# pylint: skip-file
"""add_opportunity_deferrals

Revision ID: e14fc6806e40
Revises: bb4091af03f4
Create Date: 2021-03-30 08:20:30.282767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e14fc6806e40"
down_revision = "bb4091af03f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity_deferrals",
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column(
            "supervising_officer_external_id", sa.String(length=255), nullable=False
        ),
        sa.Column("person_external_id", sa.String(length=255), nullable=False),
        sa.Column("opportunity_type", sa.String(length=255), nullable=False),
        sa.Column(
            "deferred_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deferred_until", sa.DateTime(), nullable=False),
        sa.Column("reminder_was_requested", sa.Boolean(), nullable=False),
        sa.Column(
            "opportunity_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "state_code",
            "supervising_officer_external_id",
            "person_external_id",
            "opportunity_type",
        ),
    )
    op.create_index(
        op.f("ix_opportunity_deferrals_opportunity_type"),
        "opportunity_deferrals",
        ["opportunity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_deferrals_person_external_id"),
        "opportunity_deferrals",
        ["person_external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_deferrals_state_code"),
        "opportunity_deferrals",
        ["state_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_deferrals_supervising_officer_external_id"),
        "opportunity_deferrals",
        ["supervising_officer_external_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_opportunity_deferrals_supervising_officer_external_id"),
        table_name="opportunity_deferrals",
    )
    op.drop_index(
        op.f("ix_opportunity_deferrals_state_code"), table_name="opportunity_deferrals"
    )
    op.drop_index(
        op.f("ix_opportunity_deferrals_person_external_id"),
        table_name="opportunity_deferrals",
    )
    op.drop_index(
        op.f("ix_opportunity_deferrals_opportunity_type"),
        table_name="opportunity_deferrals",
    )
    op.drop_table("opportunity_deferrals")
    # ### end Alembic commands ###
