# pylint: skip-file
"""add_client_milestones

Revision ID: 9462a38c6110
Revises: 33780ebfa36c
Create Date: 2021-08-04 15:15:50.398338

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9462a38c6110"
down_revision = "33780ebfa36c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "etl_clients", sa.Column("employment_start_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "etl_clients", sa.Column("most_recent_violation_date", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("etl_clients", "most_recent_violation_date")
    op.drop_column("etl_clients", "employment_start_date")
    # ### end Alembic commands ###
