# pylint: skip-file
"""last_known_date_of_employment

Revision ID: bce6d723d796
Revises: e14fc6806e40
Create Date: 2021-03-30 14:12:45.792452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bce6d723d796"
down_revision = "e14fc6806e40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "etl_clients",
        sa.Column("last_known_date_of_employment", sa.Date(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("etl_clients", "last_known_date_of_employment")
    # ### end Alembic commands ###
