# pylint: skip-file
"""add pseudonymized_id column

Revision ID: 9a817e072599
Revises: 288a17af2532
Create Date: 2023-10-25 11:49:14.587200

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9a817e072599"
down_revision = "288a17af2532"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roster", sa.Column("pseudonymized_id", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roster", "pseudonymized_id")
    # ### end Alembic commands ###
