# pylint: skip-file
"""remove role column

Revision ID: 1e530729d217
Revises: fb34705fd055
Create Date: 2024-08-08 13:17:28.900430

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e530729d217"
down_revision = "fb34705fd055"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roster", "role")
    op.drop_column("user_override", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_override",
        sa.Column("role", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "roster",
        sa.Column("role", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
