# pylint: skip-file
"""Change blocked_on type to TIMESTAMP WITH TIME ZONE

Revision ID: 753d0dab5a29
Revises: b8252ea2c53b
Create Date: 2025-02-04 17:04:24.015923

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "753d0dab5a29"
down_revision = "b8252ea2c53b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_override",
        "blocked_on",
        type_=sa.TIMESTAMP(timezone=True),
        existing_type=sa.DateTime(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_override",
        "blocked_on",
        type_=sa.DateTime(),
        existing_type=sa.TIMESTAMP(timezone=True),
    )
    # ### end Alembic commands ###
