# pylint: skip-file
"""add_zero_grants_tooltip_field

Revision ID: 9e4e5447eccf
Revises: 86cdd33c2c58
Create Date: 2024-10-31 14:53:13.356674

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9e4e5447eccf"
down_revision = "86cdd33c2c58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opportunity_configuration",
        sa.Column("zero_grants_tooltip", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opportunity_configuration", "zero_grants_tooltip")
    # ### end Alembic commands ###
