# Infrastructure configuration for components that will be deployed to the recidiviz-ingest-us-ar project

import:
  - ../catalogs/terraform-backend # Import Terraform backend configuration
  - ../catalogs/organization-settings # Import billing_account and organization_id `settings.context`

settings:
  context:
    project_id: recidiviz-ingest-us-ar
    state_code: US_AR

# The variables set here are automatically provided to any components used in this stack.
vars:
  project_id: "{{ .settings.context.project_id }}"

components:
  terraform:
    # Provisions the recidiviz-ingest-us-ar project
    vendor/core-project-factory:
      vars:
        name: "{{ .settings.context.project_id }}"
        org_id: "{{ .settings.context.organization_id }}"
        folder_id: "{{ .settings.context.hipaa_folder_id }}"
        billing_account: "{{ .settings.context.billing_account }}"
        default_service_account: deprivilege
        deletion_policy: PREVENT
        domain: "{{ .settings.context.organization_domain }}"
        # Grant the owner security group owner access (can be gained with go/jit)
        group_name: "s-{{ .settings.context.project_id }}-owner"
        group_role: roles/owner
        activate_apis:
          - secretmanager.googleapis.com
          - storagetransfer.googleapis.com

    # AR pushes data to this bucket daily, then the replication rules defined for this bucket cause the data to be
    # pushed to the recidiviz-staging-direct-ingest-state-us-ar and recidiviz-123-direct-ingest-state-us-ar buckets in
    # the recidiviz-staging and recidiviz-123 projects, respectively.
    isolated-direct-ingest-bucket-with-replication:
      vars:
        project_id: "{{ .settings.context.project_id }}"
        region: us-central1
        state_code: "{{ .settings.context.state_code }}"
        # AR uses an IBM CloudPak module to upload files to our GCS bucket. The upload process writes a set
        # of temporary files to the bucket that have a long numerical suffix tacked to the end. We filter out these
        # files by only allowing files that match expected file names, but excluding files that have those file names
        # plus the extra temporary file prefix. We maintain a list of expected files and excluded prefixes that we
        # specify here.These must be the paths relative to the isolated-direct-ingest-bucket-with-replication module.
        replication_spec_include_prefixes_file_path: "../../../../../../../recidiviz/ingest/direct/regions/us_ar/raw_data/expected_file_names.txt"
        replication_spec_exclude_prefixes_file_path: "../../../../../../../recidiviz/ingest/direct/regions/us_ar/raw_data/excluded_file_name_prefixes.txt"

    # This is the service account with permissions
    direct-ingest-gcs-service-account:
      vars:
        project_id: "{{ .settings.context.project_id }}"
        state_code: "{{ .settings.context.state_code }}"
        ingest_bucket_name: !terraform.output isolated-direct-ingest-bucket-with-replication recidiviz-ingest-us-ar bucket_name
