# Infrastructure configuration for components that will be deployed to the recidiviz-ingest-us-ar project

# Import billing_account and organization_id
import:
  - ../catalogs/organization-settings

settings:
  context:
    project_id: recidiviz-ingest-us-ar
    state_code: US_AR

# The variables set here are automatically provided to any components used in this stack.
vars:
  project_id: "{{ .settings.context.project_id }}"

terraform:
  # Describes where the Terraform state file for these centrally-managed components is stored
  # https://atmos.tools/core-concepts/components/terraform/backends#google-cloud-storage-backend
  backend_type: gcs
  backend:
    gcs:
      bucket: recidiviz-devops-tf-state
      prefix: "projects/{{ .settings.context.project_id }}/{{ .component }}"
  # This provides the default configuration for our Terraform providers
  # https://atmos.tools/core-concepts/components/terraform/providers
  providers:
    google:
      project: "{{ .settings.context.project_id }}"

components:
  terraform:
    # Provisions the recidiviz-ingest-us-ar project
    vendor/core-project-factory:
      vars:
        name: "{{ .settings.context.project_id }}"
        org_id: "{{ .settings.context.organization_id }}"
        folder_id: "{{ .settings.context.hipaa_folder_id }}"
        billing_account: "{{ .settings.context.billing_account }}"
        default_service_account: deprivilege
        deletion_policy: PREVENT
        domain: "{{ .settings.context.organization_domain }}"
        # Grant the owner security group owner access (can be gained with go/jit)
        group_name: "s-{{ .settings.context.project_id }}-owner"
        group_role: roles/owner
        activate_apis:
          - secretmanager.googleapis.com
          - storagetransfer.googleapis.com

    # AR pushes data to this bucket daily, then the replication rules defined for this bucket cause the data to be
    # pushed to the recidiviz-staging-direct-ingest-state-us-ar and recidiviz-123-direct-ingest-state-us-ar buckets in
    # the recidiviz-staging and recidiviz-123 projects, respectively.
    isolated-direct-ingest-bucket-with-replication:
      vars:
        project_id: "{{ .settings.context.project_id }}"
        region: us-central1
        state_code: "{{ .settings.context.state_code }}"

    # This is the service account with permissions
    direct-ingest-gcs-service-account:
      vars:
        project_id: "{{ .settings.context.project_id }}"
        state_code: "{{ .settings.context.state_code }}"
        ingest_bucket_name: !terraform.output isolated-direct-ingest-bucket-with-replication recidiviz-ingest-us-ar bucket_name
