# Infrastructure configuration for components that will be deployed to the recidiviz-staging

import:
  - ../catalogs/terraform-backend # Import Terraform backend configuration
  - ../catalogs/organization-settings # Import billing_account and organization_id `settings.context`

settings:
  context:
    project_id: recidiviz-staging

# The variables set here are automatically provided to any components used in this stack.
vars:
  project_id: "{{ .settings.context.project_id }}"

components:
  terraform:
    dag-triggering:
      vars:
        composer:
          environment: orchestration-v2
          location: us-central1

        dags:
          # Monitoring runs hourly
          hourly_monitoring_dag:
            schedule:
              - 0 * * * *

          # Calculation runs daily in staging at 6am EST
          calculation_dag:
            config:
              INGEST_INSTANCE: PRIMARY
            schedule:
              - 0 3 * * *

          # SFTP runs every hour at the 45th minute
          sftp_dag:
            schedule:
              - 45 * * * *

          # Raw data runs at 5 am EST
          raw_data_import_dag:
            config:
              INGEST_INSTANCE: PRIMARY
            schedule:
              - 0 2 * * *
