# pylint: skip-file
"""update_metric_metadata_add_dynamic_filter_options_column

Revision ID: 97f2dbce20ca
Revises: 881601233da9
Create Date: 2026-01-13 17:11:07.392029

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "97f2dbce20ca"
down_revision = "881601233da9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "metric_metadata",
        sa.Column(
            "dynamic_filter_options",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("metric_metadata", "dynamic_filter_options")
    # ### end Alembic commands ###
