reference_data_type: acronyms
entries:
  - acronym: PO
    expansion: Parole Officer
  - acronym: FT
    expansion: Full-Time
  - acronym: PT
    expansion: Part-Time
  - acronym: UA
    expansion: Urinalysis
  - acronym: CRC
    expansion: Community Reentry Center
