address:
  dataset_id: export_archives
  table_id: product_roster_archive
description: This table contains daily archives of the product roster
schema:
  - name: export_date
    type: DATE
    mode: NULLABLE
  - name: state_code
    type: STRING
    mode: NULLABLE
  - name: email_address
    type: STRING
    mode: NULLABLE
  - name: user_hash
    type: STRING
    mode: NULLABLE
  - name: external_id
    type: STRING
    mode: NULLABLE
  - name: first_name
    type: STRING
    mode: NULLABLE
  - name: last_name
    type: STRING
    mode: NULLABLE
  - name: role
    type: STRING
    mode: NULLABLE
  - name: roles
    type: STRING
    mode: REPEATED
  - name: district
    type: STRING
    mode: NULLABLE
  - name: routes_workflows
    type: BOOLEAN
    mode: NULLABLE
  - name: routes_workflowsSupervision
    type: BOOLEAN
    mode: NULLABLE
  - name: routes_workflowsFacilities
    type: BOOLEAN
    mode: NULLABLE
  - name: routes_insights
    type: BOOLEAN
    mode: NULLABLE
  - name: default_feature_variants
    type: STRING
    mode: NULLABLE
  - name: override_feature_variants
    type: STRING
    mode: NULLABLE
clustering_fields: null
