name: "Airflow Python Setup"
runs:
  using: "composite"
  steps:
    - name: Use Python 3.11.8
      run: pyenv global 3.11.8
      shell: bash
    - name: Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
      with:
        version: "0.9.x"
    - name: uv caching
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      id: uv-caching
      with:
        path: |
          recidiviz/airflow/.venv
          ~/.cache/uv
        key: ${{ runner.os }}-${{ runner.arch }}-uv-airflow-v1-${{ hashFiles('**/recidiviz/airflow/uv.lock') }}
        # If we haven't cached a venv for the new version of the lock file this will
        # restore the cache for the most recent version. Since most of the time our
        # lock file updates only change a small number of packages, this speeds up
        # the sync step significantly.
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-uv-airflow-
    - name: Sync uv
      # Always sync to ensure environment matches lock file, even on cache hit.
      # The package cache (~/.cache/uv) speeds this up significantly.
      # The --frozen flag ensures we use exactly what's in the lock file without updating it.
      working-directory: ./recidiviz/airflow
      run: uv sync --all-extras --frozen
      shell: bash
