runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /start
  script: scraper.recidiviz.app
  login: admin

- url: /stop_scraper
  script: scraper.queue_control.app

- url: /resume_scraper
  script: scraper.queue_control.app

- url: /scraper
  script: scraper.worker.app
  login: admin

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: "3.7.3"

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'