runtime: python27
api_version: 1
threadsafe: false
instance_class: F2

includes:
- base.yaml

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: "3.7.3"
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'

# The first five regular expressions are the default values which have to be
# made explicit when defining custom values: https://cloud.google.com/appengine/docs/standard/python/config/appref
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^local\.yaml$
