runtime: python27
api_version: 1
threadsafe: false
instance_class: F2

# It is imperative that the module and version values are set to default for local and not production,
# due to a GAE MapReduce bug: https://github.com/GoogleCloudPlatform/appengine-mapreduce/issues/103.
# Comment these out to run locally. TODO: make this dynamic by environment.
#module: default
#version: default

includes:
- lib/mapreduce/include.yaml

handlers:
- url: /start
  script: scraper.recidiviz.app
  login: admin

- url: /stop_scraper
  script: scraper.queue_control.app

- url: /resume_scraper
  script: scraper.queue_control.app

- url: /scraper
  script: scraper.worker.app
  login: admin

- url: /_ah/pipeline.*
  script: mapreduce.lib.pipeline.handlers._APP
  login: admin

- url: /calculator_pipeline
  script: calculator.pipeline.app

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: "3.7.3"

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'