includes:
- lib/mapreduce/include.yaml

builtins:
# Deferred is required to use google.appengine.ext.deferred
- deferred: on

handlers:
- url: /scraper/start
  script: recidiviz.ingest.scraper_control.app

- url: /scraper/stop
  script: recidiviz.ingest.scraper_control.app

- url: /scraper/resume
  script: recidiviz.ingest.scraper_control.app

- url: /scraper/work
  script: recidiviz.ingest.worker.app

- url: /_ah/pipeline.*
  script: recidiviz.mapreduce.lib.pipeline.handlers._APP
  login: admin

- url: /calculator_pipeline
  script: recidiviz.calculator.recidivism.pipeline.app

- url: /datastore_export
  script: cloud_datastore_admin.app
  login: admin
