includes:
- lib/mapreduce/include.yaml

builtins:
# Deferred is required to use google.appengine.ext.deferred
- deferred: on

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /v1/records
  script: recidiviz.persistence.actions.app

- url: /_ah/pipeline.*
  script: recidiviz.mapreduce.lib.pipeline.handlers._APP
  login: admin

- url: /.*
  script: recidiviz.server.app
