builtins:
# Deferred is required to use google.appengine.ext.deferred
- deferred: on

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /.*
  script: recidiviz.server.app
