# Details of pipeline jobs to deploy to templates

# Number of pipelines to deploy
pipeline_count: 1

# List of pipelines with their necessary details
pipelines:
  - pipeline: recidivism
    job_name: full-recidivism-calculations
    input: state
    output: dataflow_metrics
