steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    # TODO(#6678): Remove test when confirmed that caching works and pick caching strategy
    - --destination=us.gcr.io/$PROJECT_ID/appengine-test/kaniko:latest
    - --cache=true
