# Defines services needed to run the Justice Counts Control Panel app (on top of shared services already in docker-compose.yaml)
# Run via `docker-compose -f docker-compose.yaml -f docker-compose.justice-counts.yaml up`

version: "3"

services:
  control_panel_backend:
    image: us.gcr.io/recidiviz-staging/appengine/default:latest
    volumes:
      - "./recidiviz:/app/recidiviz/"
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: pipenv run flask run -h 0.0.0.0
    environment:
      - FLASK_APP=/app/recidiviz/justice_counts/control_panel/server.py
      - FLASK_ENV=development
      - IS_DEV=true
      - JUSTICE_COUNTS_DEVELOPMENT_POSTGRES_URL=postgresql://postgres:example@db/justice_counts
