# Defines all services used by the resource search applications
# Run via `docker-compose -f docker-compose.resource-search.yaml up`
services:
  resource_search_db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.resource-search
    environment:
      POSTGRES_USER: resource_user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: us_id
    ports:
      - "5440:5432"
    volumes:
      - resource_search_db_data:/var/lib/postgresql/data
      - resource_search_db_socket:/var/run/postgresql/

  resource_search_migrations:
    image: us-docker.pkg.dev/recidiviz-staging/appengine/default:latest
    volumes:
      - "./recidiviz:/app/recidiviz/"
    depends_on:
      - resource_search_db
    command: pipenv run alembic -c recidiviz/persistence/database/migrations/resource_search_alembic.ini upgrade head
    environment:
      - IS_DEV=true
      - SQLALCHEMY_DB_HOST=resource_search_db
      - SQLALCHEMY_DB_NAME=us_id
      - SQLALCHEMY_DB_USER=resource_user
      - SQLALCHEMY_DB_PASSWORD=example
      - SQLALCHEMY_USE_SSL=0

volumes:
  resource_search_db_data:
  resource_search_db_socket:
