# Defines services needed to run the Justice Counts Control Panel app (on top of shared services already in docker-compose.yaml)
# Run via `docker-compose -f docker-compose.yaml -f docker-compose.justice-counts.yaml up`

version: "3"

services:
  control_panel_backend:
    image: us.gcr.io/recidiviz-staging/appengine/default:latest
    volumes:
      - "./recidiviz:/app/recidiviz/"
      - justice_counts_db_socket:/cloudsql/justice_counts
    depends_on:
      - justice_counts_db
    ports:
      - "5001:5000"
    # Running with threads and no debugger seems to improve latency on first request
    command: pipenv run flask run -h 0.0.0.0  --with-threads --no-debugger
    environment:
      - FLASK_APP=/app/recidiviz/justice_counts/control_panel/server.py
      - FLASK_ENV=development
      - IS_DEV=true
