FROM us-docker.pkg.dev/recidiviz-staging/recidiviz-base/default:latest

WORKDIR /app/recidiviz

COPY --chown=recidiviz . /app

WORKDIR /app

CMD pipenv run hypercorn recidiviz.prototypes.app:app --bind :8080

# This makes docker not report that our container is healthy until the workers are
# started and returning 200 on the `/health` endpoint.
HEALTHCHECK --interval=5s --timeout=3s \
    CMD curl -f http://localhost:8080/health || exit 1
