runtime: custom
env: flex
service: default

resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 100
automatic_scaling:
  min_num_instances: 4

liveness_check:
  check_interval_sec: 5
  initial_delay_sec: 30
readiness_check:
  app_start_timeout_sec: 60

beta_settings:
  cloud_sql_instances: recidiviz-123:us-east4:prod-data, recidiviz-123:us-east1:prod-state-data, recidiviz-123:us-east1:usmamiddlesex-redundant, recidiviz-123:us-east1:prod-operations-data
env_variables:
  RECIDIVIZ_ENV: production
  FROM_EMAIL_ADDRESS: reports@recidiviz.org
  FROM_EMAIL_NAME: Recidiviz Reports
