runtime: custom
env: flex
service: default

resources:
  # TODO(1628): This was bumped from cpu: 1, memory_gb: 2 to temporarily mitigate issues we're seeing with cloud tasks
  # getting stuck if they are running when a new instance gets spun up.
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1

liveness_check:
  check_interval_sec: 5
  initial_delay_sec: 0
readiness_check:
  app_start_timeout_sec: 60

beta_settings:
  cloud_sql_instances: recidiviz-123:us-east4:prod-data, recidiviz-123:us-east1:prod-state-data, recidiviz-123:us-east1:usmamiddlesex-redundant
env_variables:
  RECIDIVIZ_ENV: production
