runtime: custom
env: flex
service: scrapers

# Note: if we adjust the number of instances or amount of cpu upwards,
# we may have to adjust the number of max connections in our postgres instances.
# See the discussion in #5497 for more context, and see the docs:
# https://cloud.google.com/sql/docs/quotas#postgresql for more.
resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 100
automatic_scaling:
  min_num_instances: 4

liveness_check:
  check_interval_sec: 5
  initial_delay_sec: 30
readiness_check:
  app_start_timeout_sec: 120

beta_settings:
  cloud_sql_instances: recidiviz-123:us-east4:prod-data, recidiviz-123:us-east1:usmamiddlesex-redundant, recidiviz-123:us-east4:prod-data-0x9ea199
env_variables:
  RECIDIVIZ_ENV: production
  RECIDIVIZ_SERVICE: scrapers
  FROM_EMAIL_ADDRESS: reports@recidiviz.org
  FROM_EMAIL_NAME: Recidiviz Reports
