runtime: custom
env: flex
service: default

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1

liveness_check:
  check_interval_sec: 5
  initial_delay_sec: 0
readiness_check:
  app_start_timeout_sec: 60

beta_settings:
  # TODO(1831): Add state cloudsql instance once it has been created
  cloud_sql_instances: recidiviz-123:us-east4:prod-data, recidiviz-123:us-east1:usmamiddlesex-redundant
env_variables:
  RECIDIVIZ_ENV: production
