runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
beta_settings:
  cloud_sql_instances: recidiviz-staging:us-east4:dev-data
env_variables:
  RECIDIVIZ_ENV: production
