runtime: custom
env: flex
service: default

# Note: if we adjust the number of instances or amount of cpu upwards,
# we may have to adjust the number of max connections in our postgres instances.
# See the discussion in #5497 for more context, and see the docs:
# https://cloud.google.com/sql/docs/quotas#postgresql for more.
resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 100
automatic_scaling:
  min_num_instances: 4

liveness_check:
  check_interval_sec: 5
  initial_delay_sec: 30
readiness_check:
  app_start_timeout_sec: 120

beta_settings:
  cloud_sql_instances: recidiviz-staging:us-east1:dev-state-data, recidiviz-staging:us-east1:dev-operations-data, recidiviz-staging:us-east1:dev-justice-counts-data, recidiviz-staging:us-central1:dev-case-triage-data-0af0a, recidiviz-staging:us-east1:dev-operations-data-0x17a1b, recidiviz-staging:us-east1:dev-state-data-0x28b48

env_variables:
  RECIDIVIZ_ENV: staging
  RECIDIVIZ_SERVICE: default
  FROM_EMAIL_ADDRESS: reports@recidiviz.org
  FROM_EMAIL_NAME: Recidiviz Reports

# Per zenhub-tasks#358, our app engine needs egress traffic to be issued on a static IP address:
# Reference doc: https://cloud.google.com/appengine/docs/standard/python/outbound-ip-addresses#static-ip
# for more details.
vpc_access_connector:
  name: "projects/recidiviz-staging/locations/us-east1/connectors/redis-vpc-connector"
  egress_setting: all-traffic
