runtime: custom
env: flex

resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 100
automatic_scaling:
  min_num_instances: 4

liveness_check:
  check_interval_sec: 5
  initial_delay_sec: 30
readiness_check:
  app_start_timeout_sec: 60

beta_settings:
  cloud_sql_instances: recidiviz-staging:us-east4:dev-data, recidiviz-123:us-east1:usmamiddlesex-redundant, recidiviz-staging:us-east1:dev-state-data, recidiviz-staging:us-east1:dev-operations-data
env_variables:
  RECIDIVIZ_ENV: staging
  MEMORY_DEBUG: true
  MONITOR_THREAD: true
