runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1

liveness_check:
  check_interval_sec: 5
  initial_delay_sec: 0
readiness_check:
  app_start_timeout_sec: 60

beta_settings:
  cloud_sql_instances: recidiviz-staging:us-east4:dev-data, recidiviz-123:us-east1:usmamiddlesex-redundant, recidiviz-staging:us-east1:dev-state-data
env_variables:
  RECIDIVIZ_ENV: staging
