# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2021 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================
"""Metricfile objects used for supervision metrics."""

from recidiviz.justice_counts.dimensions.person import (
    GenderRestricted,
    RaceAndEthnicity,
)
from recidiviz.justice_counts.dimensions.supervision import (
    NewOffenseType,
    SupervisionCaseType,
    SupervisionIndividualType,
    SupervisionStaffType,
    SupervisionTerminationType,
    SupervisionViolationType,
)
from recidiviz.justice_counts.metricfile import MetricFile
from recidiviz.justice_counts.metrics import parole, probation, supervision

SUPERVISION_METRIC_FILES = [
    MetricFile(
        canonical_filename="annual_budget",
        definition=supervision.annual_budget,
    ),
    MetricFile(
        canonical_filename="total_staff",
        definition=supervision.total_staff,
    ),
    MetricFile(
        canonical_filename="total_staff_by_type",
        definition=supervision.total_staff,
        disaggregation=SupervisionStaffType,
        disaggregation_column_name="staff_type",
    ),
    MetricFile(
        canonical_filename="supervision_violations",
        definition=supervision.supervision_violations,
    ),
    MetricFile(
        canonical_filename="supervision_violations_by_type",
        definition=supervision.supervision_violations,
        disaggregation=SupervisionViolationType,
        disaggregation_column_name="violation_type",
    ),
    MetricFile(
        canonical_filename="new_supervision_cases",
        definition=supervision.new_supervision_cases,
    ),
    MetricFile(
        canonical_filename="new_supervision_cases_by_type",
        definition=supervision.new_supervision_cases,
        disaggregation=SupervisionCaseType,
        disaggregation_column_name="supervision_type",
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision",
        definition=supervision.individuals_under_supervision,
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision_by_type",
        definition=supervision.individuals_under_supervision,
        disaggregation=SupervisionIndividualType,
        disaggregation_column_name="supervision_type",
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision_by_gender",
        allowed_filenames=["individuals_gender"],
        definition=supervision.individuals_under_supervision,
        disaggregation=GenderRestricted,
        disaggregation_column_name="gender",
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision_by_race",
        allowed_filenames=[
            "individuals_under_supervision_by_race/ethnicity",
            "individuals_race",
        ],
        definition=supervision.individuals_under_supervision,
        disaggregation=RaceAndEthnicity,
        disaggregation_column_name="race/ethnicity",
    ),
    MetricFile(
        canonical_filename="supervision_terminations",
        definition=supervision.supervision_terminations,
    ),
    MetricFile(
        canonical_filename="supervision_terminations_by_type",
        definition=supervision.supervision_terminations,
        disaggregation=SupervisionTerminationType,
        disaggregation_column_name="termination_type",
    ),
    MetricFile(
        canonical_filename="reconvictions",
        definition=supervision.reconviction_while_on_supervision,
    ),
    MetricFile(
        canonical_filename="reconvictions_by_type",
        definition=supervision.reconviction_while_on_supervision,
        disaggregation=NewOffenseType,
        disaggregation_column_name="offense_type",
    ),
]

PAROLE_METRIC_FILES = [
    MetricFile(
        canonical_filename="annual_budget",
        definition=parole.annual_budget,
    ),
    MetricFile(
        canonical_filename="total_staff",
        definition=parole.total_staff,
    ),
    MetricFile(
        canonical_filename="total_staff_by_type",
        definition=parole.total_staff,
        disaggregation=SupervisionStaffType,
        disaggregation_column_name="staff_type",
    ),
    MetricFile(
        canonical_filename="supervision_violations",
        definition=parole.supervision_violations,
    ),
    MetricFile(
        canonical_filename="supervision_violations_by_type",
        definition=parole.supervision_violations,
        disaggregation=SupervisionViolationType,
        disaggregation_column_name="violation_type",
    ),
    MetricFile(
        canonical_filename="new_supervision_cases",
        definition=parole.new_supervision_cases,
    ),
    MetricFile(
        canonical_filename="new_supervision_cases_by_type",
        definition=parole.new_supervision_cases,
        disaggregation=SupervisionCaseType,
        disaggregation_column_name="supervision_type",
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision",
        definition=parole.individuals_under_supervision,
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision_by_type",
        definition=parole.individuals_under_supervision,
        disaggregation=SupervisionIndividualType,
        disaggregation_column_name="supervision_type",
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision_by_gender",
        allowed_filenames=["individuals_gender"],
        definition=parole.individuals_under_supervision,
        disaggregation=GenderRestricted,
        disaggregation_column_name="gender",
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision_by_race",
        allowed_filenames=[
            "individuals_under_supervision_by_race/ethnicity",
            "individuals_race",
        ],
        definition=parole.individuals_under_supervision,
        disaggregation=RaceAndEthnicity,
        disaggregation_column_name="race/ethnicity",
    ),
    MetricFile(
        canonical_filename="supervision_terminations",
        definition=parole.supervision_terminations,
    ),
    MetricFile(
        canonical_filename="supervision_terminations_by_type",
        definition=parole.supervision_terminations,
        disaggregation=SupervisionTerminationType,
        disaggregation_column_name="termination_type",
    ),
    MetricFile(
        canonical_filename="reconvictions",
        definition=parole.reconviction_while_on_supervision,
    ),
    MetricFile(
        canonical_filename="reconvictions_by_type",
        definition=parole.reconviction_while_on_supervision,
        disaggregation=NewOffenseType,
        disaggregation_column_name="offense_type",
    ),
]

PROBATION_METRIC_FILES = [
    MetricFile(
        canonical_filename="annual_budget",
        definition=probation.annual_budget,
    ),
    MetricFile(
        canonical_filename="total_staff",
        definition=probation.total_staff,
    ),
    MetricFile(
        canonical_filename="total_staff_by_type",
        definition=probation.total_staff,
        disaggregation=SupervisionStaffType,
        disaggregation_column_name="staff_type",
    ),
    MetricFile(
        canonical_filename="supervision_violations",
        definition=probation.supervision_violations,
    ),
    MetricFile(
        canonical_filename="supervision_violations_by_type",
        definition=probation.supervision_violations,
        disaggregation=SupervisionViolationType,
        disaggregation_column_name="violation_type",
    ),
    MetricFile(
        canonical_filename="new_supervision_cases",
        definition=probation.new_supervision_cases,
    ),
    MetricFile(
        canonical_filename="new_supervision_cases_by_type",
        definition=probation.new_supervision_cases,
        disaggregation=SupervisionCaseType,
        disaggregation_column_name="supervision_type",
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision",
        definition=probation.individuals_under_supervision,
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision_by_type",
        definition=probation.individuals_under_supervision,
        disaggregation=SupervisionIndividualType,
        disaggregation_column_name="supervision_type",
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision_by_gender",
        allowed_filenames=["individuals_gender"],
        definition=probation.individuals_under_supervision,
        disaggregation=GenderRestricted,
        disaggregation_column_name="gender",
    ),
    MetricFile(
        canonical_filename="individuals_under_supervision_by_race",
        allowed_filenames=[
            "individuals_under_supervision_by_race/ethnicity",
            "individuals_race",
        ],
        definition=probation.individuals_under_supervision,
        disaggregation=RaceAndEthnicity,
        disaggregation_column_name="race/ethnicity",
    ),
    MetricFile(
        canonical_filename="supervision_terminations",
        definition=probation.supervision_terminations,
    ),
    MetricFile(
        canonical_filename="supervision_terminations_by_type",
        definition=probation.supervision_terminations,
        disaggregation=SupervisionTerminationType,
        disaggregation_column_name="termination_type",
    ),
    MetricFile(
        canonical_filename="reconvictions",
        definition=probation.reconviction_while_on_supervision,
    ),
    MetricFile(
        canonical_filename="reconvictions_by_type",
        definition=probation.reconviction_while_on_supervision,
        disaggregation=NewOffenseType,
        disaggregation_column_name="offense_type",
    ),
]
