# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2026 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================
"""Identifies new documents that need to be uploaded to the document store."""

import uuid
from datetime import datetime

import attr

from recidiviz.big_query.big_query_address import BigQueryAddress
from recidiviz.big_query.big_query_client import BigQueryClient
from recidiviz.common.constants.states import StateCode
from recidiviz.NOT_FOR_PRODUCTION_USE.documents.store.active_compartment_filter import (
    build_active_entities_cte_sql,
    build_active_entities_exists_filter,
)
from recidiviz.NOT_FOR_PRODUCTION_USE.documents.store.document_collection_config import (
    DOCUMENT_ID_COLUMN_NAME,
    DOCUMENT_UPDATE_DATETIME_COLUMN_NAME,
    DocumentCollectionConfig,
    DocumentRootEntityIdType,
)

DEFAULT_TEMP_DATASET_ID = "temp_document_collection"


def _get_root_entity_column_names(
    root_entity_type: DocumentRootEntityIdType,
) -> list[str]:
    """Returns the column names for the given root entity type."""
    match root_entity_type:
        case DocumentRootEntityIdType.PERSON_ID:
            return ["person_id"]
        case DocumentRootEntityIdType.PERSON_EXTERNAL_ID:
            return ["person_external_id", "person_external_id_type"]
        case DocumentRootEntityIdType.STAFF_ID:
            return ["staff_id"]
        case DocumentRootEntityIdType.STAFF_EXTERNAL_ID:
            return ["staff_external_id", "staff_external_id_type"]
        case _:
            raise NotImplementedError(
                f"Column names not implemented for {root_entity_type.value}"
            )


def document_id_sql_clause(state_code: StateCode, document_text_column: str) -> str:
    """Returns a SQL expression that generates a document ID from document text.

    Uses SHA256 rather than FARM_FINGERPRINT because SHA256 can be reliably
    replicated in Python (via hashlib.sha256), whereas FARM_FINGERPRINT's exact
    implementation is internal to BigQuery. Benchmarking on 16M case notes (~99GB)
    showed no meaningful performance difference between the two.
    """
    return f"TO_HEX(SHA256(CONCAT('{state_code.value}', '|', {document_text_column})))"


@attr.define
class NewDocumentIdentifier:
    """Identifies documents that need to be uploaded to the document store.

    Compares documents generated by a collection's query against the metadata
    table to find documents that haven't been uploaded yet.
    """

    big_query_client: BigQueryClient
    project_id: str
    temp_dataset_id: str = DEFAULT_TEMP_DATASET_ID
    metadata_dataset_override: str | None = None

    def find_new_documents_in_collection(
        self,
        collection_config: DocumentCollectionConfig,
        sample_size: int | None = None,
        sample_entity_count: int | None = None,
        active_in_compartment: str | None = None,
        lookback_days: int | None = None,
        person_ids: list[int] | None = None,
    ) -> BigQueryAddress:
        """Finds documents that need to be uploaded for the given collection.

        Args:
            collection_config: Configuration for the document collection.
            sample_size: If provided, limits the number of new documents returned.
            sample_entity_count: If provided, samples N distinct entities (e.g., people)
                and returns ALL documents for those entities. This is useful for
                getting complete document histories for a subset of people.
                Cannot be used together with sample_size.
            active_in_compartment: If provided, restricts entity sampling to people
                with an active session in the given compartment (e.g., SUPERVISION,
                INCARCERATION). Only supported for PERSON_* root entity types.
                Cannot be used together with person_ids.
            lookback_days: If provided, only includes documents whose
                document_update_datetime is within the last N days.
            person_ids: If provided, restricts documents to those belonging to the
                given person IDs. Cannot be used together with active_in_compartment,
                sample_entity_count, or sample_size.

        Returns:
            Address of a temporary table containing new documents with columns:
            - document_id: The unique identifier for the document
            - document_text: The text content of the document
            - sequence_num: A sequential number for batch processing
            - Plus all primary key columns from the collection config
        """
        if sample_size and sample_entity_count:
            raise ValueError(
                "Cannot specify both sample_size and sample_entity_count. "
                "Use sample_size to limit total documents, or sample_entity_count "
                "to get all documents for N entities."
            )
        if person_ids and (active_in_compartment or sample_entity_count or sample_size):
            raise ValueError(
                "Cannot specify person_ids together with active_in_compartment, "
                "sample_entity_count, or sample_size. person_ids is a standalone "
                "filtering mode for running extractions on specific person entities."
            )
        if collection_config.state_code is None:
            raise ValueError(
                "Cannot find new documents for state-agnostic collection. "
                f"Collection: {collection_config.collection_name}"
            )

        state_code = collection_config.state_code
        metadata_address = collection_config.metadata_table_address(
            dataset_override=self.metadata_dataset_override
        )

        # Build the document generation query
        doc_gen_query = collection_config.build_document_generation_query(
            self.project_id
        )

        # Build list of primary key columns for the SELECT clause
        pk_columns = [
            col.name for col in collection_config.other_primary_key_column_schemas
        ]
        pk_columns_str = ", ".join(pk_columns) if pk_columns else ""

        # Get root entity columns based on the root entity type
        root_entity_columns = _get_root_entity_column_names(
            collection_config.root_entity_type
        )
        root_entity_columns_str = ", ".join(root_entity_columns)

        # Get additional metadata columns
        additional_metadata_columns = [
            col.name for col in collection_config.additional_metadata_column_schemas
        ]
        additional_metadata_columns_str = (
            ", ".join(additional_metadata_columns)
            if additional_metadata_columns
            else ""
        )

        # Build the query to find new documents
        # First, check if metadata table exists
        metadata_table_exists = self.big_query_client.table_exists(metadata_address)

        if metadata_table_exists:
            # Filter out documents that already exist in the metadata table
            filter_clause = f"""
            WHERE generated_docs.{DOCUMENT_ID_COLUMN_NAME} NOT IN (
                SELECT {DOCUMENT_ID_COLUMN_NAME}
                FROM `{self.project_id}.{metadata_address.dataset_id}.{metadata_address.table_id}`
            )
            """
        else:
            # No metadata table yet, all documents are new
            filter_clause = ""

        # Build sampling clauses
        limit_clause = f"LIMIT {sample_size}" if sample_size else ""

        # Build active compartment filter CTE and clause
        active_entities_cte = ""
        if active_in_compartment:
            active_entities_cte = (
                build_active_entities_cte_sql(
                    root_entity_type=collection_config.root_entity_type,
                    project_id=self.project_id,
                    state_code=state_code,
                    active_in_compartment=active_in_compartment,
                )
                + ","
            )

        # Entity-based sampling: sample N distinct entities, get all their docs
        entity_sample_cte = ""
        entity_filter = ""
        if sample_entity_count:
            # Build a composite key from all root entity columns
            entity_key_expr = (
                "CONCAT("
                + ", '|', ".join(
                    f"CAST({col} AS STRING)" for col in root_entity_columns
                )
                + ")"
            )

            # When active_in_compartment is set, sample only from active entities
            active_filter_in_sample = ""
            if active_in_compartment:
                active_filter_in_sample = (
                    "WHERE "
                    + build_active_entities_exists_filter(
                        root_entity_type=collection_config.root_entity_type,
                        table_alias="generated_docs",
                    )
                )

            entity_sample_cte = f"""
        sampled_entities AS (
            SELECT DISTINCT {root_entity_columns_str}
            FROM generated_docs
            {active_filter_in_sample}
            ORDER BY FARM_FINGERPRINT({entity_key_expr})
            LIMIT {sample_entity_count}
        ),"""
            # Build join condition for all entity columns
            entity_join_conditions = " AND ".join(
                f"generated_docs.{col} = sampled_entities.{col}"
                for col in root_entity_columns
            )
            # Use WHERE if no filter_clause, otherwise AND
            entity_filter_prefix = "WHERE" if not metadata_table_exists else "AND"
            entity_filter = f"""
            {entity_filter_prefix} EXISTS (
                SELECT 1 FROM sampled_entities
                WHERE {entity_join_conditions}
            )"""

        # When active_in_compartment is set but entity sampling is NOT used,
        # add the active filter directly to filtered_docs
        active_filter_in_docs = ""
        if active_in_compartment and not sample_entity_count:
            has_where = metadata_table_exists  # filter_clause starts with WHERE
            prefix = "AND" if has_where else "WHERE"
            active_filter_in_docs = (
                f"\n            {prefix} "
                + build_active_entities_exists_filter(
                    root_entity_type=collection_config.root_entity_type,
                    table_alias="generated_docs",
                )
            )

        # Build lookback filter to restrict by document_update_datetime
        lookback_filter = ""
        if lookback_days is not None:
            has_prior_where = (
                metadata_table_exists
                or bool(entity_filter)
                or bool(active_filter_in_docs)
            )
            lookback_prefix = "AND" if has_prior_where else "WHERE"
            lookback_filter = (
                f"\n            {lookback_prefix} generated_docs.{DOCUMENT_UPDATE_DATETIME_COLUMN_NAME}"
                f" >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL {lookback_days} DAY)"
            )

        # Build person_ids filter
        person_ids_cte = ""
        person_ids_filter = ""
        if person_ids:
            ids_str = ", ".join(str(pid) for pid in person_ids)
            match collection_config.root_entity_type:
                case DocumentRootEntityIdType.PERSON_ID:
                    has_prior_where = (
                        metadata_table_exists
                        or bool(entity_filter)
                        or bool(lookback_filter)
                    )
                    prefix = "AND" if has_prior_where else "WHERE"
                    person_ids_filter = f"\n            {prefix} generated_docs.person_id IN ({ids_str})"
                case DocumentRootEntityIdType.PERSON_EXTERNAL_ID:
                    person_ids_cte = f"""person_id_entities AS (
                SELECT ext_id.external_id AS person_external_id,
                                ext_id.id_type AS person_external_id_type
                FROM `{self.project_id}.normalized_state.state_person_external_id` ext_id
                WHERE ext_id.person_id IN ({ids_str})
                  AND ext_id.state_code = '{state_code.value}'
            ),"""
                    has_prior_where = (
                        metadata_table_exists
                        or bool(entity_filter)
                        or bool(lookback_filter)
                    )
                    prefix = "AND" if has_prior_where else "WHERE"
                    person_ids_filter = (
                        f"\n            {prefix} EXISTS (SELECT 1 FROM person_id_entities"
                        f" WHERE person_id_entities.person_external_id = generated_docs.person_external_id"
                        f" AND person_id_entities.person_external_id_type = generated_docs.person_external_id_type)"
                    )
                case _:
                    raise ValueError(
                        f"person_ids filtering is not supported for "
                        f"root entity type {collection_config.root_entity_type.value}."
                    )

        # Generate unique table name for this batch
        batch_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        batch_uuid = uuid.uuid4().hex[:8]
        table_id = f"{collection_config.collection_name.lower()}_batch_{batch_timestamp}_{batch_uuid}"

        query = f"""
        WITH generated_docs AS (
            SELECT
                {document_id_sql_clause(state_code, 'document_text')} AS {DOCUMENT_ID_COLUMN_NAME},
                document_text,
                {DOCUMENT_UPDATE_DATETIME_COLUMN_NAME},
                {pk_columns_str + ',' if pk_columns_str else ''}
                {additional_metadata_columns_str + ',' if additional_metadata_columns_str else ''}
                {root_entity_columns_str}
            FROM ({doc_gen_query})
        ),{active_entities_cte}{person_ids_cte}{entity_sample_cte}
        filtered_docs AS (
            SELECT *
            FROM generated_docs
            {filter_clause}
            {entity_filter}
            {active_filter_in_docs}
            {lookback_filter}
            {person_ids_filter}
            {limit_clause}
        )
        SELECT
            {DOCUMENT_ID_COLUMN_NAME},
            document_text,
            {DOCUMENT_UPDATE_DATETIME_COLUMN_NAME},
            {pk_columns_str + ',' if pk_columns_str else ''}
            {additional_metadata_columns_str + ',' if additional_metadata_columns_str else ''}
            {root_entity_columns_str},
            ROW_NUMBER() OVER (ORDER BY {DOCUMENT_ID_COLUMN_NAME}) AS sequence_num
        FROM filtered_docs
        """

        result_address = BigQueryAddress(
            dataset_id=self.temp_dataset_id,
            table_id=table_id,
        )

        self.big_query_client.create_table_from_query(
            address=result_address,
            query=query,
            use_query_cache=False,
            overwrite=True,
        )

        return result_address
