config:
  #TODO(#36926): Update to represent all states and compartments with a configured workflow
  - state_code: US_CA
    compartment: SUPERVISION
    access_filter: caseload
    is_supervision_officer: true
    has_null_district: true
  - state_code: US_CA
    compartment: SUPERVISION
    access_filter: district
    is_supervision_officer: true
    has_null_district: false
  - state_code: US_CA
    compartment: SUPERVISION
    access_filter: state
    is_supervision_officer: false
  - state_code: US_IX
    compartment: SUPERVISION
    access_filter: district
  - state_code: US_IX
    compartment: INCARCERATION
    access_filter: state
  - state_code: US_ME
    compartment: SUPERVISION
    access_filter: state
  - state_code: US_ME
    compartment: INCARCERATION
    access_filter: state
  - state_code: US_MI
    compartment: SUPERVISION
    access_filter: district
  - state_code: US_MO
    compartment: INCARCERATION
    access_filter: state
  - state_code: US_ND
    compartment: SUPERVISION
    access_filter: state
  - state_code: US_OR
    compartment: SUPERVISION
    access_filter: state
  - state_code: US_PA
    compartment: SUPERVISION
    access_filter: state
  - state_code: US_TN
    compartment: SUPERVISION
    access_filter: district
  - state_code: US_TN
    compartment: INCARCERATION
    access_filter: state
