# Configuration for which validations to run for region US_TX.

region_code: US_TX
# TODO(#32851): Enable validations for US_TX.
dev_mode: True
exclusions: []
max_allowed_error_overrides: []
num_allowed_rows_overrides: []
