# Configuration for which validations to run for region US_NE.

region_code: US_NE
# TODO(#31894): Enable validations for US_NE.
dev_mode: True
exclusions: []
max_allowed_error_overrides: []
num_allowed_rows_overrides: []
