# Configuration for which validations to run for region US_NE.

region_code: US_NE
dev_mode: False
exclusions:
  - validation_name: session_new_admissions_with_no_sentence_date_imposed
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: NE is being hydrated only with v2 sentences
  - validation_name: sessions_missing_closest_sentence_imposed_group
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: NE is being hydrated only with v2 sentences
  - validation_name: session_liberty_releases_with_no_sentence_completion_date
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: NE is being hydrated only with v2 sentences
  - validation_name: case_insights_rates_missing_charges
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason:
      Sentencing assistance case insights are not configured/launched for this
      state
  - validation_name: person_caseload_location_sessions_caseload
    exclusion_type: BROKEN
    exclusion_reason: Failing at 82%, will be addressed in #TODO(#47003)
  - validation_name: person_caseload_location_sessions_location
    exclusion_type: BROKEN
    exclusion_reason: Failing at 82%, will be addressed in #TODO(#47003)
max_allowed_error_overrides:
  - validation_name: state_supervision_violation_response_by_response_date_stable_counts
    hard_max_allowed_error_override: .38
    override_reason: This is standard variation for this entity month to month.
  - validation_name: state_supervision_violation_by_violation_date_stable_counts
    hard_max_allowed_error_override: .38
    override_reason: This is standard variation for this entity month to month.
  - validation_name: state_supervision_period_by_start_date_stable_counts
    hard_max_allowed_error_override: .38
    override_reason: This is standard variation for this entity month to month.
num_allowed_rows_overrides:
  - validation_name: overlapping_supervision_periods
    hard_num_allowed_rows_override: 12
    override_reason:
      Currently only 6 instances as of 02/14/25. These are data entry errors
      from Nebraska and have been brought to their attention.
