# Configuration for which validations to run for region US_AR.

region_code: US_AR
exclusions: []
max_allowed_error_overrides: []
num_allowed_rows_overrides:
  - validation_name: location_metadata_missing_staff_location_period_locations
    hard_num_allowed_rows_override: 10
    override_reason:
      AR location metadata pulls locations from the ORGANIZATIONPROF table, but doesn't
      include locations with ORGANIZATIONTYPE M9 (Employer (Other)) or Z9 (Unknown). There
      are a handful of staff periods associated with these types of locations, mainly "Unknown".
