# Configuration for which validations to run for region US_AR.

region_code: US_AR
# TODO(#17084): Enable validations for US_AR.
dev_mode: True
exclusions: []
max_allowed_error_overrides: []
num_allowed_rows_overrides: []
