version: 2.1

orbs:
  terraform: circleci/terraform@1.1.1

# This section defines variables that are used throughout the code.
# A variable defined `&my_var` may be referenced elsewhere as `*my_var`.
aliases:
  # Restores the pipenv to the most recent version, either the one that is already cached for this version of Pipfile.lock, or the most current previously cached one.
  # See: https://circleci.com/docs/2.0/caching/#restoring-cache
  - &restore_pipenv_cache
    restore_cache:
      keys:
        - pipenv-cache-v1-{{ checksum "Pipfile.lock" }}
        - pipenv-cache-v1-
        - pipenv-cache-

  - &pipenv_sync
    run:
      name: Sync pipenv
      command: |
        pipenv sync --dev

  # Caches the synced pipenv for the current version of Pipfile.lock.
  # See: https://circleci.com/docs/2.0/caching/#basic-example-of-dependency-caching
  - &save_pipenv_cache
    save_cache:
      key: pipenv-cache-v1-{{ checksum "Pipfile.lock" }}
      paths:
        - ~/.local/share/virtualenvs/

jobs:
  base-unit-tests:
    docker:
      - image: recidiviz/circleci-build-img
    resource_class: medium
    steps:
      - checkout
      - *restore_pipenv_cache
      - *pipenv_sync
      - *save_pipenv_cache
      - run:
          name: Run unit tests in parallel
          command: |
            pipenv run pytest recidiviz -n 2 --test-set parallel

  db-tests:
    docker:
      - image: recidiviz/circleci-build-img
    resource_class: medium
    steps:
      - checkout
      - *restore_pipenv_cache
      - *pipenv_sync
      - *save_pipenv_cache
      - run:
          name: Run db tests
          command: |
            pipenv run pytest recidiviz --test-set not-parallel -m 'uses_db' --with-emulator

  emulator-tests:
    docker:
      - image: recidiviz/circleci-build-img
    resource_class: large
    steps:
      - checkout
      - *restore_pipenv_cache
      - *pipenv_sync
      - *save_pipenv_cache
      - run:
          name: Run emulator tests
          command: |
            pipenv run pytest recidiviz --test-set not-parallel -m 'not uses_db' --with-emulator

  lint:
    docker:
      - image: recidiviz/circleci-build-img
    resource_class: medium
    steps:
      - checkout
      - *restore_pipenv_cache
      - *pipenv_sync
      - *save_pipenv_cache
      - terraform/validate:
          path: ./recidiviz/tools/deploy/terraform
      - run:
          name: Validate Source Modifications
          command: |
            pipenv run python -m recidiviz.tools.validate_source_modifications \
              --commit-range $(git merge-base origin/master HEAD)...HEAD
      - run:
          name: Check pipenv is locked
          command: |
            pipenv run python -m recidiviz.tools.is_pipenv_locked
      - run:
          name: Mypy Check
          command: |
            pipenv run mypy recidiviz
      - run:
          name: Pylint
          command: |
            pipenv run ./recidiviz/tools/travis/run_pylint.sh
          no_output_timeout: 20m

workflows:
  main:
    jobs:
      - lint
      - base-unit-tests
      - db-tests
      - emulator-tests
# TODO(#5266): add Copybara workflow on push to master if we're committing to CircleCI
