# pylint: skip-file
"""add_program_assignment_table

Revision ID: 2d840a47cbd6
Revises: 86b7d2889a0e
Create Date: 2019-09-20 20:47:16.411571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d840a47cbd6"
down_revision = "86b7d2889a0e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "state_program_assignment",
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("program_id", sa.String(length=255), nullable=True),
        sa.Column("program_location_id", sa.String(length=255), nullable=True),
        sa.Column(
            "participation_status",
            sa.Enum(
                "EXTERNAL_UNKNOWN",
                "PRESENT_WITHOUT_INFO",
                "DISCHARGED",
                "IN_PROGRESS",
                "PENDING",
                name="state_program_assignment_participation_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "participation_status_raw_text", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "discharge_reason",
            sa.Enum(
                "EXTERNAL_UNKNOWN",
                "ABSCONDED",
                "ADVERSE_TERMINATION",
                "COMPLETED",
                "MOVED",
                "OPTED_OUT",
                "PROGRAM_TRANSFER",
                "REINCARCERATED",
                name="state_program_assignment_discharge_reason",
            ),
            nullable=True,
        ),
        sa.Column("discharge_reason_raw_text", sa.String(length=255), nullable=True),
        sa.Column("referral_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("discharge_date", sa.Date(), nullable=True),
        sa.Column("program_assignment_id", sa.Integer(), nullable=False),
        sa.Column("referring_agent_id", sa.Integer(), nullable=True),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["state_person.person_id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["referring_agent_id"],
            ["state_agent.agent_id"],
        ),
        sa.PrimaryKeyConstraint("program_assignment_id"),
    )
    op.create_index(
        op.f("ix_state_program_assignment_external_id"),
        "state_program_assignment",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_state_program_assignment_state_code"),
        "state_program_assignment",
        ["state_code"],
        unique=False,
    )
    op.create_table(
        "state_program_assignment_history",
        sa.Column("valid_from", sa.DateTime(), nullable=False),
        sa.Column("valid_to", sa.DateTime(), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("program_id", sa.String(length=255), nullable=True),
        sa.Column("program_location_id", sa.String(length=255), nullable=True),
        sa.Column(
            "participation_status",
            sa.Enum(
                "EXTERNAL_UNKNOWN",
                "PRESENT_WITHOUT_INFO",
                "DISCHARGED",
                "IN_PROGRESS",
                "PENDING",
                name="state_program_assignment_participation_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "participation_status_raw_text", sa.String(length=255), nullable=True
        ),
        sa.Column(
            "discharge_reason",
            sa.Enum(
                "EXTERNAL_UNKNOWN",
                "ABSCONDED",
                "ADVERSE_TERMINATION",
                "COMPLETED",
                "MOVED",
                "OPTED_OUT",
                "PROGRAM_TRANSFER",
                "REINCARCERATED",
                name="state_program_assignment_discharge_reason",
            ),
            nullable=True,
        ),
        sa.Column("discharge_reason_raw_text", sa.String(length=255), nullable=True),
        sa.Column("referral_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("discharge_date", sa.Date(), nullable=True),
        sa.Column("program_assignment_history_id", sa.Integer(), nullable=False),
        sa.Column("program_assignment_id", sa.Integer(), nullable=False),
        sa.Column("referring_agent_id", sa.Integer(), nullable=True),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["state_person.person_id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["program_assignment_id"],
            ["state_program_assignment.program_assignment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["referring_agent_id"],
            ["state_agent.agent_id"],
        ),
        sa.PrimaryKeyConstraint("program_assignment_history_id"),
    )
    op.create_index(
        op.f("ix_state_program_assignment_history_external_id"),
        "state_program_assignment_history",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_state_program_assignment_history_program_assignment_id"),
        "state_program_assignment_history",
        ["program_assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_state_program_assignment_history_state_code"),
        "state_program_assignment_history",
        ["state_code"],
        unique=False,
    )
    op.create_table(
        "state_supervision_period_program_assignment_association",
        sa.Column("supervision_period_id", sa.Integer(), nullable=True),
        sa.Column("program_assignment_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["program_assignment_id"],
            ["state_program_assignment.program_assignment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["supervision_period_id"],
            ["state_supervision_period.supervision_period_id"],
        ),
    )
    op.create_table(
        "state_incarceration_period_program_assignment_association",
        sa.Column("incarceration_period_id", sa.Integer(), nullable=True),
        sa.Column("program_assignment_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["incarceration_period_id"],
            ["state_incarceration_period.incarceration_period_id"],
        ),
        sa.ForeignKeyConstraint(
            ["program_assignment_id"],
            ["state_program_assignment.program_assignment_id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("state_incarceration_period_program_assignment_association")
    op.drop_table("state_supervision_period_program_assignment_association")
    op.drop_index(
        op.f("ix_state_program_assignment_history_state_code"),
        table_name="state_program_assignment_history",
    )
    op.drop_index(
        op.f("ix_state_program_assignment_history_program_assignment_id"),
        table_name="state_program_assignment_history",
    )
    op.drop_index(
        op.f("ix_state_program_assignment_history_external_id"),
        table_name="state_program_assignment_history",
    )
    op.drop_table("state_program_assignment_history")
    op.drop_index(
        op.f("ix_state_program_assignment_state_code"),
        table_name="state_program_assignment",
    )
    op.drop_index(
        op.f("ix_state_program_assignment_external_id"),
        table_name="state_program_assignment",
    )
    op.drop_table("state_program_assignment")

    op.execute("DROP TYPE state_program_assignment_discharge_reason;")
    op.execute("DROP TYPE state_program_assignment_participation_status;")
    # ### end Alembic commands ###
