# pylint: skip-file
"""shorten_decision_type_entry_name

Revision ID: fbf7e6528526
Revises: 6a107111b6a2
Create Date: 2019-11-22 22:29:00.235506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbf7e6528526'
down_revision = '6a107111b6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_supervision_violation_response_decision_entry',
    sa.Column('state_code', sa.String(length=255), nullable=False),
    sa.Column('decision', postgresql.ENUM('CONTINUANCE', 'DELAYED_ACTION', 'EXTENSION', 'REVOCATION', 'SERVICE_TERMINATION', 'SUSPENSION', name='state_supervision_violation_response_decision', create_type=False), nullable=True),
    sa.Column('decision_raw_text', sa.String(length=255), nullable=True),
    sa.Column('revocation_type', postgresql.ENUM('REINCARCERATION', 'RETURN_TO_SUPERVISION', 'SHOCK_INCARCERATION', 'TREATMENT_IN_PRISON', name='state_supervision_violation_response_revocation_type', create_type=False), nullable=True),
    sa.Column('revocation_type_raw_text', sa.String(length=255), nullable=True),
    sa.Column('supervision_violation_response_decision_entry_id', sa.Integer(), nullable=False),
    sa.Column('supervision_violation_response_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['state_person.person_id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['supervision_violation_response_id'], ['state_supervision_violation_response.supervision_violation_response_id'], ),
    sa.PrimaryKeyConstraint('supervision_violation_response_decision_entry_id')
    )
    op.create_index(op.f('ix_state_supervision_violation_response_decision_entry_state_code'), 'state_supervision_violation_response_decision_entry', ['state_code'], unique=False)
    op.create_table('state_supervision_violation_response_decision_entry_history',
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('state_code', sa.String(length=255), nullable=False),
    sa.Column('decision', postgresql.ENUM('CONTINUANCE', 'DELAYED_ACTION', 'EXTENSION', 'REVOCATION', 'SERVICE_TERMINATION', 'SUSPENSION', name='state_supervision_violation_response_decision', create_type=False), nullable=True),
    sa.Column('decision_raw_text', sa.String(length=255), nullable=True),
    sa.Column('revocation_type', postgresql.ENUM('REINCARCERATION', 'RETURN_TO_SUPERVISION', 'SHOCK_INCARCERATION', 'TREATMENT_IN_PRISON', name='state_supervision_violation_response_revocation_type', create_type=False), nullable=True),
    sa.Column('revocation_type_raw_text', sa.String(length=255), nullable=True),
    sa.Column('supervision_violation_response_decision_entry_history_id', sa.Integer(), nullable=False),
    sa.Column('supervision_violation_response_decision_entry_id', sa.Integer(), nullable=False),
    sa.Column('supervision_violation_response_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['state_person.person_id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['supervision_violation_response_decision_entry_id'], ['state_supervision_violation_response_decision_entry.supervision_violation_response_decision_entry_id'], ),
    sa.ForeignKeyConstraint(['supervision_violation_response_id'], ['state_supervision_violation_response.supervision_violation_response_id'], ),
    sa.PrimaryKeyConstraint('supervision_violation_response_decision_entry_history_id')
    )
    op.create_index(op.f('ix_state_supervision_violation_response_decision_entry_history_state_code'), 'state_supervision_violation_response_decision_entry_history', ['state_code'], unique=False)
    op.create_index(op.f('ix_state_supervision_violation_response_decision_entry_history_supervision_violation_response_decision_entry_id'), 'state_supervision_violation_response_decision_entry_history', ['supervision_violation_response_decision_entry_id'], unique=False)
    op.drop_index('ix_state_supervision_violation_response_decision_type_e_2fc7', table_name='state_supervision_violation_response_decision_type_entry_histor')
    op.drop_index('ix_state_supervision_violation_response_decision_type_e_ba56', table_name='state_supervision_violation_response_decision_type_entry_histor')
    op.drop_table('state_supervision_violation_response_decision_type_entry_histor')
    op.drop_index('ix_state_supervision_violation_response_decision_type_e_a335', table_name='state_supervision_violation_response_decision_type_entry')
    op.drop_table('state_supervision_violation_response_decision_type_entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_supervision_violation_response_decision_type_entry',
    sa.Column('state_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('decision', postgresql.ENUM('CONTINUANCE', 'DELAYED_ACTION', 'EXTENSION', 'REVOCATION', 'SERVICE_TERMINATION', 'SUSPENSION', name='state_supervision_violation_response_decision', create_type=False), autoincrement=False, nullable=True),
    sa.Column('decision_raw_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('revocation_type', postgresql.ENUM('REINCARCERATION', 'RETURN_TO_SUPERVISION', 'SHOCK_INCARCERATION', 'TREATMENT_IN_PRISON', name='state_supervision_violation_response_revocation_type', create_type=False), autoincrement=False, nullable=True),
    sa.Column('revocation_type_raw_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('supervision_violation_response_decision_type_entry_id', sa.INTEGER(), server_default=sa.text("nextval('state_supervision_violation_r_supervision_violation_respon_seq2'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('supervision_violation_response_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['state_person.person_id'], name='state_supervision_violation_response_decision_ty_person_id_fkey', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['supervision_violation_response_id'], ['state_supervision_violation_response.supervision_violation_response_id'], name='state_supervision_violation__supervision_violation_respon_fkey2'),
    sa.PrimaryKeyConstraint('supervision_violation_response_decision_type_entry_id', name='state_supervision_violation_response_decision_type_entry_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_state_supervision_violation_response_decision_type_e_a335', 'state_supervision_violation_response_decision_type_entry', ['state_code'], unique=False)
    op.create_table('state_supervision_violation_response_decision_type_entry_histor',
    sa.Column('valid_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('valid_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('state_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('decision', postgresql.ENUM('CONTINUANCE', 'DELAYED_ACTION', 'EXTENSION', 'REVOCATION', 'SERVICE_TERMINATION', 'SUSPENSION', name='state_supervision_violation_response_decision', create_type=False), autoincrement=False, nullable=True),
    sa.Column('decision_raw_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('revocation_type', postgresql.ENUM('REINCARCERATION', 'RETURN_TO_SUPERVISION', 'SHOCK_INCARCERATION', 'TREATMENT_IN_PRISON', name='state_supervision_violation_response_revocation_type', create_type=False), autoincrement=False, nullable=True),
    sa.Column('revocation_type_raw_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('supervision_violation_response_decision_type_entry_history_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supervision_violation_response_decision_type_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supervision_violation_response_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['state_person.person_id'], name='state_supervision_violation_response_decision_t_person_id_fkey1', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['supervision_violation_response_decision_type_entry_id'], ['state_supervision_violation_response_decision_type_entry.supervision_violation_response_decision_type_entry_id'], name='state_supervision_violation__supervision_violation_respon_fkey3'),
    sa.ForeignKeyConstraint(['supervision_violation_response_id'], ['state_supervision_violation_response.supervision_violation_response_id'], name='state_supervision_violation__supervision_violation_respon_fkey4'),
    sa.PrimaryKeyConstraint('supervision_violation_response_decision_type_entry_history_id', name='state_supervision_violation_response_decision_type_entry_h_pkey')
    )
    op.create_index('ix_state_supervision_violation_response_decision_type_e_ba56', 'state_supervision_violation_response_decision_type_entry_histor', ['state_code'], unique=False)
    op.create_index('ix_state_supervision_violation_response_decision_type_e_2fc7', 'state_supervision_violation_response_decision_type_entry_histor', ['supervision_violation_response_decision_type_entry_id'], unique=False)
    op.drop_index(op.f('ix_state_supervision_violation_response_decision_entry_history_supervision_violation_response_decision_entry_id'), table_name='state_supervision_violation_response_decision_entry_history')
    op.drop_index(op.f('ix_state_supervision_violation_response_decision_entry_history_state_code'), table_name='state_supervision_violation_response_decision_entry_history')
    op.drop_table('state_supervision_violation_response_decision_entry_history')
    op.drop_index(op.f('ix_state_supervision_violation_response_decision_entry_state_code'), table_name='state_supervision_violation_response_decision_entry')
    op.drop_table('state_supervision_violation_response_decision_entry')
    # ### end Alembic commands ###