# pylint: skip-file
"""conditions_no_length_limit

Revision ID: 438944c4ebde
Revises: 82d0b4a12d0f
Create Date: 2020-08-10 16:21:38.321315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "438944c4ebde"
down_revision = "82d0b4a12d0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "state_supervision_period",
        "conditions",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "state_supervision_period_history",
        "conditions",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "state_supervision_period_history",
        "conditions",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "state_supervision_period",
        "conditions",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
