# pylint: skip-file
"""add_external_id_unique_constraint

Revision ID: a54c66450b78
Revises: 623ee18d757c
Create Date: 2020-11-20 11:08:33.365979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a54c66450b78"
down_revision = "623ee18d757c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "external_ids_unique_within_type_and_region",
        "state_person_external_id",
        ["state_code", "id_type", "external_id"],
        deferrable="True",
        initially="DEFERRED",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "external_ids_unique_within_type_and_region",
        "state_person_external_id",
        type_="unique",
    )
    # ### end Alembic commands ###
