# pylint: skip-file
"""duplicate_external_ids

Revision ID: 9980028da635
Revises: 826ccffeb6b8
Create Date: 2021-03-11 15:23:13.157329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9980028da635"
down_revision = "826ccffeb6b8"
branch_labels = None
depends_on = None

DEDUP_UPGRADE_QUERY = """
    WITH id_counts AS (
        SELECT state_code, external_id,
            COUNT(*) as c,
            ARRAY_AGG({primary_key} ORDER BY {primary_key}) AS {primary_key}s
        FROM {table}
        WHERE external_id IS NOT NULL AND state_code = 'US_ID'
        GROUP BY state_code, external_id
    ),
    duplicates AS (
        SELECT state_code, external_id, {primary_key},
        ROW_NUMBER() OVER (PARTITION BY external_id ORDER BY {primary_key}) AS rn
        FROM id_counts, UNNEST({primary_key}s) AS {primary_key}
        WHERE c > 1
    ),
    new_ids AS (
        SELECT state_code, {primary_key}, external_id AS old_external_id, CONCAT(external_id, '-dup', rn) AS external_id
        FROM duplicates
    )
    UPDATE {table} t
    SET external_id = new_ids.external_id
    FROM new_ids
    WHERE t.{primary_key} = new_ids.{primary_key}
"""


def upgrade():
    table_to_primary_key = {"state_incarceration_sentence": "incarceration_sentence_id"}
    with op.get_context().autocommit_block():
        for table, primary_key in table_to_primary_key.items():
            op.execute(DEDUP_UPGRADE_QUERY.format(table=table, primary_key=primary_key))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
