# pylint: skip-file
"""drop_source_supervision_violation_response

Revision ID: f1ce18e8950e
Revises: 190df7ac651c
Create Date: 2021-08-18 13:54:35.518293

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f1ce18e8950e"
down_revision = "190df7ac651c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_state_incarceration_period_source_supervision_violat_fd77",
        table_name="state_incarceration_period",
    )
    op.drop_constraint(
        "state_incarceration_period_source_supervision_violation_re_fkey",
        "state_incarceration_period",
        type_="foreignkey",
    )
    op.create_table_comment(
        "state_incarceration_period",
        "The StateIncarcerationPeriod object represents information about a single period of incarceration, defined as a contiguous stay by a particular person in a particular facility. As a person transfers from facility to facility, these are modeled as multiple abutting incarceration periods. This also extends to temporary transfers to, say, hospitals or court appearances. The sequence of incarceration periods can be squashed into longer conceptual periods (e.g. from the first admission to the final release for a particular sentence) for analytical purposes, such as measuring recidivism and revocation -- this is done with a fine-grained examination of the admission dates, admission reasons, release dates, and release reasons of consecutive incarceration periods.<br /><br />Handling of incarceration periods is a crucial aspect of our platform and involves work in jurisdictional ingest mappings, entity matching, and calculation. Fortunately, this means that we have practice working with varied representations of this information.<br /><br />Incarceration Periods can be children of either Incarceration Sentences or Supervision Sentences, for reasons established in the descriptions of those objects. Incarceration periods have zero to many Incarceration Incidents as children, and zero to many Parole Decisions. They also may have Assessments or Program Assignments as children, if any of those objects are explicitly related to this particular period of incarceration.",
        existing_comment="The StateIncarcerationPeriod object represents information about a single period of incarceration, defined as a contiguous stay by a particular person in a particular facility. As a person transfers from facility to facility, these are modeled as multiple abutting incarceration periods. This also extends to temporary transfers to, say, hospitals or court appearances. The sequence of incarceration periods can be squashed into longer conceptual periods (e.g. from the first admission to the final release for a particular sentence) for analytical purposes, such as measuring recidivism and revocation -- this is done with a fine-grained examination of the admission dates, admission reasons, release dates, and release reasons of consecutive incarceration periods.<br /><br />Handling of incarceration periods is a crucial aspect of our platform and involves work in jurisdictional ingest mappings, entity matching, and calculation. Fortunately, this means that we have practice working with varied representations of this information.<br /><br />Incarceration Periods can be children of either Incarceration Sentences or Supervision Sentences, for reasons established in the descriptions of those objects. Incarceration periods have zero to many Incarceration Incidents as children, and zero to many Parole Decisions. They also may have Assessments or Program Assignments as children, if any of those objects are explicitly related to this particular period of incarceration. Incarceration periods also optionally have a child source_supervision_violation_response, which is a Supervision Violation Response of type REVOCATION that corresponds to the revocation that caused the re-incarceration leading back to this particular incarceration period. This connection is established during entity matching, unless that link can be explicitly provided in the source data.",
        schema=None,
    )
    op.drop_column(
        "state_incarceration_period", "source_supervision_violation_response_id"
    )
    op.drop_index(
        "ix_state_incarceration_period_history_source_supervisio_363e",
        table_name="state_incarceration_period_history",
    )
    op.drop_constraint(
        "state_incarceration_period_hi_source_supervision_violation_fkey",
        "state_incarceration_period_history",
        type_="foreignkey",
    )
    op.drop_column(
        "state_incarceration_period_history", "source_supervision_violation_response_id"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "state_incarceration_period_history",
        sa.Column(
            "source_supervision_violation_response_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Unique identifier for a(n) source supervision violation response, generated automatically by the Recidiviz system. This identifier is not stable over time (it may change if historical data is re-ingested), but should be used within the context of a given dataset to connect this object to relevant source supervision violation response information.",
        ),
    )
    op.create_foreign_key(
        "state_incarceration_period_hi_source_supervision_violation_fkey",
        "state_incarceration_period_history",
        "state_supervision_violation_response",
        ["source_supervision_violation_response_id"],
        ["supervision_violation_response_id"],
    )
    op.create_index(
        "ix_state_incarceration_period_history_source_supervisio_363e",
        "state_incarceration_period_history",
        ["source_supervision_violation_response_id"],
        unique=False,
    )
    op.add_column(
        "state_incarceration_period",
        sa.Column(
            "source_supervision_violation_response_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Unique identifier for a(n) source supervision violation response, generated automatically by the Recidiviz system. This identifier is not stable over time (it may change if historical data is re-ingested), but should be used within the context of a given dataset to connect this object to relevant source supervision violation response information.",
        ),
    )
    op.create_table_comment(
        "state_incarceration_period",
        "The StateIncarcerationPeriod object represents information about a single period of incarceration, defined as a contiguous stay by a particular person in a particular facility. As a person transfers from facility to facility, these are modeled as multiple abutting incarceration periods. This also extends to temporary transfers to, say, hospitals or court appearances. The sequence of incarceration periods can be squashed into longer conceptual periods (e.g. from the first admission to the final release for a particular sentence) for analytical purposes, such as measuring recidivism and revocation -- this is done with a fine-grained examination of the admission dates, admission reasons, release dates, and release reasons of consecutive incarceration periods.<br /><br />Handling of incarceration periods is a crucial aspect of our platform and involves work in jurisdictional ingest mappings, entity matching, and calculation. Fortunately, this means that we have practice working with varied representations of this information.<br /><br />Incarceration Periods can be children of either Incarceration Sentences or Supervision Sentences, for reasons established in the descriptions of those objects. Incarceration periods have zero to many Incarceration Incidents as children, and zero to many Parole Decisions. They also may have Assessments or Program Assignments as children, if any of those objects are explicitly related to this particular period of incarceration. Incarceration periods also optionally have a child source_supervision_violation_response, which is a Supervision Violation Response of type REVOCATION that corresponds to the revocation that caused the re-incarceration leading back to this particular incarceration period. This connection is established during entity matching, unless that link can be explicitly provided in the source data.",
        existing_comment="The StateIncarcerationPeriod object represents information about a single period of incarceration, defined as a contiguous stay by a particular person in a particular facility. As a person transfers from facility to facility, these are modeled as multiple abutting incarceration periods. This also extends to temporary transfers to, say, hospitals or court appearances. The sequence of incarceration periods can be squashed into longer conceptual periods (e.g. from the first admission to the final release for a particular sentence) for analytical purposes, such as measuring recidivism and revocation -- this is done with a fine-grained examination of the admission dates, admission reasons, release dates, and release reasons of consecutive incarceration periods.<br /><br />Handling of incarceration periods is a crucial aspect of our platform and involves work in jurisdictional ingest mappings, entity matching, and calculation. Fortunately, this means that we have practice working with varied representations of this information.<br /><br />Incarceration Periods can be children of either Incarceration Sentences or Supervision Sentences, for reasons established in the descriptions of those objects. Incarceration periods have zero to many Incarceration Incidents as children, and zero to many Parole Decisions. They also may have Assessments or Program Assignments as children, if any of those objects are explicitly related to this particular period of incarceration.",
        schema=None,
    )
    op.create_foreign_key(
        "state_incarceration_period_source_supervision_violation_re_fkey",
        "state_incarceration_period",
        "state_supervision_violation_response",
        ["source_supervision_violation_response_id"],
        ["supervision_violation_response_id"],
    )
    op.create_index(
        "ix_state_incarceration_period_source_supervision_violat_fd77",
        "state_incarceration_period",
        ["source_supervision_violation_response_id"],
        unique=False,
    )
    # ### end Alembic commands ###
