# pylint: skip-file
"""more_nonnull_enums

Revision ID: c267025e7a4d
Revises: 77faf8397348
Create Date: 2023-05-05 15:32:27.301436

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c267025e7a4d"
down_revision = "77faf8397348"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "state_person_ethnicity",
        "ethnicity",
        existing_type=postgresql.ENUM(
            "EXTERNAL_UNKNOWN",
            "HISPANIC",
            "NOT_HISPANIC",
            "INTERNAL_UNKNOWN",
            name="state_ethnicity",
        ),
        nullable=False,
        existing_comment="A person’s reported ethnicity.",
    )
    op.alter_column(
        "state_supervision_case_type_entry",
        "case_type",
        existing_type=postgresql.ENUM(
            "DOMESTIC_VIOLENCE",
            "DRUG_COURT",
            "FAMILY_COURT",
            "GENERAL",
            "MENTAL_HEALTH_COURT",
            "SERIOUS_MENTAL_ILLNESS",
            "SEX_OFFENSE",
            "VETERANS_COURT",
            "EXTERNAL_UNKNOWN",
            "INTERNAL_UNKNOWN",
            name="state_supervision_case_type",
        ),
        nullable=False,
        existing_comment="The type of case that describes the associated period of supervision.",
    )
    op.alter_column(
        "state_supervision_violation_type_entry",
        "violation_type",
        existing_type=postgresql.ENUM(
            "ABSCONDED",
            "ESCAPED",
            "FELONY",
            "LAW",
            "MISDEMEANOR",
            "MUNICIPAL",
            "TECHNICAL",
            "EXTERNAL_UNKNOWN",
            "INTERNAL_UNKNOWN",
            name="state_supervision_violation_type",
        ),
        nullable=False,
        existing_comment="The type of violation.",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "state_supervision_violation_type_entry",
        "violation_type",
        existing_type=postgresql.ENUM(
            "ABSCONDED",
            "ESCAPED",
            "FELONY",
            "LAW",
            "MISDEMEANOR",
            "MUNICIPAL",
            "TECHNICAL",
            "EXTERNAL_UNKNOWN",
            "INTERNAL_UNKNOWN",
            name="state_supervision_violation_type",
        ),
        nullable=True,
        existing_comment="The type of violation.",
    )
    op.alter_column(
        "state_supervision_case_type_entry",
        "case_type",
        existing_type=postgresql.ENUM(
            "DOMESTIC_VIOLENCE",
            "DRUG_COURT",
            "FAMILY_COURT",
            "GENERAL",
            "MENTAL_HEALTH_COURT",
            "SERIOUS_MENTAL_ILLNESS",
            "SEX_OFFENSE",
            "VETERANS_COURT",
            "EXTERNAL_UNKNOWN",
            "INTERNAL_UNKNOWN",
            name="state_supervision_case_type",
        ),
        nullable=True,
        existing_comment="The type of case that describes the associated period of supervision.",
    )
    op.alter_column(
        "state_person_ethnicity",
        "ethnicity",
        existing_type=postgresql.ENUM(
            "EXTERNAL_UNKNOWN",
            "HISPANIC",
            "NOT_HISPANIC",
            "INTERNAL_UNKNOWN",
            name="state_ethnicity",
        ),
        nullable=True,
        existing_comment="A person’s reported ethnicity.",
    )
    # ### end Alembic commands ###
