# pylint: skip-file
"""add_conducting_staff_id_fields

Revision ID: 7265620b4316
Revises: 2fca0410ce38
Create Date: 2023-03-21 11:44:04.922754

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7265620b4316"
down_revision = "2fca0410ce38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "state_assessment",
        sa.Column(
            "conducting_staff_external_id",
            sa.String(length=255),
            nullable=True,
            comment="The external id of the staff member conducting this assessment. This field with the conducting_staff_external_id_type field make up a primary key for the state_staff_external_id table.",
        ),
    )
    op.add_column(
        "state_assessment",
        sa.Column(
            "conducting_staff_external_id_type",
            sa.String(length=255),
            nullable=True,
            comment="The ID type associated with external id of the staff member conducting this assessment. This field with the conducting_staff_external_id field make up a primary key for the state_staff_external_id table.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("state_assessment", "conducting_staff_external_id_type")
    op.drop_column("state_assessment", "conducting_staff_external_id")
    # ### end Alembic commands ###
