# pylint: skip-file
"""add_housing_unit_category

Revision ID: 674bbfc9bd0a
Revises: 58975f48febc
Create Date: 2023-07-16 14:27:02.005204

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "674bbfc9bd0a"
down_revision = "58975f48febc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    housing_unit_category = postgresql.ENUM(
        "SOLITARY_CONFINEMENT",
        "GENERAL",
        "INTERNAL_UNKNOWN",
        "EXTERNAL_UNKNOWN",
        name="state_incarceration_period_housing_unit_category",
    )
    housing_unit_category.create(op.get_bind())
    op.add_column(
        "state_incarceration_period",
        sa.Column(
            "housing_unit_category",
            sa.Enum(
                "SOLITARY_CONFINEMENT",
                "GENERAL",
                "INTERNAL_UNKNOWN",
                "EXTERNAL_UNKNOWN",
                name="state_incarceration_period_housing_unit_category",
            ),
            nullable=True,
            comment="A supertype corresponding to the housing_unit_type.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("state_incarceration_period", "housing_unit_category")
    op.execute("DROP TYPE state_incarceration_period_housing_unit_category;")
    # ### end Alembic commands ###
