# pylint: skip-file
"""add_drug_screen_metadata_col

Revision ID: 018e184b8b4e
Revises: 19c1e900f88c
Create Date: 2023-10-27 11:42:24.508957

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "018e184b8b4e"
down_revision = "19c1e900f88c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "state_drug_screen",
        sa.Column(
            "drug_screen_metadata",
            sa.Text(),
            nullable=True,
            comment="Arbitrary JSON-formatted metadata relevant to a fine understanding of this drug screen.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("state_drug_screen", "drug_screen_metadata")
    # ### end Alembic commands ###
