# pylint: skip-file
"""update_rh_enums

Revision ID: ecf3f286ba25
Revises: e8bcfe6db8e1
Create Date: 2023-09-13 10:52:35.310838

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ecf3f286ba25"
down_revision = "e8bcfe6db8e1"
branch_labels = None
depends_on = None

""" 
Update fields that were previously mapped to
StateIncarcerationPeriodHousingUnitType.PERMANENT_SOLITARY_CONFINEMENT to use new,
more granular enum values
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
    UPDATE state_incarceration_period
    SET housing_unit_type = 'DISCIPLINARY_SOLITARY_CONFINEMENT'
    WHERE state_code = 'US_OR'
    AND housing_unit_type_raw_text IN ('DSU', 'DS', 'SEG'); 

    UPDATE state_incarceration_period
    SET housing_unit_type = 'ADMINISTRATIVE_SOLITARY_CONFINEMENT'
    WHERE state_code = 'US_OR'
    AND housing_unit_type_raw_text = 'ASU';

    UPDATE state_incarceration_period
    SET housing_unit_type = 'OTHER_SOLITARY_CONFINEMENT'
    WHERE state_code = 'US_OR'
    AND housing_unit_type_raw_text IN ('IMU', 'SHU', 'SMU');

    UPDATE state_incarceration_period
    SET housing_unit_type = 'PROTECTIVE_CUSTODY'
    WHERE state_code = 'US_OR'
    AND housing_unit_type_raw_text = 'AHU';

    UPDATE state_incarceration_period
    SET housing_unit_type = 'MENTAL_HEALTH_SOLITARY_CONFINEMENT'
    WHERE state_code = 'US_OR'
    AND housing_unit_type_raw_text IN ('BHU', 'ICH');

    UPDATE state_incarceration_period
    SET housing_unit_type = 'HOSPITAL'
    WHERE state_code = 'US_OR'
    AND housing_unit_type_raw_text = 'MHI';
    """
    )

    # ### end Alembic commands ###


""" 
Uses the new StateIncarcerationPeriodHousingUnitCategory super-type to ID all fields
that were previously mapped to StateIncarcerationPeriodHousingUnitType.PERMANENT_SOLITARY_CONFINEMENT
"""


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE state_incarceration_period
        SET housing_unit_type = 'PERMANENT_SOLITARY_CONFINEMENT'
        WHERE state_code = 'US_OR'
        AND housing_unit_category = 'SOLITARY_CONFINEMENT';
        """
    )

    # ### end Alembic commands ###
