# pylint: skip-file
"""sentence_effective_date

Revision ID: 0c8cd5855782
Revises: fedb726f4772
Create Date: 2023-02-23 14:23:50.891529

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0c8cd5855782"
down_revision = "fedb726f4772"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "state_incarceration_sentence",
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The date on which a sentence effectively begins being served, including any pre-trial jail detention time if applicable.",
        ),
    )
    op.add_column(
        "state_supervision_sentence",
        sa.Column(
            "effective_date",
            sa.Date(),
            nullable=True,
            comment="The date on which a sentence effectively begins being served, including any pre-trial jail detention time if applicable.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("state_supervision_sentence", "effective_date")
    op.drop_column("state_incarceration_sentence", "effective_date")
    # ### end Alembic commands ###
