# pylint: skip-file
"""drop_task_deadline_constraint

Revision ID: c2da8c1ade37
Revises: e284041ae6d4
Create Date: 2023-10-24 16:04:14.531664

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2da8c1ade37"
down_revision = "e284041ae6d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "state_task_deadline_unique_per_person_update_date_type",
        "state_task_deadline",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "state_task_deadline_unique_per_person_update_date_type",
        "state_task_deadline",
        ["state_code", "person_id", "task_type", "task_subtype", "update_datetime"],
    )
    # ### end Alembic commands ###
