# pylint: skip-file
"""add_referring_staff_id_fields

Revision ID: fca4f7f9b740
Revises: ef74efae91ad
Create Date: 2023-03-21 14:32:56.360483

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fca4f7f9b740"
down_revision = "ef74efae91ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "state_program_assignment",
        sa.Column(
            "referring_staff_external_id",
            sa.String(length=255),
            nullable=True,
            comment="The external id of the staff member who made the program referral. This field with the referring_staff_external_id_type field make up a primary key for the state_staff_external_id table.",
        ),
    )
    op.add_column(
        "state_program_assignment",
        sa.Column(
            "referring_staff_external_id_type",
            sa.String(length=255),
            nullable=True,
            comment="The ID type associated with the external id of the staff member who made the program referral. This field with the referring_staff_external_id field make up a primary key for the state_staff_external_id table.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("state_program_assignment", "referring_staff_external_id_type")
    op.drop_column("state_program_assignment", "referring_staff_external_id")
    # ### end Alembic commands ###
