# This file tracks exclusions for each state's stable_historical_raw_data_counts
# validation. This file has two types of exclusions:
#   - PERMANENT
#     for this type of exclusion, never run a validation for this file. this is a good
#     exclusion type if you don't care if this file changes in size
#   - DATE_RANGE
#     for this type of exclusion, exclude this date range when building the validation.
#     this is a good exclusion type if a jump in file size that is above the threshold
#     is a false positive and the failure won't cycle out soon. the same file tag in the
#     same region can have multiple entries if you want to exclude two distinct datetime
#     ranges
PERMANENT:
  US_IX:
    - file_tag: RECIDIVIZ_REFERENCE_supervisor_roster
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cause large % changes
    - file_tag: RECIDIVIZ_REFERENCE_community_opportunities
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cause large % changes. This file is also maintained manually, so changes are
        always monitored.
    - file_tag: RECIDIVIZ_REFERENCE_release_to_crc_facility_mappings
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cause large % changes. This file is also maintained manually, so changes are
        always monitored.
  US_TN:
    - file_tag: Chain
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cause large % changes
    - file_tag: PhotoIDRequest
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cause large % changes
    - file_tag: SupervisionStandard
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cause large % changes
    - file_tag: SanctionLevelLookUp
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cause large % changes
    - file_tag: SupervisionLevelLookUp
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cause large % changes
    - file_tag: RECIDIVIZ_REFERENCE_supervision_locations
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cause large % changes
  US_MI:
    - file_tag: RECIDIVIZ_REFERENCE_offense_exclusion_list
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cauase large % changes
  US_OR:
    - file_tag: RCDVZ_CISUIR_INCIDENT_LOCATION
      exclusion_reason:
        Small reference file that is updated infrequently -- small changes in file size
        cause large % changes. This file is also not currently used in a view.
DATE_RANGE:
  US_MO:
    - file_tag: LBAKRDTA_TAK237
      datetime_start_inclusive: "2022-11-17T00:00:00Z"
      datetime_end_exclusive: "2023-08-30T00:00:00Z"
      exclusion_reason:
        We inconsistently import sub-sections of the file based on what is needed
        because the file itself is so big
    - file_tag: LBAKRDTA_TAK238
      datetime_start_inclusive: "2022-11-17T00:00:00Z"
      datetime_end_exclusive: "2023-04-20T00:00:00Z"
      exclusion_reason:
        We inconsistently import sub-sections of the file based on what is needed
        because the file itself is so big
    - file_tag: LBCMDATA_APFX91
      datetime_start_inclusive: "2024-05-05T00:00:00Z"
      datetime_end_exclusive: "2024-05-13T00:00:00Z"
      exclusion_reason:
        This is a small file with only ~1000 rows, so even small fluctuations cause this
        to fail on % change. This date had a reasonable change of 22 rows, so we exclude
        it from the failures.
    - file_tag: LBCMDATA_APFX91
      datetime_start_inclusive: "2024-08-11T00:00:00Z"
      datetime_end_exclusive: "2024-08-17T00:00:00Z"
      exclusion_reason:
        See above - this date range covers a ~3% increase and decrease for the ~1000 row
        table, so we can exclude it.
  US_AR:
    - file_tag: RELEASEDATECHANGE
      datetime_start_inclusive: "2024-06-12T00:00:00Z"
      datetime_end_exclusive: "2024-07-18T00:00:00Z"
      exclusion_reason:
        This is the date range between when this file was first copied to prod and when
        SFTP was configured to start directly uploading AR tables to the prod bucket.
        There's about a month between these transfers, so it's expected for some tables
        to have more rows as of the first SFTP transfer.
    - file_tag: SUPVINCENTIVE
      datetime_start_inclusive: "2024-06-12T00:00:00Z"
      datetime_end_exclusive: "2024-07-18T00:00:00Z"
      exclusion_reason:
        This is the date range between when this file was first copied to prod and when
        SFTP was configured to start directly uploading AR tables to the prod bucket.
        There's about a month between these transfers, so it's expected for some tables
        to have more rows as of the first SFTP transfer.
