# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2025 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================
"""Enumerates columns that are currently exempt from the requirement that datetime SQL
parsers are defined for any datetime column.
"""
from recidiviz.common.constants.states import StateCode
from recidiviz.utils import environment

# Columns that have `field_type: datetime` but no defined `datetime_sql_parsers`
# defined, for file tags that are referenced both in ingest views AND downstream views.
# These need to be migrated carefully - after adding SQL parsers to these columns, we
# need to confirm that there are no changes to ingest view pipeline output AND
# downstream BQ view output. NOTE: some of these columns might not actually be
# referenced at all. If a column is listed in this map, that means it's raw data file is
# referenced in both ingest views and downstream views.
# TODO(#12174): Hydrate datetime parsers for all these columns and then delete this map
DATETIME_PARSER_EXEMPTIONS_FILES_REFERENCED_IN_INGEST_VIEWS_AND_DOWNSTREAM_VIEWS: dict[
    StateCode, dict[str, list[str]]
] = {
    StateCode.US_CA: {
        "PersonParole": [
            "ControllingDischargeDate",
            "EarnedDischargeDate",
            "LATESTSUSPENDEDDATE",
            "LastCCRDate",
            "LastParoleDate",
            "ReinstateDate",
        ],
    },
    StateCode.US_IA: {
        "IA_DOC_Charges": ["ArrestDt", "MPD", "OffenseDt", "SDD", "TDD"],
        "IA_DOC_Supervision_Modifiers": [
            "HoldEndDt",
            "HoldStartDt",
            "MittimusDt",
            "SupervisionModifierEndDt",
            "SupervisionModifierStartDt",
        ],
    },
    StateCode.US_IX: {
        "asm_Assessment": ["CompletionDate", "RequestDate", "ScheduleDate"],
        "bop_BOPHearing": [
            "DecisionSubmitDate",
            "EstimateHearingDate",
            "ExecutiveStartDate",
            "ForfeitureFinalizedDate",
            "ForfeitureRecordedDate",
            "HearingEndDate",
            "HearingResumeDate",
            "HearingStartDate",
            "InsertDate",
            "ReinstateDate",
            "TentativeParoleDate",
            "UpdateDate",
        ],
        "bop_BOPVoteResult": ["InsertDate", "UpdateDate"],
        "bop_BOPVoteValue": ["InsertDate", "UpdateDate"],
        "com_Transfer": [
            "ApprovedDate",
            "CancellationDate",
            "CustodyReleaseDate",
            "HearingDate",
            "InsertDate",
            "ScheduledDate",
            "SupervisionReleaseDate",
            "TransferDate",
            "UpdateDate",
        ],
        "dsc_DACase": [
            "AuditAppealDate",
            "AuditHearingDate",
            "InsertDate",
            "OffenseDateTime",
            "UpdateDate",
        ],
        "dsc_DAProcedure": ["InsertDate", "UpdateDate"],
        "ind_OffenderNote": ["InsertDate", "UpdateDate"],
        "ind_OffenderNoteInfo": ["InsertDate", "NoteDate", "UpdateDate"],
        "ind_OffenderNoteInfo_ContactMode": ["InsertDate", "UpdateDate"],
        "ind_OffenderNoteStatus": ["InsertDate", "UpdateDate"],
        "ind_OffenderSecurityLevel": ["ApprovedDate", "InsertDate", "UpdateDate"],
        "ind_Offender_Address": ["EndDate", "InsertDate", "StartDate", "UpdateDate"],
        "ind_Offender_Phone": ["InsertDate", "UpdateDate"],
        "prb_PBCase": [
            "ForwardDate",
            "InsertDate",
            "RescissionReconsiderationDate",
            "UpdateDate",
        ],
        "prb_PBCaseSubType": ["InsertDate", "UpdateDate"],
        "ref_Address": ["InsertDate", "UpdateDate"],
        "ref_Phone": ["InsertDate", "UpdateDate"],
        "scl_Charge": [
            "ArrestDate",
            "InsertDate",
            "NextCourtDateTime",
            "OutcomeDate",
            "UpdateDate",
            "WarrantDate",
        ],
        "scl_DorOffenseType": ["EffectiveDate", "EndDate", "InsertDate", "UpdateDate"],
        "scl_Offense": ["OffenseDate"],
        "scl_SentenceOrder": ["SentenceDate"],
    },
    StateCode.US_ME: {
        "CIS_124_SUPERVISION_HISTORY": ["Assignment_Date", "Supervision_End_Date"],
        "CIS_125_CURRENT_STATUS_HIST": ["Effct_Date", "End_Date", "Ineffct_Date"],
        "CIS_309_MOVEMENT": ["Movement_Date"],
        "CIS_319_TERM": [
            "Comm_Rel_Date",
            "Curr_Cust_Rel_Date",
            "Early_Cust_Rel_Date",
            "Intake_Date",
            "Max_Cust_Rel_Date",
        ],
        "CIS_400_CHARGE": ["Offense_Date", "Referral_Date"],
        "CIS_401_CRT_ORDER_HDR": [
            "Comm_Override_Rel_Date",
            "Comm_Rel_Date",
            "Court_Finding_Date",
            "Court_Order_Sent_Date",
            "Created_On_Date",
            "Curr_Cust_Rel_Date",
            "Cust_Override_Rel_Date",
            "Early_Cust_Rel_Date",
            "Est_Sent_Start_Date",
            "Max_Cust_Rel_Date",
            "Modified_On_Date",
            "Prob_Start_Date",
        ],
        "CIS_403_CONDITION": ["Due_Date"],
        "CIS_480_VIOLATION": [
            "Arrested_Warr_Date",
            "Finding_Date",
            "Fta_Date",
            "Start_Date",
            "Toll_End_Date",
            "Toll_Start_Date",
        ],
    },
    StateCode.US_MI: {
        "ADH_OFFENDER_SENTENCE": ["last_update_date"],
        "COMS_Modifiers": ["End_Date", "Entered_Date", "Start_Date"],
        "COMS_Specialties": ["End_Date", "Entered_Date", "Start_Date"],
    },
    StateCode.US_MO: {
        "LBAKRDTA_TAK015": ["BL_IC"],
    },
    StateCode.US_ND: {
        "docstars_offensestable": ["LAST_UPDATE"],
    },
    StateCode.US_NE: {
        "CodeValue": ["codeEndDate", "codeStartDate", "createdDate", "modifiedDate"],
        "PIMSSpecialCondition": [
            "beginDate",
            "creationDateTime",
            "endDate",
            "lastUpdatedDateTime",
            "noContactEndDate",
            "sourceStartDate",
            "suspendedDate",
        ],
    },
    StateCode.US_PA: {
        "dbo_Release": ["LastModifiedDate"],
        "dbo_vwCCISAllMvmt": ["Bed_Dt", "LstMod_Dt", "Status_Dt"],
        "dbo_vwCCISAllProgDtls": ["LstMod_Dt"],
    },
    StateCode.US_TN: {
        "Classification": [
            "AppealDecisionDate",
            "AppealReceivedDate",
            "CAFDate",
            "ClassificationDate",
            "ClassificationDecisionDate",
            "ClassificationDueDate",
            "HearingDateTime",
            "LastUpdateDate",
            "PostedDate",
            "WaiverSignedDate",
        ],
        "Disciplinary": [
            "DispositionDate",
            "IncidentDate",
            "LastUpdateDate",
            "PostedDateTime",
            "RefuseToSignDate",
        ],
        "JOIdentification": ["ArrestedDate", "BirthDate", "PostedDate"],
        "JOSentence": [
            "ExecutionDate",
            "FirstConfinementCompletedDate",
            "MandatoryMinimumStartDate",
            "StayExecutionDate",
        ],
        "OffenderAttributes": [
            "DeathDate",
            "DisposalDate",
            "LastUpdateDate",
            "RestoreDate",
        ],
        "OffenderTreatment": [
            "EndDate",
            "LastUpdateDate",
            "StartDate",
            "VerifiedEndDate",
            "VerifiedStartDate",
        ],
        "Sanctions": [
            "CAReviewDate",
            "ImposedDate",
            "LastUpdateDate",
            "PPMReviewDate",
            "ProposedDate",
            "SanctionEndDate",
        ],
        "Sentence": [
            "ConfinementExpirationDate",
            "ConfinementFullExpirationDate",
            "EarliestPossibleReleaseDate",
            "ExpirationDate",
            "FullExpirationDate",
            "MandatoryParoleDate",
            "ProbationaryParoleDate",
            "RegularParoleDate",
            "ReleaseEligibilityDate",
            "SafetyValveDate",
            "SentenceChangedDate",
            "SentenceEffectiveDate",
            "SentenceStatusDate",
        ],
        "Site": ["StatusDate"],
        "SupervisionPlan": [
            "PlanEndDate",
            "PlanStartDate",
            "PostedDate",
            "StandardEndDate",
            "StandardStartDate",
        ],
        "VantagePointAssessments": ["AssignedDate", "CompletedDate", "LastUpdateDate"],
        "VantagePointRecommendations": [
            "LastUpdateDate",
            "RecommendationDate",
            "RecommendedEndDate",
        ],
        "Violations": ["ContactNoteDate"],
    },
    StateCode.US_TX: {
        "ClientData": ["Creation_Date"],
        "OfficeDescription": ["OFFC_END_DATE", "OFFC_START_DATE"],
    },
    StateCode.US_UT: {
        "case_mgr_ofndr": ["beg_dt", "end_dt", "updt_dt"],
        "crt_case": [
            "convict_dt",
            "crt_trmn_dt",
            "potential_earned_compliance_dt",
            "sent_dt",
            "sex_regis_dt",
            "updt_dt",
        ],
        "ofndr_tst": ["tst_dt", "updt_dt"],
        "ofndr_tst_eval": ["updt_dt"],
        "sprvsn_cntc": ["cntc_dt", "create_dt", "next_appt_dt", "updt_dt"],
        "tst_qstn_rspns": ["updt_dt"],
    },
}

# Columns that have `field_type: datetime` but no defined `datetime_sql_parsers`
# defined, for file tags that are referenced in ingest views but NOT downstream views.
# These need to be migrated carefully - after adding SQL parsers to these columns, we
# need to confirm that there are no changes to ingest view pipeline output. NOTE: some
# of these columns might not actually be referenced at all. If a column is listed in
# this map, that means it's raw data file is referenced in ingest views.
# TODO(#12174): Hydrate datetime parsers for all these columns and then delete this map
DATETIME_PARSER_EXEMPTIONS_FILES_REFERENCED_IN_INGEST_VIEWS_ONLY: dict[
    StateCode, dict[str, list[str]]
] = {
    StateCode.US_AZ: {
        "AZ_DOC_HWD_WARRANT": [
            "ATS_DTM",
            "CC_SIGNATURE_DTM",
            "CREATE_DTM",
            "RELEASE_TYPE_LAST_CHANGE_DTM",
            "STATUS_DTM",
        ],
        "AZ_DOC_SC_ARS_CODE": [
            "CREATE_DTM",
            "EFF_END_DTM",
            "EFF_START_DTM",
            "UPDT_DTM",
        ],
        "DOC_CLASS_ARREST_HISTORY": ["ARS_ID_LAST_MODIFIED_DATE"],
        "DOC_PR_PROGRAM": ["PR_EFF_DATE", "PR_END_DATE"],
        "ORAS_results_sheet": ["date"],
    },
    StateCode.US_CA: {
        "AssessmentInCustody": [
            "CompasCompletedDate",
            "DEVELOPDISABLEDEFFECTIVEDATE",
            "DPPVSIGNEDDATE",
            "DateCompleted",
            "FSORA_DateComputed",
            "MENTALHEALTHEFFECTIVEDATE",
            "PhysicalDPPVSignedDate",
            "Static99_DateComputed",
            "latestClassifDate",
        ],
        "AssessmentParole": [
            "CompasCompletedDate",
            "DEVELOPDISABLEDEFFECTIVEDATE",
            "DPPVSIGNEDDATE",
            "DateCompleted",
            "FSORA_DateComputed",
            "MENTALHEALTHEFFECTIVEDATE",
            "PhysicalDPPVSignedDate",
            "Static99_DateComputed",
            "latestClassifDate",
        ],
        "Delta": ["StatusDate"],
        "IncarcerationParole": ["In_Date", "Intake_Date", "ParoleEndDate", "out_date"],
        "ParoleEmployment": ["EMPLENDDATE", "EMPSTARTDATE"],
        "ParoleViolation": ["Response_Date", "Violation_Date"],
        "SupervisionSentence": ["SupvLevelChangeDate"],
    },
    StateCode.US_IA: {
        "IA_DOC_Addresses": ["AddressEndDt", "AddressStartDt"],
        "IA_DOC_BOPRevocationHearings": [
            "AutoRevokeDt",
            "ContinuedDate",
            "EnteredDt",
            "HearingDt",
            "SubmittedDt",
        ],
        "IA_DOC_FieldRuleViolations": ["EnteredDt"],
        "IA_DOC_FieldandResidentialRules": ["EndDt", "StartDt"],
        "IA_DOC_InterventionPrograms": [
            "EligibilityDt",
            "InterventionProgramEndDt",
            "InterventionProgramStartDt",
            "OrientationDt",
        ],
        "IA_DOC_Interventions": [
            "EligibilityDt",
            "InterventionEndDt",
            "InterventionStartDt",
        ],
        "IA_DOC_Movements": ["MovementDt"],
        "IA_DOC_OffenderWorkUnits": ["WorkUnitStartDt"],
        "IA_DOC_Offender_Details": ["DeceasedDt"],
        "IA_DOC_PVRReports": [
            "EnteredDt",
            "InCustodyDt",
            "PpviFiledDt",
            "ReportDt",
            "SubmittedDt",
        ],
        "IA_DOC_ParoleVR": ["EnteredDt", "ReviewDt"],
        "IA_DOC_Penalties": ["PenaltyEffectiveDt"],
        "IA_DOC_ProbationROV": ["EnteredDt", "ReportDt", "SubmittedDt"],
        "IA_DOC_ProbationROVFieldRuleViolationInfo": ["EnteredDt"],
        "IA_DOC_ProbationROVHearingResponses": ["EnteredDt", "ResponseDt"],
        "IA_DOC_Sentences": ["EnteredDt", "SentenceDt", "SentenceEndDt"],
        "IA_DOC_Specialties": ["SpecialtyEndDt", "SpecialtyStartDt"],
    },
    StateCode.US_IX: {
        "RECIDIVIZ_REFERENCE_leadership_roster": ["end_date", "start_date"],
        "asm_AssessmentDegree": ["InsertDate", "UpdateDate"],
        "asm_AssessmentTool": ["InsertDate", "UpdateDate"],
        "asm_AssessmentType": ["InsertDate", "UpdateDate"],
        "bop_BOPHearingType": ["InsertDate", "UpdateDate"],
        "clsf_Classification": [
            "ApprovedDateTime",
            "ClassificationDate",
            "HearingDate",
            "InsertDate",
            "MedicalNotifiedDate",
            "MentalHealthNotifiedDate",
            "ScheduledHearingDate",
            "UpdateDate",
        ],
        "clsf_ClassificationScoreSheet": [
            "InsertDate",
            "SecurityLevelId",
            "UpdateDate",
        ],
        "clsf_ClassificationType": ["InsertDate", "UpdateDate"],
        "com_Investigation": ["RequestDate"],
        "com_TransferReason": ["InsertDate", "UpdateDate"],
        "com_TransferType": ["InsertDate", "UpdateDate"],
        "drg_DrugTestResult": ["CollectionDate", "DateReturnedFromEx", "DateSentToEx"],
        "dsc_DADecisionOfficer": ["DaDecisionDate", "InsertDate", "UpdateDate"],
        "dsc_DAProcedureStatus": ["InsertDate", "UpdateDate"],
        "early_discharge": [
            "created_by_dt",
            "decision_date",
            "decision_official_dt",
            "decision_updt_date",
            "fine_last_pymnt_dt",
            "juris_auth_sbmt_dt",
            "jurisdiction_authize_date",
            "ncic_chk_date",
            "restitution_last_pymnt_dt",
            "submit_updt_date",
            "subst_tst_start_dt",
            "sup_aprv_sbmt_dt",
            "supervisor_review_date",
        ],
        "hsn_CounselorAssignment": ["FromDate", "InsertDate", "ToDate", "UpdateDate"],
        "hsn_CounselorAssignmentType": ["InsertDate", "UpdateDate"],
        "ind_AliasName": ["InsertDate", "UpdateDate"],
        "ind_AliasNameType": ["InsertDate", "UpdateDate"],
        "ind_EthnicOrigin": ["InsertDate", "UpdateDate"],
        "ind_Gender": ["InsertDate", "UpdateDate"],
        "ind_LegalStatus": ["InsertDate", "UpdateDate"],
        "ind_LegalStatusObjectCharge": ["InsertDate", "UpdateDate"],
        "ind_Offender": ["BirthDate", "InsertDate", "UpdateDate"],
        "ind_OffenderLegalStatus": [
            "EndDate",
            "InsertDate",
            "PreviousEndDate",
            "StartDate",
            "UpdateDate",
        ],
        "ind_Offender_EmailAddress": ["InsertDate", "UpdateDate"],
        "ind_Offender_QuestionnaireTemplate": [
            "AssignedDate",
            "CompletedDate",
            "InsertDate",
            "UpdateDate",
        ],
        "ind_Race": ["InsertDate", "UpdateDate"],
        "movement": ["move_dtd"],
        "ofndr_tst": ["tst_dt", "updt_dt"],
        "ref_LocationSubType": ["InsertDate", "UpdateDate"],
        "ref_LocationType": ["InsertDate", "UpdateDate"],
        "ref_NameSuffixType": ["InsertDate", "UpdateDate"],
        "ref_QuestionnaireTemplate": ["InsertDate", "PublishDate", "UpdateDate"],
        "scl_DORPenalty": [
            "InsertDate",
            "PenaltyEndDate",
            "PenaltyStartDate",
            "UpdateDate",
        ],
        "scl_DiscOffenseRpt": [
            "InfractionDate",
            "InsertDate",
            "IsolationInDate",
            "IsolationOutDate",
            "PreDetentionInDate",
            "PreDetentionOutDate",
            "UpdateDate",
        ],
        "scl_ProbationSupervision": ["EndDate", "StartDate"],
        "scl_SentenceDetail": ["SegmentEndDate", "SegmentStartDate"],
        "scl_Severity": ["InsertDate", "UpdateDate"],
        "scl_Term": [
            "ApprovalDate",
            "DpedApprovedDate",
            "DpedPendingDate",
            "DrcDate",
            "DrcOverrideApprovedDate",
            "DrcOverrideDate",
            "FtoOverrideEffectDate",
            "FtrdApprovedDate",
            "FtrdPendingDate",
            "GtrdApprovedDate",
            "GtrdPendingDate",
            "IndeterminateEndDate",
            "IndeterminateStartDate",
            "InitialParoleHearingDate",
            "InsertDate",
            "LastCalculateDate",
            "LastPendingDate",
            "LocStatusEffDate",
            "MaxprdApprovedDate",
            "MaxprdPendingDate",
            "MprdApprovedDate",
            "MprdPendingDate",
            "NextHearingDate",
            "ProbationCalculationDate",
            "ProbationExpirationDate",
            "ProbationStartDate",
            "ReleaseDate",
            "RiderExpiryDate",
            "RiderStartDate",
            "SegmentStartDate",
            "TentativeParoleDate",
            "TermSentenceDate",
            "TermStartDate",
            "UpdateDate",
        ],
        "sup_SupervisionAssignment": [
            "EndDate",
            "InsertDate",
            "StartDate",
            "UpdateDate",
        ],
        "sup_SupervisionAssignmentLevel": ["InsertDate", "UpdateDate"],
        "sup_SupervisionLevelChangeRequest": [
            "AssessmentDate",
            "DecisionDate",
            "InsertDate",
            "NextReviewDate",
            "ReviewDate",
            "UpdateDate",
        ],
    },
    StateCode.US_ME: {
        "CIS_1009_LSI_TYPE": ["Modified_On_Date"],
        "CIS_100_CLIENT": ["Birth_Date"],
        "CIS_1161_LSI_RATING": ["Created_On_Date", "Lsi_Effct_Date"],
        "CIS_116_LSI_HISTORY": [
            "Cis_1161_Comm_Lsi_Apprv_Rating_Date",
            "Cis_1161_Comm_Lsi_Effct_Date",
            "Cis_1161_Comm_Lsi_Or_Date",
            "Created_On_Date",
            "Lsi_Date",
            "Reassessment_Date",
        ],
        "CIS_2150_SEX_OFF_ASSESS_TYPE": ["Created_On_Date", "Modified_On_Date"],
        "CIS_215_SEX_OFFENDER_ASSESS": [
            "Assessment_Date",
            "Cis_1161_Lsi_Effct_Date",
            "Cis_1161_Lsi_Effct_Over_Date",
            "Created_On_Date",
            "Modified_On_Date",
        ],
        "CIS_314_TRANSFER": ["Created_On_Date", "Modified_On_Date", "Transfer_Date"],
        "CIS_900_EMPLOYEE": ["Created_On_Date", "Modified_On_Date"],
        "CIS_916_ASSIGN_BED": ["End_Date", "Start_Date"],
    },
    StateCode.US_MI: {
        "ADH_COALTERNATIVESCREENING": [
            "DateComputed",
            "DateCreated",
            "DateDeleted",
            "DateOfScreening",
            "DateUpdated",
        ],
        "ADH_COASSESSMENT": [
            "DateComputed",
            "DateComputedAsString",
            "DateCreated",
            "DateCreatedAsString",
            "DateDeleted",
            "DateOfScreening",
            "DateOfScreeningAsString",
            "DateSubmitted",
            "DateSubmittedAsString",
            "DateUpdated",
            "DateUpdatedAsString",
        ],
        "ADH_CORFSCALESET": ["DateCreated", "DateDeleted", "DateUpdated"],
        "ADH_EMPLOYEE": ["gun_permit_exp_date"],
        "ADH_MISCONDUCT_OFFENSE": [
            "effective_date",
            "expiration_date",
            "last_update_date",
            "last_update_node",
            "last_update_user",
        ],
        "ADH_OFFENDER_CHARGE": ["last_update_date"],
        "ADH_OFFENDER_DESIGNATION": ["last_update_node"],
        "ADH_SHPERSON": ["DateCreated", "DateDeleted", "DateOfBirth", "DateUpdated"],
        "ADH_SHUSER": [
            "DateCreated",
            "DateDeleted",
            "DateLastLogin",
            "DatePasswordLastSet",
            "DateUpdated",
        ],
        "COMS_Case_Managers": ["End_Date", "Entered_Date", "Start_Date"],
        "COMS_Employment": [
            "Employment_End_Date",
            "Employment_Start_Date",
            "Entered_Date",
        ],
        "COMS_Parole_Violation_Summary_Decisions": [
            "Case_Manager_Recommendation_Date",
            "Create_Date",
            "Entered_Date",
            "PV_Specialist_Decision_Date",
            "Submitted_Date",
        ],
        "COMS_Parole_Violation_Violation_Incidents": ["Entered_Date"],
        "COMS_Parole_Violations": [
            "Closed_Date",
            "Entered_Date",
            "Investigation_Start_Date",
        ],
        "COMS_Probation_Violation_Violation_Incidents": ["Entered_Date"],
        "COMS_Probation_Violations": [
            "Absconded_Date",
            "Apprehended_Date",
            "Apprehension_Closed_Date",
            "Closed_Date",
            "Due_Date",
            "Entered_Date",
            "Investigation_Start_Date",
            "Probation_Violation_Sentence_Date",
            "Violation_Closed_Date",
        ],
        "COMS_Security_Standards_Toxin": [
            "Case_Manager_Response_Date",
            "Conducted_Date",
            "Entered_Date",
            "Result_Date",
            "Retest_Result_Date",
            "Retest_Sent_Date",
        ],
        "COMS_Supervision_Levels": ["End_Date", "Entered_Date", "Start_Date"],
        "COMS_Supervision_Schedules": [
            "Create_Date",
            "End_Date",
            "Entered_Date",
            "Schedule_End_Date",
            "Schedule_Start_Date",
        ],
        "COMS_Violation_Incident_Charges": ["Entered_Date"],
        "COMS_Violation_Incidents": [
            "Absconded_Date",
            "Apprehended_Date",
            "Entered_Date",
            "Incident_Date",
        ],
        "COMS_dm_Staff_Supervisors": ["End_Date", "Entered_Date", "Start_Date"],
        "RECIDIVIZ_REFERENCE_mclxwalk": ["last_update_date"],
    },
    StateCode.US_MO: {
        "ORAS_MO_ASSESSMENTS_DB2": [
            "ASSESSMENT_DATE",
            "BACKDATED",
            "CREATED_AT",
            "DELETED_AT",
            "UPDATED_AT",
        ],
    },
    StateCode.US_ND: {
        "elite_offenders": ["ModifyDate"],
    },
    StateCode.US_NE: {
        "AggregateSentence": ["projectedReleaseDate", "tentativeReleaseDate"],
        "ORASClientRiskLevelAndNeeds": [
            "assessmentDate",
            "assessmentDueDate",
            "createdDate",
            "modifiedDate",
        ],
        "Offense": [
            "arrestDate",
            "beginDate",
            "createdDate",
            "modifiedDate",
            "offenseBeginDate",
            "offenseCommittedDate",
        ],
        "PIMSContactDashboard": [
            "createdDateTime",
            "dateOfContact",
            "houseParoleEndDate",
            "houseParoleStartDate",
            "lastUpdatedDateTime",
        ],
        "PIMSEmployment": [
            "creationDateTime",
            "effectiveDate",
            "endDate",
            "lastUpdatedDateTime",
            "startDate",
        ],
        "PIMSParoleOfficer": ["createdDate", "endDate", "modifiedDate", "startDate"],
        "PIMSParoleeInformation": [
            "createdDateTime",
            "dateOfParole",
            "dischargeDate",
            "modifiedDateTime",
        ],
        "PIMSParoleeInformation_Aud": [
            "createdDateTime",
            "custodialSanctionDaysAssessedToDate",
            "dateOfParole",
            "dischargeDate",
            "effectivetDateFromMVS",
            "modifiedDateTime",
            "pickedUpByProbationOn",
            "revocationDate",
            "updatedDateTime",
        ],
        "PIMSProgramTreatment": [
            "createdDate",
            "endDate",
            "modifiedDate",
            "referralDate",
            "startDate",
        ],
        "PIMSResidence": ["creationDateTime", "lastUpdatedDateTime", "startDate"],
        "PIMSReviewHearing": [
            "continuedDate",
            "createdDateTime",
            "custSanctEndDate",
            "custSanctStartDate",
            "finalizedDate",
            "hearingDate",
            "modifiedDate",
            "setHearingDate",
            "stabilizationRevocationDate",
            "waivedFeeFromDate",
            "waivedFeeToDate",
        ],
        "PIMSReviewHearingAllegation": ["createdDateTime"],
        "PIMSSanctions": [
            "EnteredDate",
            "PONotifiedDt",
            "ResponseDt",
            "ViolationDt",
            "createdDate",
            "modifiedDate",
            "sanctionDetailsCreatedDate",
            "sanctionDetailsModifiedDate",
        ],
        "PIMSSanctionsBehaviorEvent": ["AddDate", "DelDate", "OrgDate"],
        "PIMSSanctionsResponseEvent": ["AddDate", "DelDate", "OrgDate"],
        "ParoleEarnedDischargeDate": [
            "createdDate",
            "modifiedDate",
            "paroleEarnedDischargeDate",
        ],
    },
    StateCode.US_OR: {
        "RCDVZ_DOCDTA_TBSANC": ["DISCONTINUED_DATE", "LAST_UPDATED_WHEN"],
    },
    StateCode.US_OZ: {
        "eg_movements": ["Date"],
        "eg_person": ["DOB"],
        "hunger_games_periods": ["end_date", "start_date"],
        "lds_person": ["EndDate", "StartDate"],
        "lotr_fellowship": ["StartDate"],
        "lotr_periods": ["EndDate", "StartDate"],
        "nd_people": ["date"],
        "vfds_favorite_food": ["Date"],
        "vfds_person": ["StartDate"],
    },
    StateCode.US_PA: {
        "dbo_BoardAction": ["BdActDOPrintDate"],
        "dbo_ConditionCodeDescription": ["TimeStamp"],
        "dbo_Hist_Release": [
            "HReAcceptDate",
            "HReDOB",
            "HReDProcDate",
            "HReDelDate",
            "HReEprocDate",
            "HReGprProcDate",
            "HReMaxDate",
            "HReSprocDate",
            "HReStatDate",
            "HReTprocDate",
            "HReTransDate",
            "LastModifiedDatetime",
        ],
        "dbo_LSIHistory": ["AssessmentTime", "LastModifiedDateTime"],
        "dbo_Miscon": [
            "confinement_date",
            "date_reviewed",
            "hearing_after_date",
            "inmate_notice_date",
            "misconduct_date",
            "misconduct_time",
            "report_date",
        ],
        "dbo_Movrec": ["mov_move_date", "mov_sig_date"],
        "dbo_Offender": ["LastModifiedDate", "OffReceptionDate"],
        "dbo_PRS_FACT_PAROLEE_CNTC_SUMRY": [
            "CREATED_DATE",
            "DW_CREATED_DATE",
            "END_DATE",
            "START_DATE",
        ],
        "dbo_Perrec": [
            "commit_date",
            "ic_data_entry_dt",
            "ic_date",
            "ic_reclass_date",
            "re_recls_dte",
            "re_s_rating_date",
            "recls_date",
            "sig_date",
        ],
        "dbo_RelAgentHistory": ["LastModifiedDateTime"],
        "dbo_ReleaseInfo": ["RelMaxDate"],
        "dbo_Senrec": [
            "parole_status_dt",
            "sent_date",
            "sent_start_date",
            "sent_status_date",
            "sent_stop_date",
        ],
        "dbo_Treatment": ["LastModifiedDateTime"],
        "dbo_tblCCISStatus": ["LstMod_Dt"],
        "dbo_tblInmTestScore": ["LstMod_Dt", "Test_Dt"],
        "dbo_tblInmTestScoreHist": ["Hist_dt", "LstMod_Dt", "Test_Dt"],
        "dbo_tblSearchInmateInfo": [
            "IC_Dt",
            "Reclass_Dt",
            "RecmpMax_Dt",
            "delete_date",
            "event_date",
            "min_expir_date",
            "rcptpn_regular_date",
            "reception_date",
            "regular_date",
            "sent_date",
        ],
        "offense_codes": ["AddDt"],
    },
    StateCode.US_TN: {
        "Address": ["LastUpdateDate"],
        "AssignedStaff": [
            "AssignmentDueDate",
            "EndDate",
            "LastUpdateDate",
            "StartDate",
        ],
        "CellBedAssignment": ["AssignmentDateTime", "EndDate", "LastUpdateDate"],
        "DisciplinarySentence": ["LastUpdateDate", "SentenceDate"],
        "Diversion": [
            "DiversionGrantedDate",
            "ExpirationDate",
            "JudicialCloseDate",
            "LastModificationDate",
            "StatusDate",
        ],
        "ISCSentence": [
            "ActualReleaseDAte",
            "ExpirationDate",
            "OffenseDate",
            "ReleaseEligibilityDate",
            "SentenceImposedDate",
        ],
        "Incident": ["IncidentDateTime", "LastUpdateDate", "StatusDate"],
        "Infraction": ["DispositionDate", "LastUpdateDate"],
        "JOCharge": ["OffenseDate", "PleaDate", "SentenceImposedDate"],
        "JOMiscellaneous": [
            "JOEntryDate",
            "JOStatusDate",
            "LastAmendmentFiledDate",
            "LastAppealFinalizedDate",
            "LastJudgmentOrderChangeDate",
            "LastLetterCreatedDate",
            "LastPostConvictionReliefDate",
        ],
        "OffenderName": ["BirthDate", "LastUpdateDate"],
        "SentenceAction": ["ActionDate"],
        "SentenceMiscellaneous": [
            "AlternateSentenceImposeDate",
            "BOPDate",
            "CustodialParoleDate",
            "LastModificationDate",
        ],
        "Staff": [
            "BirthDate",
            "CertificationDate",
            "PersonalQuestionnaireDate",
            "SecurityStatusDate",
            "StatusDate",
            "UserClassDate",
        ],
    },
    StateCode.US_TX: {
        "Assessment": ["ASSESSMENT_DATE"],
        "Charges": ["OFF_SENT_BEG_DATE", "OFF_SENT_DATE"],
        "Phases": ["OFFC_REGION", "PLM_TYPE_ID", "PLS_STATUS_DATE"],
        "ProgramPhaseTransitions": ["PTMT_UPDATE_DATE"],
        "ProgramReferral": [
            "PREF_CREATION_DATE",
            "PREF_PROG_TYPE_ID",
            "PREF_UPDATE_DATE",
        ],
        "Staff": ["Creation_Date", "Last_Modified_Date", "Termination_Date"],
    },
    StateCode.US_UT: {
        "addr": ["end_dt", "geocode_dt", "updt_dt", "usps_vrfy_dt"],
        "applc_usr": ["updt_dt"],
        "applc_usr_email": ["updt_dt"],
        "assess_tst": ["updt_dt"],
        "case_stat": ["end_dt", "stat_beg_dt", "updt_dt"],
        "dcpln_case": ["apprv_dt", "filing_dt", "served_dt", "updt_dt"],
        "dcpln_hrng": ["final_hrng_dt", "sched_hrng_dt", "updt_dt"],
        "dcpln_hrng_rslt": ["end_dt", "strt_dt", "suspend_snctn_dt", "updt_dt"],
        "emplymt": ["updt_dt"],
        "emplyr": ["updt_dt"],
        "est_dt": [
            "override_dt",
            "parole_sprvsn_strt_dt",
            "probation_sprvsn_strt_dt",
            "sched_expire_dt",
            "sched_trmn_dt",
            "updt_dt",
        ],
        "est_dt_hist": [
            "hist_create_dt",
            "override_dt",
            "parole_sprvsn_strt_dt",
            "probation_sprvsn_strt_dt",
            "sched_expire_dt",
            "sched_trmn_dt",
            "updt_dt",
        ],
        "incdnt": ["incdnt_dt", "incdnt_end_dt", "incdnt_rpt_dt", "updt_dt"],
        "incdnt_cntct": ["apprv_dt", "arrest_dt", "updt_dt"],
        "ofndr": ["updt_dt"],
        "ofndr_addr_attr": ["end_dt", "strt_dt"],
        "ofndr_addr_hist": ["create_dt", "end_dt", "strt_dt", "updt_dt"],
        "ofndr_agnt": ["agnt_strt_dt", "create_dt", "end_dt", "updt_dt"],
        "ofndr_dob": ["updt_dt"],
        "ofndr_email": ["end_dt", "strt_dt", "updt_dt"],
        "ofndr_lgl_stat": ["stat_beg_dt", "stat_end_dt", "updt_dt"],
        "ofndr_loc_hist": ["assgn_dt", "end_dt", "updt_dt"],
        "ofndr_name": ["updt_dt"],
        "ofndr_phone": ["end_dt", "strt_dt", "updt_dt"],
        "ofndr_sprvsn": ["end_dt", "strt_dt", "updt_dt"],
        "ofnse_cd": ["full_trmn_eff_dt"],
        "rfrd_ofnse": [
            "adj_cmtmnt_dt",
            "arrest_dt",
            "bci_updt_dt",
            "convict_dt",
            "exp_dt",
            "juris_dt",
            "ofnse_dt",
            "orig_exp_dt",
            "updt_dt",
            "vrfy_dt",
        ],
        "rim_ofndr_violation_event": ["updt_dt"],
        "rim_sanction_history": [
            "agent_acknowledge_dt",
            "court_bopp_dcsn_dt",
            "court_request",
            "created_dt",
            "retracted_dt",
            "sprvsr_dcsn_dt",
            "updt_dt",
        ],
        "rim_violation_rove": ["created_dt", "updt_dt", "violation_dt"],
        "sbstnc_rslt": ["updt_dt"],
        "sbstnc_tst": [
            "cllct_dt",
            "rfsd_sbstnc_tst_dt",
            "rslt_chall_dt",
            "smpl_not_tst_dt",
            "smpl_rqst_dt",
            "tst_dt",
            "updt_dt",
        ],
    },
}

# Columns that have `field_type: datetime` but no defined `datetime_sql_parsers`
# defined, for file tags that are referenced in downstream BQ views but NOT ingest
# views. These need to be migrated carefully - after adding SQL parsers to these
# columns, we need to confirm that there are no changes to BQ views that reference these
# raw data files directly. NOTE: some of these columns might not actually be referenced
# at all. If a column is listed in this map, that means it's raw data file is referenced
# in downstream BQ views.
# TODO(#12174): Hydrate datetime parsers for all these columns and then delete this map
DATETIME_PARSER_EXEMPTIONS_FILES_REFERENCED_IN_DOWNSTREAM_VIEWS_ONLY: dict[
    StateCode, dict[str, list[str]]
] = {
    StateCode.US_AZ: {
        "AZ_DOC_DRUG_TRANSITION_PRG_AGRMNT": ["CREATE_DTM", "UPDT_DTM"],
        "AZ_DOC_DRUG_TRANSITION_PRG_EVAL": ["CREATE_DTM"],
        "AZ_DOC_DRUG_TRAN_PRG_REVIEW": ["CREATE_DTM"],
        "AZ_DOC_HWD_DETAINER": ["PICKED_UP_DTM"],
        "AZ_DOC_TRANSITION_PRG_AGRMNT": ["CREATE_DTM", "UPDT_DTM"],
        "AZ_DOC_TRANSITION_PRG_EVAL": ["CREATE_DTM"],
        "AZ_DOC_TRANSITION_PRG_REVIEW": ["CREATE_DTM"],
        "validation_incarceration_population_person_level": ["REPORT_DATE"],
        "validation_supervision_population_person_level": [
            "BEGAN_SUPERVSN",
            "REPORT_DATE",
            "SCHEDULED_END_DATE",
        ],
    },
    StateCode.US_CA: {
        "ParoleHousing": ["ADDREFFECTIVEDATE", "ADDRENDDATE"],
    },
    StateCode.US_CO: {
        "Base_Curr_Off_Pop": ["DOB"],
    },
    StateCode.US_IX: {
        "clsf_OffenderSecurityLevelAct": ["InsertDate", "UpdateDate"],
        "com_PSIReport": [
            "ApprovedDate",
            "AssignedDate",
            "CompletedDate",
            "DueDate",
            "FinalizedDate",
            "InsertDate",
            "OrderDate",
            "ReceivedDate",
            "SentenceDate",
            "UpdateDate",
        ],
        "crs_Course": ["EndDate", "InsertDate", "StartDate", "UpdateDate"],
        "crs_CourseName": ["InsertDate", "UpdateDate"],
        "crs_CourseSection": ["EndDate", "InsertDate", "StartDate", "UpdateDate"],
        "crs_CourseSectionName": ["InsertDate", "UpdateDate"],
        "crs_OfdCourseEnrollment": [
            "EndDate",
            "EnrollmentStatusDate",
            "InsertDate",
            "PendingEnrollmentDate",
            "RemovalPendingDate",
            "StartDate",
            "UpdateDate",
        ],
        "crs_OfdEnrollmentStatus": ["InsertDate", "UpdateDate"],
        "current_day_daily_summary": [
            "EPRD",
            "FTRD",
            "NextParHrgDt",
            "ParEligDt",
            "RlsDt",
            "SentEffDt",
            "TentParDt",
            "move_dtd",
            "popdate",
        ],
        "ind_Alert": ["InsertDate", "UpdateDate"],
        "ind_AlertType": ["InsertDate", "UpdateDate"],
        "ind_AlertVisibilityType": ["InsertDate", "UpdateDate"],
        "ind_Offender_Alert": ["InsertDate", "StartDate", "UpdateDate"],
        "ind_SecurityLevelOverride": ["InsertDate", "UpdateDate"],
        "ind_SecurityLevelReviewType": ["InsertDate", "UpdateDate"],
        "prb_PBCase_Employee": ["EndDate", "InsertDate", "StartDate", "UpdateDate"],
        "ref_NoteType": ["InsertDate", "UpdateDate"],
        "ref_PhoneType": ["InsertDate", "UpdateDate"],
        "scl_Escape": ["ArrestDate", "EscapeDate", "ReturnDocDate"],
    },
    StateCode.US_ME: {
        "CIS_102_ALERT_HISTORY": [
            "CREATED_ON_DATE",
            "EFFCT_DATE",
            "INEFFCT_DATE",
            "MODIFIED_ON_DATE",
        ],
        "CIS_112_CUSTODY_LEVEL": ["CUSTODY_DATE"],
        "CIS_130_INVESTIGATION": [
            "Complete_Date",
            "Complete_Date_Changed_Date",
            "Created_On_Date",
            "Due_Date",
            "Modified_On_Date",
            "Request_Date",
        ],
        "CIS_140_CLASSIFICATION_REVIEW": [
            "CREATED_ON_DATE",
            "MEETING_DATE",
            "MODIFIED_ON_DATE",
            "NEXT_REVIEW_DATE",
        ],
        "CIS_204_GEN_NOTE": ["Created_On_Date", "Modified_On_Date", "Note_Date"],
        "CIS_2082_JOB_CODE": ["CREATED_ON_DATE", "MODIFIED_ON_DATE"],
        "CIS_2084_JOB_NAME_CODE": ["CREATED_ON_DATE", "MODIFIED_ON_DATE"],
        "CIS_208_JOB_DEFN": [
            "CREATED_ON_DATE",
            "END_TIME",
            "MODIFIED_ON_DATE",
            "START_TIME",
        ],
        "CIS_210_JOB_ASSIGN": [
            "CREATED_ON_DATE",
            "END_DATE",
            "MODIFIED_ON_DATE",
            "START_DATE",
        ],
        "CIS_300_Personal_Property": [
            "CREATED_ON_DATE",
            "ENTRY_DATE",
            "MODIFIED_ON_DATE",
        ],
        "CIS_3030_PP_Item_Type": ["CREATED_ON_DATE", "MODIFIED_ON_DATE"],
        "CIS_425_MAIN_PROG": ["LSI_DATE", "TERM_END_DATE"],
        "CIS_426_PROG_STATUS": ["Effct_Datetime"],
        "Furloughs": ["EditedDt", "FurloughBeginDt", "FurloughEndDt"],
        "INCARCERATION_POPULATION_RELEASES": ["ADMISSION_DATE", "RELEASE_DATE"],
    },
    StateCode.US_MI: {
        "COMS_Case_Notes": ["Entered_Date", "Note_Date"],
        "COMS_Intervention_Referral_Program_and_Service_Type_Combinations": [
            "Entered_Date"
        ],
        "COMS_Intervention_Referrals": [
            "End_Date",
            "Entered_Date",
            "Referral_Date",
            "Start_Date",
        ],
        "COMS_Level_Of_Care": ["AdmissionDate"],
        "COMS_Mental_Health_Problems": ["StatusDate"],
        "COMS_Personal_Protection_Orders": [
            "Effective_Date",
            "Entered_Date",
            "Expiration_Date",
        ],
        "COMS_Security_Classification": [
            "Actual_Placement_Level_Assessment_Result_Entered_Date",
            "Confinement_Level_Assessment_Result_Entered_Date",
            "Management_Level_Assessment_Result_Entered_Date",
            "True_Security_Level_Assessment_Result_Entered_Date",
        ],
        "COMS_Supervision_Schedule_Activities": [
            "Completed_Date",
            "Entered_Date",
            "Scheduled_Date",
        ],
        "COMS_Supervision_Statuses": ["End_Date", "Entered_Date", "Start_Date"],
    },
    StateCode.US_ND: {
        "RECIDIVIZ_REFERENCE_community_opportunities": ["lastUpdatedDate"],
        "recidiviz_elite_Assessments": ["CREATE_DATE"],
    },
    StateCode.US_NE: {
        "PIMSCasePlan": [
            "assessmentDueDate",
            "casePlanDate",
            "createdDate",
            "lastORASAssessmentDate",
            "lastPaymentDate",
            "modifiedDate",
        ],
        "PIMSCasePlanSpecialCondition": ["createdDate"],
    },
    StateCode.US_OZ: {
        "validation_incarceration_population": ["date"],
    },
    StateCode.US_PA: {
        "dbo_LU_PBPP_Organization": ["DateModified"],
    },
    StateCode.US_TN: {
        "ContactNoteComment": ["ContactNoteDateTime"],
        "DrugTestDrugClass": ["LastUpdateDate", "TestDate"],
        "HealthExam": ["ExamDateTime", "LastUpdateDate"],
        "Hearing": [
            "AlternateReleaseDate",
            "BoardOfParoleDate",
            "CertificateReleaseDate",
            "FutureActionDate",
            "HearingDate",
            "ParoleDecisionDate",
            "RecommendedAlternateReleaseDate",
            "RecommendedBoardOfParoleDate",
            "RecommendedFutureActionDate",
        ],
        "IncompatiblePair": ["LastUpdateDate", "PostedDate", "SourceDate"],
        "Offender": ["ArchiveDate", "LastUpdateDate", "NotInCustodyDate", "PostedDate"],
        "OffenderAccounts": ["AccountStartDate", "AccountStatusDate", "LastUpdateDate"],
        "OffenderExemptions": ["EndDate", "LastUpdateDate", "StartDate", "VoidedDate"],
        "OffenderInvoices": ["InvoiceDate", "LastUpdateDate", "VoidedDate"],
        "OffenderPayments": ["LastUpdateDate", "PaymentDate", "VoidedDate"],
        "OffenderSentenceSummary": [
            "EarliestPossibleDate",
            "ExecutionDate",
            "ExpirationDate",
            "FullExpirationDate",
            "LastScheduledParoleHearingDate",
            "MandatoryParoleDate",
            "PERBCreditEligibilityDate",
            "PERBReleaseEligibilityDate",
            "ProbationaryParoleDate",
            "RegularParoleDate",
            "ReleaseEligibilityDate",
            "SafetyValveDate",
            "SentenceEffectiveDate",
        ],
        "PriorRecord": [
            "ArrestDate",
            "DispositionDate",
            "LastUpdateDate",
            "OffenseDate",
            "PostedDate",
        ],
        "TDPOP": [
            "Admit_Date",
            "DOB",
            "Date",
            "EXP_Date",
            "Future_Act_Date",
            "Hearing_Date",
            "Last_RNA_in_CC",
            "Last_RNA_in_Field",
            "Last_RNA_in_Prison_Jail",
            "PSI_Date",
            "RED_Date",
            "SID_Date",
        ],
        "VantagePointPathways": ["LastUpdateDate"],
        "VantagePointProgram": ["LastUpdateDate", "ProgramCreateDate"],
    },
    StateCode.US_UT: {
        "p_p_agrmnt": [
            "agrmnt_end_dt",
            "agrmnt_sign_dt",
            "orig_eff_strt_dt",
            "orig_entry_dt",
            "updt_dt",
        ],
        "p_p_spcl_cond": ["end_dt", "orig_entry_dt", "strt_dt", "updt_dt"],
        "rim_ofndr_accomplishment": ["accomplishment_dt", "created_dt", "updt_dt"],
        "wf_rpt": [
            "create_dt",
            "custody_dt",
            "due_dt",
            "last_pmt_dt",
            "lock_rpt_dt",
            "rpt_dt",
            "sent_to_crt_dt",
            "sent_to_supr_dt",
            "updt_dt",
        ],
    },
}


# Columns that have `field_type: datetime` but no defined `datetime_sql_parsers`
# defined, for file tags that have no downstream references. These do NOT need to be
# migrated carefully. If the recidiviz.tools.ingest.development.hydrate_datetime_sql_parsers
# script suggests a parser for these files, we can accept it without any further
# testing. NOTE: some of these columns might not actually be referenced at all. If a
# column is listed in this map, that means it's raw data file is referenced in ingest
# views.
# TODO(#12174): Hydrate datetime parsers for all these columns and then delete this map
DATETIME_PARSER_EXEMPTIONS_NO_DOWNSTREAM_REFERENCES: dict[
    StateCode, dict[str, list[str]]
] = {
    StateCode.US_AZ: {
        "AZ_DOC_DRUG_TRANSITION_PRG_NOTES": ["CREATE_DTM"],
        "AZ_DOC_DRUG_TRANSITION_PRG_OVERRIDE": [
            "COIII_CREATE_DTM",
            "COIII_UPDT_DTM",
            "TC_UPDT_DTM",
        ],
        "AZ_DOC_DRUG_TRAN_PRG_INELIGOD": ["TC_CREATE_DTM"],
        "AZ_DOC_SC_ARS_ENHANCE_CD": ["CREATE_DTM", "UPDT_DTM"],
        "AZ_DOC_TRANSITION_PRG_INELIGOD": ["TC_CREATE_DTM"],
        "AZ_DOC_TRANSITION_PRG_NOTES": ["CREATE_DTM"],
        "AZ_DOC_TRANSITION_PRG_OVERRIDE": [
            "COIII_CREATE_DTM",
            "COIII_UPDT_DTM",
            "TC_UPDT_DTM",
        ],
        "PERSON_MERGE": ["EMAIL_SENT_DATE", "MERGE_DATE"],
    },
    StateCode.US_CA: {
        "HoldInCustody": ["HoldPlaceDate"],
        "IncarcerationInCustody": ["ParoleEndDate", "in_date", "out_date"],
        "IncarcerationIncident": [
            "DISCIPLINARYVIOLATIONDATE",
            "INCIDENTBEGINDATE",
            "ORIGINALVIOLATIONDATE",
        ],
        "IncarcerationSentence": ["ScheduledReleaseDate"],
        "PersonInCustody": ["Birthday"],
        "ProgramAssignment": [
            "PROGRAMAPPLICATIONDATE",
            "PROGRAMASSIGNEDDATE",
            "PgmApplicationStatusDate",
            "WorkAssignStatusDate",
        ],
        "RVRSanctions": ["ORIGINALVIOLATIONDATE"],
        "SupervisionContact": ["CONTACTDATE"],
    },
    StateCode.US_CO: {
        "eomis_bedassignment": ["BEDASSIGNMENTDATE"],
    },
    StateCode.US_IA: {
        "Base_Pop_T_DeID": ["SupervisionStatusEndDt", "SupervisionStatusStartDt"],
        "Base_Population_Demographics_T_DeID": ["DeceasedDt"],
        "Case_Managers_T_DeID": ["CaseManagerEndDt", "CaseManagerStartDt"],
        "Current_Iowa_Correctional_System_CBC_Field_Population": [
            "Report_Date",
            "Supervision_Start_Date",
        ],
        "Current_Iowa_Correctional_System_CBC_Residential_Population": [
            "Report_Date",
            "Residential_Start_Date",
        ],
        "Current_Iowa_Correctional_System_Prison_Population": [
            "Prison_Start_Date",
            "Report_Date",
        ],
        "DRAOR_CBC_Revised_T_DeID": ["AssessedDt", "OverrideApprovalDt"],
        "DRAOR_CBC_T_DeID": ["AssessedDt", "OverrideApprovalDt"],
        "IA_DOC_ConsolidatedSupStatuses": [
            "EndDt",
            "MaxOWIContinuumStartDtWithinConsSupStatus",
            "MaxPrisonEndDtWithinConsSupStatus",
            "MinOffenseDt",
            "StartDt",
        ],
        "IA_DOC_DRAOR_CBCRevised": ["AssessedDt", "OverrideApprovalDt", "SubmittedDt"],
        "IA_DOC_DRAOR_InstitutionRevised": ["AssessedDt", "SubmittedDt"],
        "IA_DOC_Employment": [
            "EmploymentEndDt",
            "EmploymentStartDt",
            "FirstPaycheckDt",
        ],
        "IA_DOC_FieldRuleViolationBCs": ["EnteredDt"],
        "IA_DOC_Housing": ["EnteredDt", "HousingEndDt", "HousingStartDt"],
        "IA_DOC_Housing_PrivilegeLevels": [
            "EnteredDt",
            "PrivilegeLevelEndDt",
            "PrivilegeLevelReleaseDt",
            "PrivilegeLevelReviewDt",
            "PrivilegeLevelStartDt",
        ],
        "IA_DOC_ISORA": ["AssessedDt", "EnteredDt", "SubmittedDt"],
        "IA_DOC_IVVI": [
            "AssessedDt",
            "OverrideApprovalDt",
            "Q4Q5IvviTenYrPriorStartValue",
            "Q4toQ6IvviPriorEndValue",
            "Q6IvviFiveYrPriorStartValue",
            "Q7IvviFiveYrPriorStartValue",
            "Q7IvviPriorEndValue",
            "StaffAuditDt",
            "SubmittedDt",
        ],
        "IA_DOC_InstDiscHearings": [
            "ContinuedDt",
            "DecisionDt",
            "EnteredDt",
            "HearingDt",
            "MostRecentReportSubmittedDt",
        ],
        "IA_DOC_InstDiscNotices": [
            "EnteredDt",
            "MostRecentReportSubmittedDt",
            "NoticeDt",
            "ServedDt",
        ],
        "IA_DOC_InstHearingNotices": ["EnteredDt"],
        "IA_DOC_MAINT_InterventionLocations": ["EnteredDt"],
        "IA_DOC_MAINT_InterventionProgramLocations": ["EnteredDt"],
        "IA_DOC_MAINT_InterventionPrograms": ["EnteredDt"],
        "IA_DOC_MAINT_Interventions": ["EnteredDt"],
        "IA_DOC_MilitaryInfo": ["EndDt", "EnteredDt", "StartDt"],
        "IA_DOC_Names": ["EnteredDt"],
        "IA_DOC_PSI": [
            "AnticipatedSentenceDt",
            "AssignedDt",
            "DueDt",
            "EnteredDt",
            "ORDER_DTTM",
            "OrderedDt",
            "SubmittedDt",
        ],
        "IA_DOC_PSIChargeRecommendations": ["EnteredDt"],
        "IA_DOC_ResiFormalDisc": [
            "EnteredDt",
            "InvestigationDt",
            "MostRecentReportSubmittedDt",
            "ReportDt",
            "ServingDt",
            "WaiverDt",
        ],
        "IA_DOC_ResiInformalDisc": ["EnteredDt", "ReportDt", "ServingDt"],
        "IA_DOC_SOTIPS": [
            "AssessedDt",
            "EnteredDt",
            "SexOffenseFreeStartDt",
            "SubmittedDt",
            "SupervisionLevelOverrideApprovalDt",
        ],
        "IA_DOC_STATIC99R": ["AssessedDt", "EnteredDt", "SubmittedDt"],
        "IA_DOC_SecStdToxins": ["ConductedDt", "ResultDt", "RetestResultDt"],
        "IA_DOC_SecondaryCaseManagers": [
            "EnteredDt",
            "SecondaryManagementEndDt",
            "SecondaryManagementStartDt",
        ],
        "Intervention_Program_T_DeID": ["EligibilityDt", "OrientationDt"],
        "Interventions_T_DeID": [
            "EligibilityDt",
            "InterventionEndDt",
            "InterventionStartDt",
        ],
        "Iowa_Parole_Revocations": ["Record_Date"],
        "Iowa_Prison_Admissions": ["Admission_Date", "Date_of_Release"],
        "Iowa_Probation_Admissions": ["Admission_Date"],
        "Iowa_Probation_Revocations": ["Revocation_Date"],
        "Iowa_Risk_Revised_T_DeID": ["AssessedDt", "OverrideApprovalDt"],
        "Level_of_Supervision_T_DeID": ["LOSEndDt", "LOSStartDt"],
        "Modifier_T_DeID": ["SupervisionModifierEndDt", "SupervisionModifierStartDt"],
        "Offenders_Released_from_Iowa_Prisons": ["Admission_Date", "Release_Date"],
        "Prison_Charges_T_DeID": [
            "ArrestDt",
            "EndDt",
            "OffenseDt",
            "SDD",
            "StartDt",
            "TDD",
            "TDDDisplay",
        ],
        "Prison_Status_T_DeID": ["SupervisionStatusEndDt", "SupervisionStatusStartDt"],
        "ROV_Ticket18447_Parole_SS_DeID": ["ReportDt", "ReviewDt"],
        "ROV_Ticket18447_Probation_DeID": ["ReportDt"],
        "ROV_Ticket18447_WR_OWI_DeID": ["ReportDt"],
        "Region_and_Work_Unit_T_DeID": ["WorkUnitEndDt", "WorkUnitStartDt"],
        "Specialty_T_DeID": ["SpecialtyEndDt", "SpecialtyStartDt"],
        "Sup_Status_Charge_Sentence_T_DeID": ["SentenceDt", "SentenceEndDt"],
        "Sup_Status_Charges_T_DeID": [
            "ArrestDt",
            "EndDt",
            "OffenseDt",
            "SDD",
            "StartDt",
            "TDD",
            "TDDDisplay",
        ],
        "Supervision_Level_T_DeID": [
            "SupervisionLevelEndDt",
            "SupervisionLevelStartDt",
        ],
    },
    StateCode.US_IX: {
        "arm_MatrixIncentiveTrigger": ["InsertDate", "UpdateDate"],
        "arm_MatrixInfractionTrigger": ["InsertDate", "UpdateDate"],
        "arm_ResponseMatrix": ["InsertDate", "UpdateDate"],
        "asm_AssessmentStatus": ["InsertDate", "UpdateDate"],
        "asm_AssessmentTypeResult": ["InsertDate", "UpdateDate"],
        "clsf_ClsfAction": ["InsertDate", "UpdateDate"],
        "clsf_ClsfActionHistory": ["ApprovedDate", "InsertDate", "UpdateDate"],
        "com_CommunityServiceRecord": [
            "EndDate",
            "InsertDate",
            "StartDate",
            "UpdateDate",
        ],
        "com_MentalHealth": ["ApprovalDate", "EntryDate", "InsertDate", "UpdateDate"],
        "com_MentalHealthTreatmentType": ["InsertDate", "UpdateDate"],
        "com_SubstanceAbuseInfo": [
            "ASIDate",
            "AlcoholDateofLastUse",
            "EntryDate",
            "InsertDate",
            "SSIDate",
            "UpdateDate",
        ],
        "com_SubstanceAbuseTreatment": ["InsertDate", "UpdateDate"],
        "crs_CourseLesson_Movement": ["InsertDate", "UpdateDate"],
        "crs_OfdCourseEnrollmentHistory": [
            "EndDate",
            "EnrollmentStatusDate",
            "PendingEnrollmentDate",
            "RemovalPendingDate",
            "StartDate",
            "UpdateDate",
        ],
        "dce_OffenderDCEInfo": [
            "FastTrackEligibleUntilDate",
            "GEDEligibleUntilDate",
            "InsertDate",
            "OPTEligibleUntilDate",
            "UpdateDate",
            "WaiverDate",
        ],
        "dsc_DAHearing": [
            "InsertDate",
            "OffenderPresenceWitnessDatetime",
            "OffenderSignatureDate",
            "OffenderStaffWitnessDatetime",
            "ResponseFormDueDate",
            "UpdateDate",
        ],
        "gsm_Event_Participant": ["EndDate", "InsertDate", "StartDate", "UpdateDate"],
        "gsm_Movement": ["InsertDate", "UpdateDate"],
        "gsm_ParticipantOffender": ["InsertDate", "UpdateDate"],
        "hsn_CounselorAssignmentClass": ["InsertDate", "UpdateDate"],
        "ind_HomelessType": ["InsertDate", "UpdateDate"],
        "ind_LegalStatusChangeReason": ["InsertDate", "UpdateDate"],
        "ind_OffenderLocationHistory": ["InsertDate", "UpdateDate"],
        "ind_SecurityLevelMandatoryOverride": ["InsertDate", "UpdateDate"],
        "prb_PBCaseType": ["InsertDate", "UpdateDate"],
        "ref_AddressType": ["InsertDate", "UpdateDate"],
        "ref_EmployeeStatus": ["InsertDate", "UpdateDate"],
        "ref_ScoreSheetType": ["InsertDate", "UpdateDate"],
        "scl_Credit": ["InsertDate", "UpdateDate"],
        "scl_CreditBase": ["InsertDate", "UpdateDate"],
        "scl_CreditDetail": ["InsertDate", "SubmittedDate", "UpdateDate"],
        "scl_CreditDetailType": ["InsertDate", "UpdateDate"],
        "scl_DOROffenseTypePenalty": [
            "EffectiveDate",
            "EndDate",
            "InsertDate",
            "UpdateDate",
        ],
        "scl_DorOffenseCategoryType": ["InsertDate", "UpdateDate"],
        "scl_Parole": ["ReleaseDate"],
        "scl_Supervision": ["ImposedDate", "StartDate"],
        "scl_Warrant": [
            "DocumentRetrievedDate",
            "InsertDate",
            "LastArchivedDate",
            "POExecutionAwareDate",
            "UpdateDate",
            "WarrantApprovedDate",
            "WarrantExecutedDate",
            "WarrantInactiveDate",
            "WarrantIssuedDate",
        ],
        "scl_WarrantReason": ["InsertDate", "UpdateDate"],
        "scl_WarrantType": ["InsertDate", "UpdateDate"],
        "sup_SupervisionLevelChangeRequestStatus": ["InsertDate", "UpdateDate"],
    },
    StateCode.US_ME: {
        "CIS_128_EMPLOYMENT_HISTORY": ["END_DATE", "START_DATE"],
        "CIS_1401_CLASSIFICATION_CD": ["CREATED_ON_DATE", "MODIFIED_ON_DATE"],
        "CIS_160_DRUG_SCREENING": ["POSTED_DATE", "TEST_DATE"],
        "CIS_2083_JOB_SYS": ["CREATED_ON_DATE", "MODIFIED_ON_DATE"],
        "CIS_324_AWOL": [
            "AWOL_DATE",
            "AWOL_TIME",
            "INEFFCT_DATE",
            "RETURN_DATE",
            "RETURN_TIME",
        ],
        "CIS_430_ASSESSMENT": ["Dead_Line_Date", "Interview_Date", "Start_Date"],
        "CIS_5003_TRANSACTION_TYPE": ["CREATED_ON_DATE", "MODIFIED_ON_DATE"],
        "CIS_503_TRUST_TRANSACTION": [
            "CREATED_ON_DATE",
            "HOLD_DATE",
            "MODIFIED_ON_DATE",
            "TRANSACTION_DATETIME",
        ],
    },
    StateCode.US_MI: {
        "COMS_Assaultive_Risk_Assessments": [
            "Assessed_Date",
            "Entered_Date",
            "Next_Review_Date",
        ],
        "COMS_Conditions": ["End_Date", "Entered_Date", "Start_Date"],
        "COMS_Program_Recommendations": [
            "Create_Date",
            "End_Date",
            "Entered_Date",
            "Program_Status_Date",
            "Referral_Date",
            "Start_Date",
        ],
        "COMS_dm_Staff_Specialized_Types": ["Entered_Date"],
    },
    StateCode.US_NC: {
        "APPT7AA1": ["CDCLBRTH", "DTOFUPDT"],
        "APPT9BJ1": ["DTOFUPDT", "IMPREQDT", "IMPSTRDT"],
        "INMT4AA1": [
            "CICLBRTH",
            "CICONVDT",
            "CIGTDATE",
            "CILAMVDT",
            "CILPENDT",
            "CIRADMDT",
            "CIXCALDT",
            "GIRMAX",
            "GIRPED",
            "GIRPRD",
            "GIRTRD",
            "LSTINFRDT",
            "NXTCUSREV",
            "NXTPCREV",
            "NXTSECREV",
        ],
        "INMT4BB1": ["CIRELDAT", "GIEFFDT", "GISPRD", "PARBEGDT", "PARDISCHDT"],
        "INMT4CA1": ["CICREVDT", "CIPARREL", "DTOFUPDT"],
        "INMT9CF1": ["ACTVSPDT", "CIDREFDT", "DTOFUPDT"],
        "OFNT1BA1": ["DTOFUPDT"],
        "OFNT3AA1": ["CMCLBRTH", "DTOFUPDT"],
        "OFNT3BB1": [
            "CIOLDPED",
            "CMADMDTE",
            "CMINTDTE",
            "CMPPCMDT",
            "CMSTADTE",
            "DTOFUPDT",
            "GMSEFFDT",
        ],
        "OFNT3CE1": [
            "CMCMSTDT",
            "CMIMPSDT",
            "CMOFFDT2",
            "CMOFFDTE",
            "CMPPSTDT",
            "CMSENTDT",
            "DTINUPDT",
            "DTOFUPDT",
            "DTOFUPDT2",
        ],
        "OFNT3DE1": ["DTOFUPDT"],
        "OFNT9BE1": ["DTOFUPDT"],
    },
    StateCode.US_ND: {
        "docstars_lsi_plan_of_action": ["END_DATE", "START_DATE"],
        "recidiviz_docstars_DIVERSION_PLAN": ["INACTIVEDATE"],
        "recidiviz_docstars_LSI_SUPERPLAN": ["INACTIVEDATE", "RECDATE"],
    },
    StateCode.US_NE: {
        "CUSTODY_HIST": ["CREATION_TS", "EFFECTIVE_DT", "LAST_ACTIVITY_TS"],
        "LKViolation": ["createdDate", "endDate", "modifiedDate", "startDate"],
        "MRRSAppealBoard": [
            "createdDate",
            "finalDecisionDate",
            "hearingDate",
            "modifiedDate",
            "submissionDate",
        ],
        "MRRSAppealCharge": ["createdDate", "modifiedDate"],
        "MRRSAttorney": ["appealReceivedByLegalDate", "createdDate", "modifiedDate"],
        "MRRSBoardMember": ["createdDate", "modifiedDate"],
        "MRRS_MisconductDisciplinaryCommittee": [
            "dateAndTimeLog",
            "dateOfSupportMisconductReport",
            "lastUpdated",
        ],
        "MRRS_Warden": [
            "createdDate",
            "firstSentCompletedDate",
            "lastSentBackDate",
            "lastUpdated",
        ],
        "MRRS_charges": ["beginDate", "createdDate", "endDate", "lastUpdated"],
        "MRRS_investigationOfficer": [
            "dateOfDeliveredCopyToInmate",
            "dateOfDiscovery",
            "dateOfHearingBeforeIO",
            "investigationContinuedDate",
            "lastUpdated",
            "recommendedDateOfDisciplinaryCommitteeHearing",
        ],
        "MRRS_misconductReport": [
            "dateFiled",
            "dateOfDiscovery",
            "dateReportWasWritten",
            "modifiedDate",
        ],
        "PBABoardMember": ["createdDate", "endDate", "modifiedDate", "startDate"],
        "PBABoardMemberAttendance": ["createdDate", "modifiedDate"],
        "PBABoardMemberVote": ["createdDate", "modifiedDate"],
        "PBAHearingAttendance": ["createdDate", "hearingDate", "modifiedDate"],
        "PBAHearingMemberAttendance": ["createdDate", "modifiedDate"],
        "PBAHearingReviewSummary": ["createdDate", "modifiedDate"],
        "PBAOffenderBoardReview": [
            "createdDate",
            "modifiedDate",
            "originalReviewDate",
            "pdfGeneratedDate",
            "reviewDate",
        ],
        "PIMSAPIWSpecialCondition": [
            "beginDate",
            "createdDate",
            "endDate",
            "modifiedDate",
            "noContactEndDate",
            "suspendedDate",
        ],
        "PIMSAdultPlacementInvestigationWorksheet": [
            "assignedDate",
            "createdDate",
            "dueDate",
            "finalDispositionDate",
            "modifiedDate",
            "nextHearingDate",
        ],
        "PIMSBMSSanctionDetails": ["createdDate", "modifiedDate"],
        "PIMSCasePlanGoal": ["createdDate", "dateCompleted", "modifiedDate"],
        "PIMSCasePlanGoalObjective": [
            "createdDate",
            "dateCompleted",
            "modifiedDate",
            "startDate",
            "targetDate",
        ],
        "PIMSCustodialSanction": [
            "actualJailAdmitDate",
            "actualJailDischargeDate",
            "createdDate",
            "hearingDate",
            "modifiedDate",
            "projectedReleaseDate",
            "recommendedStartDate",
            "revisedRecommendedStartDate",
        ],
        "PIMSCustodialSanctionViolation": ["modifiedDate", "violationDate"],
        "PIMSCustodialSanctionViolationSpecialCondition": [
            "createdDate",
            "modifiedDate",
        ],
        "PIMSDisciplinaryActionLaw": ["createdDateTime", "lastUpdatedDateTime"],
        "PIMSDisciplinaryActionLocation": [
            "createdDatetime",
            "dateMoved",
            "lastUpdatedDatetime",
        ],
        "PIMSDisciplinaryActionReffers": ["createdDateTime", "lastUpdateDateTime"],
        "PIMSDisciplinaryActions": [
            "caseDismissedDate",
            "createdOn",
            "feeWaiverStartDate",
            "holdDate",
            "lastUpdatedOn",
            "revocationDT",
            "waiveFromDT",
            "waiveToDT",
        ],
        "PIMSDisciplinaryCharges": ["createdDateTime", "lastUpdatedDateTime"],
        "PIMSDisciplinaryHearing": [
            "continueDate",
            "createdDateTime",
            "hearingDate",
            "lastUpdatedDateTime",
        ],
        "PIMSDisciplinaryTechnical": ["createdDateTime", "lastUpdatedDateTime"],
        "PIMSEducation": [
            "creationDateTime",
            "endDate",
            "lastUpdatedDateTime",
            "startDate",
        ],
        "PIMSElectronicMonitoring": [
            "creationDateTime",
            "dateOff",
            "dateOn",
            "lastUpdatedDateTime",
        ],
        "PIMSLSOAssessment": [
            "assessmentDate",
            "createdDateTime",
            "lastUpdatedDateTime",
        ],
        "PIMSResidenceContact": ["creationDateTime", "lastUpdatedDateTime"],
        "PIMSReviewHearingRoster": [
            "createdDateTime",
            "finalizedDate",
            "hearingDate",
            "modifiedDateTime",
        ],
        "PIMSReviewHearingVote": ["createdDate", "modifiedDate"],
        "PIMSSpecialConditionContact": [
            "creationDateTime",
            "endDate",
            "lastUpdatedDateTime",
        ],
        "PIMSreviewHearingSpecCondContact": [
            "createdDate",
            "endDate",
            "lastUpdatedDateTime",
        ],
        "PIMSreviewHearingSpecialCondition": ["createdDateTime", "lastUpdatedDateTime"],
        "SecurityThreatGroup": [
            "affiliationDate",
            "createdDate",
            "lastActivityDate",
            "lastUpdated",
        ],
    },
    StateCode.US_OZ: {
        "bad_data": ["date"],
        "bad_data_person": ["StartDate"],
        "gd_dogs": ["acquired"],
        "tfds_person": ["StartDate"],
    },
    StateCode.US_PA: {
        "AssessmentResults_StrongR": ["DateCompleted"],
        "MEDIASSTID": [
            "Created_Date",
            "Effective_End_Date",
            "Effective_Start_Date",
            "Modified_Date",
        ],
        "Person_Inmate_Map": [
            "Created_Date",
            "Effective_End_Date",
            "Effective_Start_Date",
            "Modified_Date",
        ],
        "Person_vw_Projected_Release_Date": ["Projected_Release_Date"],
        "RECIDIVIZ_REFERENCE_agent_districts": ["date_received"],
        "SAPPHIRE_COMPLETED_DC108AS": ["DATE_FORM_SUBMITTED"],
        "dbo_Controlling_Sentence": [
            "Expiration_Date",
            "RRRI_Date",
            "Recomputed_Max_Date",
        ],
        "dbo_LSIR": ["InterviewDate"],
        "dbo_LU_ReleaseEntryCodesAddCase": ["LastModifiedDatetime"],
        "dbo_Offender_MHT": ["sig_date"],
        "dbo_SentenceGroup": [
            "SenAddDate",
            "SenLastModDate",
            "SentEffectiveDate",
            "senRRRIDate",
            "senTrueMinDate",
        ],
        "dbo_vwCCISAllInmate": ["Bed_Dt", "Cur_Status_Dt", "LstMod_Dt"],
    },
    StateCode.US_TN: {
        "Class": ["ClassStatusDate", "LastUpdateDate", "RateDate"],
        "ClassRoster": ["ConfirmationDate", "EndDate", "LastUpdateDate", "StartDate"],
        "ClassSection": [
            "ApprovalDate",
            "DenialDate",
            "EndDate",
            "LastUpdateDate",
            "RequestDate",
            "StartDate",
        ],
        "DisciplinaryAppeal": ["AppealDate", "DispositionDate", "LastUpdateDate"],
        "DrugTest": ["LastUpdateDate", "PostedDate", "TestDate"],
        "DrugTestAdulterant": ["LastUpdateDate", "TestDate"],
        "FeePriceSheet": ["EndDate", "StartDate"],
        "IncidentPersonInvolved": ["LastUpdateDate"],
        "InterestedPartyComment": ["VictimLetterCreateDate"],
        "Job": ["JobStatusDate", "LastUpdateDate"],
        "JobPositionHistory": [
            "ConfirmationDate",
            "EffectiveFromDate",
            "EffectiveToDate",
            "EndDate",
            "HighestCustodyDate",
            "LastAuditDate",
            "LastUpdateDate",
            "StartDate",
            "TerminationDate",
        ],
        "JobPositionRoster": [
            "ConfirmationDate",
            "EffectiveFromDate",
            "EffectiveToDate",
            "EndDate",
            "LastAuditDate",
            "LastUpdateDate",
            "StartDate",
        ],
        "OffenderContact": ["EffectiveFromDate", "EndDate", "StartDate"],
        "OffenderEmployment": [
            "EndDate",
            "LastUpdateDate",
            "SortEndDate",
            "SortStartDate",
            "StartDate",
            "VerifiedEndDate",
            "VerifiedStartDate",
        ],
        "OffenderFees": ["EndDate", "StartDate"],
        "OffenderFinding": ["FindingDate", "PostedDate"],
        "OffenderOrientation": [
            "OrientationCompletedDate",
            "OrientationDueDate",
            "SignedDate",
        ],
        "OtherID": ["BirthDate", "LastUpdateDate", "OffenderDeletionDate"],
        "PardonCommutation": ["LastModifiedDate", "PardonCommutationDate"],
        "PardonCommutationRecommendation": ["HearingDate", "PostedDate"],
        "PhotoIDRequest": [
            "InterimDocumentFiledDate",
            "OfficialDocumentFiledDate",
            "ReceivedDate",
            "RequestBirthDate",
            "RequestDate",
            "ResponseEligibleDate",
            "SubmittedApplicationDate",
            "TDOcHSLicenseExpirationDate",
        ],
        "PretrialJailCredits": ["EndDate", "StartDate"],
        "Referral": [
            "CompletedDate",
            "CourtDate",
            "DueDate",
            "OrderDate",
            "PostedDate",
        ],
        "ReferralDebtandAsset": ["OrderDate", "PostedDate"],
        "ReferralDocket": ["OrderDate", "PostedDate"],
        "ReferralPriorRecord": ["EventDate", "OrderDate"],
        "ReleasePlan": ["ParolePlanDate", "StartDate"],
        "SAIUFinding": ["PostedDate"],
        "SentenceCreditLaw": ["CreditEligibleDate", "LastModifiedDate", "WaiverDate"],
        "SentenceExtension": ["ExtensionDate", "LastModifiedDate"],
        "SentenceTimeAdjustment": ["EndDate", "StartDate"],
        "StaffAction": ["LastUpdateDate", "StaffActionDate"],
        "SupervisionStandard": ["PostedDate", "StandardEndDate", "StandardStartDate"],
        "SupervisionStandardType": ["StandardStartDate"],
        "VantagePointCCR": ["DTE_CCR_RVW", "DTE_LAST_UPDT"],
        "VantagePointClasses": ["LastUpdateDate", "ProgramCreateDate"],
        "ViolationSupervisionSanctionLookUp": ["EndDate", "StartDate"],
        "Warrant": [
            "DelinquentDate",
            "InitalExtraditionDate",
            "IssueDate",
            "WarrantDisposeDate",
            "WarrantPendingDate",
            "WarrantServedDate",
            "WarrantStatusDate",
        ],
        "WarrantSentence": ["IssueDate"],
    },
    StateCode.US_UT: {
        "addr_typ_cd": ["pick_order"],
        "agg_prsn_sent": [
            "adj_cmtmnt_dt",
            "agg_exp_dt",
            "agg_sent_comp_dt",
            "full_term_rlse_dt",
            "prle_elig_dt",
            "sent_stsfy_dt",
        ],
        "agnt_rspns_actn": ["agent_acknowledge_dt"],
        "cap": ["mstr_updt_dt"],
        "case_mgr": ["lst_eff_dt"],
        "dio_bed": ["end_dt"],
        "dio_ofndr_bed": ["end_dt"],
        "dio_prog_rfrl": ["schd_dt", "scrn_dt"],
        "grvnc": ["grvnc_close_dt"],
        "grvnc_actn_lvl": [
            "actn_due_dt",
            "grvnc_fwd_dt",
            "grvnc_rtrn_dt",
            "rspns_to_inmate_dt",
        ],
        "grvnc_appeal_actn": [
            "grvnc_fwd_dt",
            "grvnc_rtrn_dt",
            "rspns_to_inmate_dt",
        ],
        "grvnc_frml_actn": [
            "actn_due_dt",
            "grvnc_fwd_dt",
            "grvnc_rtrn_dt",
            "rspns_to_inmate_dt",
        ],
        "grvnc_infrml_actn": [
            "grvnc_fwd_dt",
            "grvnc_rtrn_dt",
            "rspns_to_inmate_dt",
        ],
        "grvnc_prblm": ["sent_to_ofndr_dt"],
        "lgl_stat_chg_rule": ["vld_end_dt"],
        "ofndr_addr_arch": [
            "addr_end_dt",
            "cnvrt_dt",
            "vrfy_dt",
        ],
        "ofndr_addr_attr_wrk": ["end_dt"],
        "ofndr_addr_wrk": ["geocode_dt"],
        "ofndr_earned_compliance_log": ["earned_end_dt"],
        "ofndr_header": [
            "acuity_strt_dt_tm",
            "curr_stat_beg_dt_tm",
            "eval_dt",
            "expire_life_sent_dcsn_dt",
            "ice_dtnr_rcvd_dt",
            "last_app_sprvsn_beg_dt",
            "last_prsn_admit_dt",
            "last_rfrl_dt",
            "loc_assgn_dt_tm",
            "next_hearing_dt",
            "pet_dt",
            "risk_eval_dt",
            "rlse_dt",
            "sched_expire_dt",
            "sched_trmn_dt",
            "sex_ofndr_beg_dt",
            "stg_apprvd_dt",
        ],
        "ofndr_spcl_sprvsn": ["end_dt"],
        "p_p_agnt_rspns": ["agnt_rspns_deny_dt"],
        "p_p_agrmnt_cond": ["end_dt", "orig_entry_dt"],
        "p_p_allgt": ["plea_dt"],
        "prgrm_elgblty": ["follow_up_dt", "override_dt", "priority_move_dt"],
        "prob_sent": ["end_dt", "trmn_approv_dt"],
        "smot_ofnse_cd": ["full_termination_eff_dt"],
        "wf_crim_hist_dtl": ["lock_dt"],
        "wf_custody_dtl": ["lock_dt"],
        "wf_financial_dtl": ["last_pmt_dt", "lock_dt"],
    },
}


# TODO(#12174): Remove this function once all exemptions have been removed above
def is_column_exempt_from_datetime_parsers(
    state_code: StateCode, file_tag: str, col_name: str
) -> bool:
    if environment.in_test():
        # TODO(#12174): Fix test raw data config fixture files to include datetime
        #  parsers for datetime columns, then remove these exemptions
        if state_code in {
            StateCode.US_DD,
            StateCode.US_LL,
            StateCode.US_XX,
            StateCode.US_YY,
            StateCode.US_WW,
        }:
            return True

    for exemption_map in [
        DATETIME_PARSER_EXEMPTIONS_FILES_REFERENCED_IN_INGEST_VIEWS_AND_DOWNSTREAM_VIEWS,
        DATETIME_PARSER_EXEMPTIONS_FILES_REFERENCED_IN_INGEST_VIEWS_ONLY,
        DATETIME_PARSER_EXEMPTIONS_FILES_REFERENCED_IN_DOWNSTREAM_VIEWS_ONLY,
        DATETIME_PARSER_EXEMPTIONS_NO_DOWNSTREAM_REFERENCES,
    ]:

        if col_name in exemption_map.get(state_code, {}).get(file_tag, set()):
            return True
    return False
