"""add_new_aggregate_tables

Revision ID: a1da0fc514a7
Revises: f117d53a093c
Create Date: 2019-03-05 18:00:43.509921

"""


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a1da0fc514a7'
down_revision = 'f117d53a093c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pa_county_pre_sentenced_aggregate',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('fips', sa.String(length=255), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_granularity', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', create_type=False, name='report_granularity'), nullable=False),
    sa.Column('county_name', sa.Integer(), nullable=True),
    sa.Column('pre_sentenced_population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('fips', 'report_date', 'report_granularity')
    )
    op.create_table('tn_facility_aggregate',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('fips', sa.String(length=255), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_granularity', postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', create_type=False, name='report_granularity'), nullable=False),
    sa.Column('facility_name', sa.Integer(), nullable=True),
    sa.Column('tdoc_backup_population', sa.Integer(), nullable=True),
    sa.Column('local_felons_population', sa.Integer(), nullable=True),
    sa.Column('other_convicted_felons_population', sa.Integer(), nullable=True),
    sa.Column('federal_and_other_population', sa.Integer(), nullable=True),
    sa.Column('convicted_misdemeanor_population', sa.Integer(), nullable=True),
    sa.Column('pretrial_felony_population', sa.Integer(), nullable=True),
    sa.Column('pretrial_misdemeanor_population', sa.Integer(), nullable=True),
    sa.Column('total_jail_population', sa.Integer(), nullable=True),
    sa.Column('total_beds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('fips', 'facility_name', 'report_date', 'report_granularity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tn_facility_aggregate')
    op.drop_table('pa_county_pre_sentenced_aggregate')
    # ### end Alembic commands ###
