# pylint: skip-file
"""incorporate_template_comments

Revision ID: 758610f5bc22
Revises: 46584efcabe7
Create Date: 2021-04-29 12:53:12.526731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "758610f5bc22"
down_revision = "46584efcabe7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
