# List of products with their required exports and statuses
# TODO(#7063): Add product descriptions

products:
  - name: Admin Panel
    is_state_agnostic: True
    exports:
      - INGEST_METADATA
      - VALIDATION_METADATA
    environment: production
  - name: Case Triage
    exports:
      - CASE_TRIAGE
    states:
      - state_code: US_ID
        environment: production
  - name: COVID Dashboard
    is_state_agnostic: True
    exports:
      - COVID_DASHBOARD
    environment: production
  - name: Core Dashboard
    exports:
      - CORE
    states:
      - state_code: US_ND
        environment: production
  - name: Justice Counts
    is_state_agnostic: True
    exports:
      - JUSTICE_COUNTS
    environment: production
  - name: Lantern Dashboard
    exports:
      - LANTERN
      - DASHBOARD_USER_RESTRICTIONS
    states:
      - state_code: US_MO
        environment: production
      - state_code: US_PA
        environment: production
  - name: PO Report
    exports:
      - PO_MONTHLY
    states:
      - state_code: US_ID
        environment: production
      - state_code: US_PA
        environment: staging
  - name: Public Dashboard
    exports:
      - PUBLIC_DASHBOARD
    states:
      - state_code: US_PA
        environment: staging
      - state_code: US_ND
        environment: production
  - name: Vitals
    exports:
      - VITALS
    states:
      - state_code: US_ID
        environment: staging
  - name: Vitals Report
    exports: []
    states:
      - state_code: US_ND
        environment: production
