# Configuration for which validations to run for region US_IX.

region_code: US_IX
# TODO(#10703): Move the exclusions / overrides in this validation config over to the
# US_ID validation config once US_IX is merged into US_ID
dev_mode: False
exclusions: []
max_allowed_error_overrides: []
num_allowed_rows_overrides:
  - validation_name: sentences_undefined_relationship
    hard_num_allowed_rows_override: 150
    override_reason: Needs investigation. Current failing level as of 2/24/23 is 69 rows #TODO(#19047)
