# Configuration for which validations to run for region US_IX.

region_code: US_IX
# TODO(#10703): Move the exclusions / overrides in this validation config over to the
# US_ID validation config once US_IX is merged into US_ID
dev_mode: False
exclusions:
  - validation_name: county_jail_population_person_level_external_comparison
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason:
      TODO(#16974), we haven't launched population projections against Atlas yet (due to an outstanding question about paid beds),
      so US_IX can't be incorporated into this validation yet.
max_allowed_error_overrides:
  - validation_name: most_recent_face_to_face_contact_date_by_person_by_state_comparison
    hard_max_allowed_error_override: 0.03
    override_reason: TODO(#18856), TODO(#18993) - Needs investigation. As of 2/24/23, failing 2.29% in staging and 2.3% in production.
  - validation_name: supervision_population_person_level_external_comparison_matching_people_supervising_officer
    hard_max_allowed_error_override: 0.22
    override_reason: TODO(#18860) - Fixed state specific condition but will need additional investigation after that.
  - validation_name: supervision_population_person_level_external_comparison_matching_people_supervision_level
    hard_max_allowed_error_override: 0.04
    override_reason: TODO(#18859) - Added in IX specific logic to address, will lower threshold once fix confirmed
  - validation_name: incarceration_release_person_level_external_comparison
    hard_max_allowed_error_override: 0.78
    override_reason: TODO(#18862) - Added in IX specific logic to address, will lower threshold once fix confirmed
  - validation_name: incarceration_admission_person_level_external_comparison
    hard_max_allowed_error_override: 0.82
    override_reason: TODO(#18863) - Added in IX specific logic to address, will lower threshold once fix confirmed
num_allowed_rows_overrides:
  - validation_name: admission_pfi_pop_pfi_mismatch
    hard_num_allowed_rows_override: 20
    override_reason:
      TODO(#18815), TODO(#18980) - Needs investigation and will probably need to be handled in IP pre-processing.
      As of 2/24/23, failing for 8 rows in staging and 9 rows in prod
  - validation_name: session_new_admissions_with_no_sentence_date_imposed
    hard_num_allowed_rows_override: 35000
    override_reason: TODO(#18861), TODO(#18990) - Needs investigation.  Current failing level as of 2/24/23 is 29,648 rows in staging and 29,655 rows in prod.  (Known issues with missing sentences)
  - validation_name: session_liberty_releases_with_no_sentence_completion_date
    hard_num_allowed_rows_override: 11000
    override_reason: TODO(#18857), TODO(#18989) - Needs investigation.  Current failing level as of 2/24/23 is 10,870 rows in both staging and prod
  - validation_name: incarceration_commitments_subset_of_admissions
    hard_num_allowed_rows_override: 1
    override_reason: TODO(#18821), TODO(#18981) - Needs investigation. As of 2/24/23, just one failing row and it's an admission from decades ago
  - validation_name: sentences_undefined_relationship
    hard_num_allowed_rows_override: 150
    override_reason: Needs investigation. Current failing level as of 2/24/23 is 69 rows #TODO(#19047)
  - validation_name: sentence_end_dates_before_start_dates
    hard_num_allowed_rows_override: 72000
    override_reason: TODO(#18865) - Needs investigation. Sentence dates are a known issue for Atlas so bumping thresholds for now
  - validation_name: overlapping_supervision_periods
    hard_num_allowed_rows_override: 24000
    override_reason: TODO(#18855) - Needs investigation and just bumping threshold for now
  - validation_name: incarceration_release_reason_no_release_date
    hard_num_allowed_rows_override: 10
    override_reason: TODO(#18818) - Really low error rate so just bumping threshold for now
  - validation_name: sentences_missing_date_imposed
    hard_num_allowed_rows_override: 12000
    override_reason: TODO(#18817) - Issue is coming from ingest charges that aren't attached to an ingested sentence.  Will fix during bug bash.
