# Configuration for which validations to run for region US_OZ.

region_code: US_OZ
dev_mode: True
exclusions:
  - validation_name: case_insights_rates_missing_charges
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: Sentencing assistance case insights are not configured/launched for this state
max_allowed_error_overrides: []
num_allowed_rows_overrides: []
