"""fix_ca_aggregate_granularity_type

Revision ID: 4e8b3d90d337
Revises: 12cd53d9fd86
Create Date: 2019-02-06 18:05:04.031558

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8b3d90d337'
down_revision = '12cd53d9fd86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ca_facility_aggregate', 'report_granularity',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='report_granularity'),
               postgresql_using='report_granularity::text::report_granularity',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ca_facility_aggregate', 'report_granularity',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='report_granularity'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
