# Excluding region codes is only supported in the State and Operations schemas.
production:
  # CREATE A TO-DO TASK FOR EVERY REGION CODE ADDED HERE TO UN-PAUSE THE EXPORT
  region_codes_to_exclude: []
staging:
  # CREATE A TO-DO TASK FOR EVERY REGION CODE ADDED HERE TO UN-PAUSE THE EXPORT
  region_codes_to_exclude:
    - US_PA  # TODO(#4187): Un-pause PA refresh once incarceration periods / incidents have been re-ingested in staging
state_history_tables_to_include:
  - state_person_history
county_columns_to_exclude:
  person:
    - full_name
    - birthdate_inferred_from_age
