# Excluding region codes is only supported in the State and Operations schemas.
production:
  region_codes_to_exclude: [] # CREATE A TO-DO TASK FOR EVERY REGION CODE ADDED HERE TO UN-PAUSE THE EXPORT
staging:
  region_codes_to_exclude: [] # CREATE A TO-DO TASK FOR EVERY REGION CODE ADDED HERE TO UN-PAUSE THE EXPORT
state_history_tables_to_include:
  - state_person_history
county_columns_to_exclude:
  person:
    - full_name
    - birthdate_inferred_from_age
