# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2024 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================
"""
These ingest views have undocumented CTEs.

Assume comments for a CTE go above the alias, like so:

WITH
-- this explains table 1
table_1 AS (
    SELECT * FROM A
),
-- this explains table 2
table_2 AS (
    SELECT * FROM B JOIN C USING(col)
)
SELECT * FROM table_1 UNION ALL SELECT * FROM table_2
"""

from typing import Dict, List

from recidiviz.common.constants.states import StateCode

# state_code -> ingest_view_name -> cte name
# We don't pass the state code Enum because the test class heirarchy that
# gets us to this point uses a str :(

# When we check ingest view CTEs, we will check the ENTIRE view.
# This data structure tracking individual CTEs is to make it easy
# to see what currently needs updating.
# This does mean that updating an ingest view with CTE documentation
# means updating the entire ingest view.
THESE_INGEST_VIEWS_HAVE_UNDOCUMENTED_CTES: Dict[StateCode, Dict[str, List[str]]] = {
    StateCode.US_AR: {
        "incarceration_period": [
            "external_movements_processed",
            "bed_assignment_transition_dates",
            "custody_classification_transition_dates",
            "deduped_transitions",
            "all_transitions",
            "sealed_periods",
        ],
        "incarceration_incident": ["violations", "unpivoted_violation_outcomes"],
        "supervision_sentence": ["sc_cleaned"],
        "person": ["op_cleaned", "aliases", "ora_deduped"],
        "employment_period": ["employer_address"],
        "supervision_violation": ["offenses", "sanctions", "offenses_and_sanctions"],
        "supervision_period": [
            "cleaned_se",
            "tl_periods",
            "se_unique_dates",
            "loc_changes",
            "supervisory_changes",
            "special_status_changes",
            "constructed_periods",
            "periods_with_info",
        ],
    },
    StateCode.US_PA: {
        "supervision_staff_role_period": [
            "critical_dates_from_roster",
            "staff_from_roster",
            "prelim_roster_periods",
            "staff_from_agent_history",
            "supervisors_from_agent_history",
            "staff_from_contacts",
            "all_periods",
        ],
        "person_external_ids": ["recidiviz_primary_person_ids"],
        "sci_incarceration_period": [
            "recidiviz_primary_person_ids",
            "movements_base",
            "movements",
            "movements_with_inflection_indicators",
            "critical_movements",
            "sentence_types",
            "periods",
        ],
        "supervision_violation_response": ["base_sanctions"],
        "doc_person_info": [
            "recidiviz_primary_person_ids",
            "search_inmate_info_with_primary_ids",
            "bad_address_field_values",
            "info_ranked_by_recency",
            "most_recent_info",
            "people",
        ],
        "supervision_violation": ["base_violations"],
        "ccis_incarceration_period": [
            "inmate_number_with_control_numbers",
            "movements_with_single_control_number",
            "movements_base",
            "admission_movements",
            "transfer_movements",
            "release_movements",
            "all_movements",
            "all_movements_without_invalid_edges",
            "program_movements",
            "program_base",
            "full_periods",
            "valid_periods",
            "periods",
        ],
        "supervision_staff_location_period": [
            "contacts_data",
            "roster_data",
            "location_external_ids",
            "cleaned_data",
            "critical_dates",
            "all_periods",
        ],
        "program_assignment": [
            "program_data",
            "TrtClassCode_trim",
            "TrtClassCode_decode",
        ],
        "supervision_staff": [
            "staff_from_roster",
            "raw_staff_from_agent_history",
            "cleaned_staff_from_agent_history",
            "raw_supervisors_from_agent_history",
            "cleaned_supervisors_from_agent_history",
            "staff_from_contacts",
        ],
        "supervision_staff_caseload_type_period": [
            "roster_data",
            "critical_dates",
            "all_periods",
        ],
        "supervision_period_v4": [
            "parole_count_id_level_info_base",
            "conditions_by_parole_count_id",
            "parole_count_id_level_info",
            "start_count_edges",
            "end_count_edges",
            "agent_employee_numbers",
            "agent_history_base",
            "agent_update_dates",
            "agent_update_edges_with_district",
            "all_update_dates",
            "edges_with_sequence_numbers",
            "hydrated_edges",
            "hydrated_edges_better_districts",
            "filtered_edges",
            "supervision_periods",
        ],
        "board_action": ["distinct_codes", "sci_actions"],
        "dbo_tblInmTestScore": ["all_test_scores"],
        "supervision_staff_supervisor_period": [
            "filtered_data",
            "roster_data",
            "critical_dates",
            "all_periods",
        ],
    },
    StateCode.US_ME: {
        "supervision_sentences_v2": [
            "charges",
            "terms",
            "judges",
            "conditions",
            "sentences",
        ],
        "supervision_periods": [
            "transfers",
            "statuses_and_transfers_with_parsed_dates",
            "order_status_dates_chronologically",
            "select_next_effective_datetime",
            "statuses",
            "supervision_officer_assignments",
            "supervision_officer_assignments_dates",
            "join_statuses_and_officers",
            "statuses_and_officers_with_prev_and_next",
            "supervision_periods",
        ],
        "incarceration_task_deadline": ["terms", "sentences", "sorted"],
        "assessments": [
            "non_lsi_assessments",
            "lsi_assessments",
            "lsi_ratings",
            "all_assessments",
        ],
        "CURRENT_STATUS_incarceration_periods_v2": [
            "transfers",
            "statuses_and_transfers_with_parsed_dates",
            "order_status_dates_chronologically",
            "select_next_effective_datetime",
            "statuses",
            "all_bed_assignments",
            "continuous_bed_assignment_periods",
            "bed_assignment_periods",
            "previous_movements_for_deduplication",
            "ranked_movements",
            "ranked_movements_release",
            "movements_with_next_values",
            "join_statuses_to_bed_assignments",
            "join_statuses_to_movements",
            "get_status_end_dates",
            "get_next_and_prev_statuses",
            "incarceration_periods",
        ],
        "incarceration_sentences_v2": [
            "charges",
            "terms",
            "judges",
            "conditions",
            "sentences",
        ],
        "supervision_task_deadline": ["terms", "sentences", "sorted"],
    },
    StateCode.US_NC: {"incarceration_periods": ["sentences", "remove_nested_periods"]},
    StateCode.US_ND: {
        "docstars_offenders": ["annotated_rows"],
        "docstars_staff": ["staff_from_directory", "staff_from_docstars"],
        "docstars_staff_supervisor_periods": ["critical_dates", "all_periods"],
        "docstars_offendercasestable_with_officers": [
            "cases_with_terminating_officers",
            "ranked_term_dates",
            "most_recent_term_date_by_sid",
            "offendercases_with_terminating_and_recent_pos",
        ],
        "docstars_contacts_v2": [
            "contacts_with_split_supervisor_name",
            "latest_officer_info",
        ],
        "docstars_staff_caseload_type_periods": ["roster_data", "critical_dates"],
        "elite_movements_incarceration_periods": [
            "critical_dates",
            "dates_with_all_attributes",
            "full_periods",
            "infer_missing_attributes",
        ],
        "task_deadlines": [
            "supervision_sentence_expiration",
            "sup_filtered",
            "incarceration_sentence_expiration",
            "inc_filtered",
        ],
        "elite_incarceration_sentences": ["charges", "sentences", "terms"],
        "docstars_staff_location_periods": [
            "staff_from_directory",
            "staff_from_docstars",
            "combined_data",
            "critical_dates",
            "all_periods",
        ],
        "elite_offense_in_custody_and_pos_report_data": ["all_entries"],
        "docstars_staff_role_periods": [
            "staff_from_directory",
            "staff_from_docstars",
            "combined_data",
            "critical_dates",
            "all_periods",
        ],
    },
    StateCode.US_AZ: {
        "incarceration_incidents": ["traffic_preprocessed", "base", "code_lookup"],
        "state_task_deadline": [
            "eligibility_dates",
            "release_dates",
            "elig_and_due_dates",
        ],
        "supervision_periods": [
            "critical_dates",
            "base",
            "base_with_descriptions",
            "periods",
            "carry_forward_IDs",
        ],
        "state_charge": ["commitments", "charges"],
        "state_person": [
            "complete_addresses",
            "most_recent_demographics",
            "base_person_info",
        ],
        "state_sentence_group": ["base"],
        "incarceration_periods": [
            "base",
            "base_with_descriptions",
            "locations_preprocessed",
            "base_with_locations",
            "custody_level",
            "locations_decoded",
            "periods",
            "filter_periods",
        ],
    },
    StateCode.US_IA: {},
    StateCode.US_OR: {
        "Incarceration_Incident": ["distinct_mtrlms", "MISCONDUCTS"],
        "Supervision_Period": [
            "transfers",
            "high_level_transfers",
            "releases",
            "custody",
            "locations",
            "clean_supervision_levels",
            "highest_suplevel",
            "prev_supervision_level",
            "supervision_changes",
            "periods",
            "adding_supervision_level",
            "info_to_split_periods_with_supervision_level_changes",
            "split_periods_with_multiple_supervision_levels",
            "staff_caseloads",
            "new_periods",
            "supervision_levels_prior_to_supervision_start",
            "final",
        ],
        "Sentences": [
            "sentence",
            "charge",
            "offense",
            "conditions",
            "additional_info",
            "crime_info",
            "descriptions",
            "ncic_info",
            "final",
        ],
        "Incarceration_Period": [
            "transfers",
            "high_level_transfers",
            "releases",
            "custody",
            "locations",
            "units",
            "cust_clclhd",
            "cust_clover",
            "rank_cust",
            "rank_cust_level",
            "cust_changes",
            "periods",
            "merging_units1",
            "merging_units2",
            "merging_units3",
            "added_releases",
            "cell_changes",
            "additional_releases",
            "add_periods",
            "switch_admission",
            "final",
        ],
        "Program_Assignment": ["programs"],
        "Supervision_Violation_Responses": [
            "base_sanction",
            "imposed_sanc",
            "court_sanction",
            "conditions",
            "all_sanctions",
            "aggr",
            "final",
        ],
        "Supervision_Contact": ["people_on_supervision", "contacts"],
    },
    StateCode.US_IX: {
        "supervision_contacts": ["contact_modes", "legacy_contacts", "atlas_contacts"],
        "state_staff_role_location_periods": [
            "ref_Employee_latest",
            "preliminary_periods",
            "final_periods",
        ],
        "incarceration_sentence_v2": [
            "SentenceBase",
            "RelatedSentence",
            "final_sentences",
        ],
        "transfer_to_supervision_deadline": ["SentenceBase", "lag_cte"],
        "discharge_from_supervision_deadline": ["SentenceBase", "lag_cte"],
        "supervision_violation": ["violated_conditions", "state_violation"],
        "state_staff_supervisor_periods": [
            "preliminary_periods",
            "aggregated_periods",
            "final_supervisor_periods",
        ],
        "state_staff": ["unioned"],
        "supervision_sentence_v2": [
            "SentenceBase",
            "RelatedSentence",
            "final_sentences",
            "ProbationSupervision",
        ],
        "incarceration_period": [
            "transfer_periods_incarceration_cte",
            "security_level_periods_cte",
        ],
        "state_staff_caseload_type_periods": [
            "preliminary_periods",
            "aggregated_periods",
            "caseload_periods",
            "specialized_caseload_periods",
            "general_caseload_periods",
        ],
        "early_discharge_parole": [
            "all_relevant_info_w_request_groupings",
            "all_requests",
        ],
        "person": ["current_address", "alias_records"],
        "state_staff_supervisor_role_periods": [
            "preliminary_periods",
            "aggregated_periods",
            "final_supervisor_periods",
            "all_end_dates",
            "all_dates",
        ],
        "state_staff_role_location_periods_legacy": [
            "all_periods",
            "preliminary_periods",
            "final_periods",
        ],
        "supervision_period": [
            "transfer_periods_supervision_cte",
            "supervision_periods",
        ],
        "supervision_violation_legacy": ["stacked"],
        "discharge_from_incarceration_deadline": [
            "term_base",
            "termOrderDates",
            "sentences_base",
            "lag_cte",
            "SentenceOrderDates",
            "rows_with_eligible",
            "last_val_cte",
        ],
        "supervision_violation_supplemental": [
            "survey_template",
            "survey_responses",
            "survey_answer_per_question",
        ],
    },
    StateCode.US_MI: {
        "incarceration_incident": ["all_info", "penalties_info", "offenses_info"],
        "state_staff_role_period_COMS": ["case_manager_dates"],
        "state_persons_v2": ["latest_booking_profiles"],
        "sentences_v2": ["sentence_records_grouped"],
        "supervision_violations_coms": ["probation_and_violation_joined_incidents"],
        "state_staff": [
            "corrected_adh_shuser",
            "corrected_adh_employee_additional_info",
            "compas",
            "omni_base",
            "omni",
        ],
        "assessments_v3": ["COMPAS"],
        "supervision_periods_v2": [
            "coms_level_periods_base",
            "COMS_levels",
            "offender_supervision_periods",
            "COMS_assignments",
            "offender_booking_assignment",
        ],
        "incarceration_periods_v3": [
            "deduped_lock_records",
            "final_lock_records",
            "internal_movements",
            "deduped_movement_records",
            "final_movement_records",
            "final_movements",
            "ad_seg_designation",
            "all_dates",
            "periods_basic",
            "periods_with_info",
        ],
    },
    StateCode.US_TN: {
        "InferredViolations": [
            "documented_violations",
            "abs_contact_notes",
            "cleaned_contact_note_type",
            "ordered_vwars_vrpts",
            "identifying_likely_related_events",
            "grouping_likely_related_events",
            "all_inferred_violations",
        ],
        "StaffRoleLocationPeriods": [
            "first_reported_title",
            "key_status_change_dates",
            "ranked_rows",
            "create_unique_rows",
            "construct_periods",
        ],
        "OffenderMovementIncarcerationPeriod_v3": ["all_incarceration_periods"],
        "StaffSupervisorPeriods": [
            "first_reported_supervisor",
            "ranked_rows",
            "create_unique_rows",
            "construct_periods",
        ],
        "DisciplinaryIncarcerationIncident": [
            "disciplinary_base",
            "inc_base",
            "disc_outcome",
            "full_inc_and_out",
        ],
        "SupervisionContacts": ["contact_note_type_view"],
        "Staff": [
            "most_recent_staff_information",
            "most_recent_staff_email_information",
        ],
        "AssignedStaffSupervisionPeriod_v2": [
            "officer_names",
            "split_officer_names",
            "cleaned_assignment_periods",
            "raw_supervision_level_periods",
            "ungrouped_supervision_level_sessions",
            "supervision_level_sessions",
            "supervision_level_sessions_padded",
            "combined_officer_and_level",
            "all_supervision_periods",
            "override_backdated_discharges",
            "last_movement_from_OffenderMovement",
            "close_oos_periods",
        ],
        "ViolationsAndSanctions": ["sanctions_groupings"],
        "SentencesChargesAndCourtCases_v4": [
            "order_sentence_actions_by_date_per_sentence",
            "special_conditions_date_grouping",
            "special_conditions_aggregation",
            "cleaned_Sentence_view",
            "cleaned_Diversion_view",
            "consecutive_ISCRelated_sentences",
            "cleaned_ISCSentence_view",
            "all_sentence_sources_joined",
            "all_latest_sentences_joined",
            "most_recent_sentence_information",
            "discharge_task_deadline_array",
        ],
        "CAFScoreAssessment": ["latest_Classification", "CAF_base"],
        "OffenderName": ["normalized_rows", "filtered_out_nicknames"],
    },
    StateCode.US_MO: {
        "sentence_length": [
            "projected_completion_dates",
            "eligibility_dates",
            "incarceration_only_ledger",
            "supervision_only_ledger",
            "unioned_rows",
            "sentence_length_values",
        ],
        "sentence_status_snapshot": ["filtered_sentence_statuses", "sentence_sequence"],
        "offender_sentence_supervision": [
            "classified_status_bw",
            "supervision_sentence_status_xref_bv",
            "non_investigation_supervision_sentences_bu",
            "distinct_supervision_sentence_ids",
            "collapsed_sentence_status_type_classification",
            "supervision_sentence_type_classifier",
            "full_supervision_sentence_info",
            "supervision_sentence_status_xref_with_types",
            "valid_sentences_with_status_xref",
            "ranked_supervision_sentence_status_xref",
            "most_recent_fso_and_status_for_sentence",
            "shock_sentence",
        ],
        "oras_assessments_weekly_v2": [
            "assessments_with_duplicates",
            "duplicate_counts",
        ],
        "incarceration_sentence": [
            "consecutive_parent_sentences",
            "concurrent_parent_sentences",
            "parent_sentence_arrays",
            "base_sentence_info",
            "incarceration_sentence_detail_info",
        ],
        "offender_sentence_institution": [
            "sentence_status_xref",
            "most_recent_status_by_sentence",
            "shock_sentence",
        ],
        "supervision_staff": ["APFX_ALL"],
        "supervision_staff_role_periods": [
            "apfx90_periods",
            "apfx91_periods",
            "apfx_all",
            "collapsed",
        ],
        "tak034_tak026_tak039_apfx90_apfx91_supervision_enhancements_supervision_periods": [
            "field_assignments_ce",
            "field_assignments_next_beg_dt",
            "augmented_field_assignments",
            "field_assignments_with_unique_date_spans",
            "field_assignments_with_valid_region",
            "status_bw",
            "non_inv_start_status_codes",
            "first_non_inv_start_status_code",
            "supv_period_partition_statuses",
            "all_supv_period_critical_dates",
            "supv_period_spans",
            "non_investigation_supv_period_spans",
            "basic_supervision_periods",
            "all_officers",
            "normalized_all_officers",
            "officers_with_role_time_ranks",
            "officer_role_spans",
            "periods_with_officer_info",
            "supervision_case_types",
            "periods_with_officer_and_case_type_info",
            "supervision_type_assessments",
            "supervision_type_with_seq_num",
            "supervision_type_spans",
            "periods_with_officer_case_type_and_supervision_type_info",
            "statuses_on_days",
        ],
        "tak158_tak026_incarceration_periods": [
            "status_bw",
            "sub_cycle_partition_statuses",
            "subcycle_partition_status_change_dates",
            "subcycle_open_status_change_dates",
            "subcycle_close_status_change_dates",
            "all_sub_sub_cycle_critical_dates",
            "sub_subcycle_spans",
            "most_recent_status_updates",
            "cleaned_facility_locations",
            "cleaned_housing_details",
            "start_date_cte",
            "end_date_cte",
            "start_and_end_dates_join",
            "start_and_end_dates_different_days",
            "start_and_end_dates_same_day_status",
            "start_and_end_dates_same_day_facility",
            "start_and_end_dates_same_day_housing",
            "start_and_end_dates_cte",
            "start_end_facility",
            "start_end_facility_housing",
        ],
        "tak028_tak042_tak076_tak024_violation_reports": [
            "non_investigation_supervision_sentences_bu",
            "all_officers",
            "normalized_all_officers",
            "officers_with_role_recency_ranks",
            "officers_with_recent_role",
            "conditions_violated_cf",
            "valid_sentences_cz",
            "finally_formed_violations_e6",
        ],
        "tak291_tak292_tak024_citations": [
            "non_investigation_supervision_sentences_bu",
            "valid_sentences_js",
            "citations_with_multiple_violations_jt",
            "finally_formed_citations_e6",
        ],
        "supervision_sentence": ["charge_info", "supervision_sentence_info"],
    },
    StateCode.US_CA: {
        "staff": [
            "staff_from_AgentParole",
            "staff_from_PersonParole",
            "unioned",
            "final",
        ],
        "staff_location_and_role_period": ["pa_1_location_periods"],
        "staff_supervisor_periods": [
            "agents",
            "filled_all_dates",
            "proto_supervisor_periods",
            "proto_supervisor_periods_2",
        ],
        "supervision_period": [
            "IncarcerationParole_parsed",
            "merged_supervision_periods",
            "offender_group_transitions_no_filter",
            "offender_group_transitions",
            "nullBadgeCTE",
            "supervision_officer_prep_cte",
            "supervision_officer_periods",
            "supervision_location_prep_cte",
            "supervision_location_prep_cte2",
            "supervision_location_periods",
            "supervision_level_changes",
            "supervision_level_periods",
            "transition_dates",
            "periods_cte",
            "periods_cte_dropping_incarceration_periods",
            "merged_supervision_periods_with_supervision_level_and_offender_groups",
            "merged_supervision_periods_with_location",
            "merged_supervision_periods_with_officer",
        ],
    },
    StateCode.US_ID: {},
    StateCode.US_OZ: {"ageid_staff_supervisor": ["critical_dates"]},
    StateCode.US_CO: {
        "IncarcerationIncident": [
            "incident_base",
            "id",
            "inc_type",
            "loc",
            "outcome",
            "incidents",
            "inc_and_out",
        ],
        "IncarcerationSentence": ["commitprefix", "sequences"],
        "StatePerson": ["normalized_rows"],
        "IncarcerationPeriod": [
            "movements_with_direction",
            "movements",
            "isp",
            "classified_movements",
            "ordered_movements",
            "periods",
            "permanent_moves",
            "missing_releases_handled",
            "final",
        ],
    },
}
