name: "Python Setup"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8.8"
    - name: Install pipenv
      run: pip install pipenv
      shell: bash
    - name: Pipenv caching
      uses: actions/cache@v2
      id: pipenv-caching
      with:
        path: ~/.local/share/virtualenvs/
        key: pipenv-cache-v2-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          pipenv-cache-v2-${{ hashFiles('**/Pipfile.lock') }}
          pipenv-cache-v2-
    - name: Sync pipenv
      if: steps.pipenv-caching.outputs.cache-hit != 'true'
      run: pipenv sync --dev
      shell: bash
