# Configuration describing the schema for our external validation tables.

dataset: validation_external_accuracy
tables:
  - name: incarceration_admission_person_level_materialized
    description: person-level incarceration admissions
    columns:
      - region_code
      - person_external_id
      - external_id_type
      - admission_date
  - name: incarceration_population_by_facility_materialized
    description: aggregate incarceration facility populations
    columns:
      - state_code
      - region_code
      - year
      - month
      - date_of_stay
      - facility
      - population_count
  - name: incarceration_population_person_level_materialized
    description: person-level incarceration population
    columns:
      - region_code
      - person_external_id
      - external_id_type
      - date_of_stay
      - facility
  - name: incarceration_release_person_level_materialized
    description: person-level incarceration releases
    columns:
      - region_code
      - person_external_id
      - external_id_type
      - release_date
  - name: population_projection_monthly_population_materialized
    description: aggregate projected populations by month
    columns:
      - region_code
      - compartment
      - year
      - month
      - total_population
  - name: population_projection_monthly_population_per_facility_materialized
    description: aggregate projected facility populations by month
    columns:
      - region_code
      - compartment
      - year
      - month
      - facility
      - total_population
      - average_population
      - r_facility
  - name: recidivism_person_level_materialized
    description: person-level recidivations
    columns:
      - region_code
      - release_cohort
      - follow_up_period
      - person_external_id
      - recidivated
  - name: supervision_early_discharge_person_level_materialized
    description: person-level supervision early discharge
    columns:
      - state_code
      - region_code
      - person_external_id
      - supervision_type
      - request_date
      - discharge_date
      - parole_decision
      - jurisdiction_decision_code_id
  - name: supervision_population_person_level_materialized
    description: person-level supervision population
    columns:
      - region_code
      - person_external_id
      - external_id_type
      - date_of_supervision
      - district
      - supervising_officer
      - supervision_level
  - name: supervision_start_person_level_materialized
    description: person-level supervision starts
    columns:
      - region_code
      - person_external_id
      - start_date
  - name: supervision_termination_person_level_materialized
    description: person-level supervision terminations
    columns:
      - region_code
      - person_external_id
      - termination_date
  - name: county_jail_population_person_level_materialized
    description: person-level county jail populations
    columns:
      - region_code
      - person_external_id
      - external_id_type
      - facility
      - legal_status
      - date_of_stay
  - name: supervision_population_by_type_materialized
    description: aggregate supervision populations by type
    columns:
      - region_code
      - date_of_supervision
      - supervision_type
      - population_count
  - name: incarceration_population_by_custody_level_materialized
    description: aggregate incarceration custody level populations
    columns:
      - region_code
      - date_of_stay
      - custody_level
      - population_count
