# Configuration describing the schema for our external validation tables.

dataset: validation_external_accuracy
tables:
  - name: incarceration_admission_person_level
    columns:
      - region_code
      - person_external_id
      - admission_date
  - name: incarceration_population_by_facility
    columns:
      - region_code
      - year
      - month
      - date_of_stay
      - facility
      - population_count
  - name: incarceration_population_person_level
    columns:
      - region_code
      - person_external_id
      - date_of_stay
      - facility
  - name: incarceration_release_person_level
    columns:
      - region_code
      - person_external_id
      - release_date
  - name: population_projection_monthly_population
    columns:
      - region_code
      - compartment
      - year
      - month
      - total_population
  - name: population_projection_monthly_population_per_facility
    columns:
      - region_code
      - compartment
      - year
      - month
      - facility
      - total_population
      - average_population
      - r_facility
  - name: recidivism_person_level
    columns:
      - region_code
      - release_cohort
      - follow_up_period
      - person_external_id
      - recidivated
  - name: supervision_early_discharge_person_level
    columns:
      - region_code
      - person_external_id
      - supervision_type
      - request_date
      - discharge_date
      - parole_decision
      - jurisdiction_decision_code_id
  - name: supervision_population_person_level
    columns:
      - region_code
      - person_external_id
      - date_of_supervision
      - district
      - supervising_officer
      - supervision_level
  - name: supervision_start_person_level
    columns:
      - region_code
      - person_external_id
      - start_date
  - name: supervision_termination_person_level
    columns:
      - region_code
      - person_external_id
      - termination_date
