# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2020 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================
"""Defines all Justice Counts metrics for the Law Enforcement system."""

from recidiviz.common.constants.justice_counts import ContextKey, ValueType
from recidiviz.justice_counts.dimensions.law_enforcement import (
    CallType,
    ForceType,
    LawEnforcementStaffType,
    OffenseType,
    SheriffBudgetType,
)
from recidiviz.justice_counts.dimensions.person import (
    GenderRestricted,
    RaceAndEthnicity,
)
from recidiviz.justice_counts.metrics.metric_definition import (
    AggregatedDimension,
    CallsRespondedOptions,
    Context,
    Definition,
    MetricCategory,
    MetricDefinition,
    ReportingFrequency,
)
from recidiviz.persistence.database.schema.justice_counts.schema import (
    MeasurementType,
    MetricType,
    System,
)

residents = MetricDefinition(
    system=System.LAW_ENFORCEMENT,
    metric_type=MetricType.RESIDENTS,
    category=MetricCategory.POPULATIONS,
    display_name="Jurisdiction Residents",
    description="Measures the number of residents in your agency's jurisdiction.",
    measurement_type=MeasurementType.INSTANT,
    reporting_frequencies=[ReportingFrequency.MONTHLY, ReportingFrequency.ANNUAL],
    specified_contexts=[
        Context(
            key=ContextKey.JURISDICTION_AREA,
            value_type=ValueType.NUMBER,
            label="Please provide the land size (area) of the jurisdiction.",
            required=False,
        )
    ],
    aggregated_dimensions=[
        AggregatedDimension(dimension=RaceAndEthnicity, required=True),
        AggregatedDimension(dimension=GenderRestricted, required=True),
    ],
    disabled=True,
)

annual_budget = MetricDefinition(
    system=System.LAW_ENFORCEMENT,
    metric_type=MetricType.BUDGET,
    category=MetricCategory.CAPACITY_AND_COST,
    display_name="Annual Budget",
    description="Measures the total annual budget (in dollars) of your agency.",
    measurement_type=MeasurementType.INSTANT,
    reporting_frequencies=[ReportingFrequency.ANNUAL],
    specified_contexts=[
        Context(
            key=ContextKey.PRIMARY_FUNDING_SOURCE,
            value_type=ValueType.TEXT,
            label="Please describe your primary funding source.",
            required=False,
        )
    ],
    # Unclear if we need this, based on the current spec
    aggregated_dimensions=[
        AggregatedDimension(dimension=SheriffBudgetType, required=False, disabled=True)
    ],
)

calls_for_service = MetricDefinition(
    system=System.LAW_ENFORCEMENT,
    metric_type=MetricType.CALLS_FOR_SERVICE,
    category=MetricCategory.OPERATIONS_AND_DYNAMICS,
    display_name="Calls for Service",
    description="Measures the number of calls for service routed to your agency.",
    measurement_type=MeasurementType.DELTA,
    reporting_frequencies=[ReportingFrequency.MONTHLY],
    reporting_note="Do not include calls that are officer-initiated.",
    definitions=[
        Definition(
            term="Calls for service",
            definition="One case that represents a request for police service generated by the community and received through an emergency or non-emergency method (911, 311, 988, online report). Count all calls for service, regardless of whether an underlying incident report was filed.",
        )
    ],
    specified_contexts=[
        Context(
            key=ContextKey.ALL_CALLS_OR_CALLS_RESPONDED,
            value_type=ValueType.MULTIPLE_CHOICE,
            label="Does the total value include all calls or just those responded to?",
            required=True,
            multiple_choice_options=CallsRespondedOptions,
        ),
        Context(
            key=ContextKey.AGENCIES_AVAILABLE_FOR_RESPONSE,
            value_type=ValueType.TEXT,
            label="Please list the names of all agencies available for response.",
            required=False,
        ),
    ],
    aggregated_dimensions=[AggregatedDimension(dimension=CallType, required=True)],
)

police_officers = MetricDefinition(
    system=System.LAW_ENFORCEMENT,
    metric_type=MetricType.TOTAL_STAFF,
    category=MetricCategory.CAPACITY_AND_COST,
    display_name="Total Police Officers",
    description="Measures the number of full or part-time sworn officers employed by your agency.",
    measurement_type=MeasurementType.INSTANT,
    reporting_frequencies=[ReportingFrequency.ANNUAL],
    aggregated_dimensions=[
        AggregatedDimension(dimension=LawEnforcementStaffType, required=True)
    ],
)

reported_crime = MetricDefinition(
    system=System.LAW_ENFORCEMENT,
    metric_type=MetricType.REPORTED_CRIME,
    category=MetricCategory.POPULATIONS,
    display_name="Reported Crime",
    description="Measures the number of crimes reported to your agency.",
    definitions=[
        Definition(
            term="Crime incident",
            definition="One case that represents one or more offenses committed by the same person/group of persons at the same time and place and for which a crime report was filed. Report each incident only once, relying on the FBI hierarchy rule for crime reporting.",
        )
    ],
    measurement_type=MeasurementType.DELTA,
    reporting_frequencies=[ReportingFrequency.MONTHLY],
    aggregated_dimensions=[AggregatedDimension(dimension=OffenseType, required=True)],
)

total_arrests = MetricDefinition(
    system=System.LAW_ENFORCEMENT,
    metric_type=MetricType.ARRESTS,
    category=MetricCategory.POPULATIONS,
    display_name="Total Arrests",
    description="Measures the number of arrests made by your agency.",
    specified_contexts=[
        Context(
            key=ContextKey.JURISDICTION_DEFINITION_OF_ARREST,
            value_type=ValueType.TEXT,
            label="Please provide your jurisdiction's definition of arrest.",
            required=True,
        )
    ],
    measurement_type=MeasurementType.DELTA,
    reporting_frequencies=[ReportingFrequency.MONTHLY],
    aggregated_dimensions=[
        AggregatedDimension(dimension=OffenseType, required=True),
        AggregatedDimension(dimension=RaceAndEthnicity, required=True),
        AggregatedDimension(dimension=GenderRestricted, required=True),
    ],
)

officer_use_of_force_incidents = MetricDefinition(
    system=System.LAW_ENFORCEMENT,
    metric_type=MetricType.USE_OF_FORCE_INCIDENTS,
    category=MetricCategory.PUBLIC_SAFETY,
    display_name="Use of Force Incidents",
    description="Measures the number of use of force incidents.",
    measurement_type=MeasurementType.DELTA,
    reporting_frequencies=[ReportingFrequency.ANNUAL],
    reporting_note="Select the most serious type of force used per incident.",
    definitions=[
        Definition(
            term="Use of force incident",
            definition="An event in which an officer uses force towards or in the vicinity of a civilian. The FBI focuses on uses of force resulting in injury or a discharge of a weapon.  Count all uses of force occurring during the same event as 1 incident.",
        )
    ],
    specified_contexts=[
        Context(
            key=ContextKey.JURISDICTION_DEFINITION_OF_USE_OF_FORCE,
            value_type=ValueType.TEXT,
            label="Please provide your jurisdiction's definition of use of force.",
            required=True,
        )
    ],
    aggregated_dimensions=[AggregatedDimension(dimension=ForceType, required=True)],
)

civilian_complaints_sustained = MetricDefinition(
    system=System.LAW_ENFORCEMENT,
    metric_type=MetricType.COMPLAINTS_SUSTAINED,
    category=MetricCategory.FAIRNESS,
    reporting_note="Disclaimer: Many factors can lead to a complaint being filed, and to a final decision on the complaint. These factors may also vary by agency and jurisdiction.",
    display_name="Civilian Complaints Sustained",
    description="Measures the number of complaints filed against officers in your agency that were ultimately sustained.",
    measurement_type=MeasurementType.DELTA,
    reporting_frequencies=[ReportingFrequency.ANNUAL],
    definitions=[
        Definition(
            term="Complaint",
            definition="One case that represents one or more acts committed by the same officer, or group of officers at the same time and place. Count all complaints, regardless of whether an underlying incident was filed.",
        ),
        Definition(
            term="Sustained",
            definition="Found to be supported by the evidence, and may or may not result in disciplinary action.",
        ),
    ],
)
