# pylint: skip-file
"""delete_supervision_type

Revision ID: b4a5dd037630
Revises: b81aa5311fb7
Create Date: 2021-09-28 19:00:13.652702

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b4a5dd037630"
down_revision = "b81aa5311fb7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("state_supervision_period", "supervision_type_raw_text")
    op.drop_column("state_supervision_period", "supervision_type")
    op.drop_column("state_supervision_period_history", "supervision_type_raw_text")
    op.drop_column("state_supervision_period_history", "supervision_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "state_supervision_period_history",
        sa.Column(
            "supervision_type",
            postgresql.ENUM(
                "CIVIL_COMMITMENT",
                "EXTERNAL_UNKNOWN",
                "INTERNAL_UNKNOWN",
                "HALFWAY_HOUSE",
                "PAROLE",
                "POST_CONFINEMENT",
                "PRE_CONFINEMENT",
                "PROBATION",
                name="state_supervision_type",
            ),
            autoincrement=False,
            nullable=True,
            comment="DEPRECATED - use supervision_period_supervision_type instead. See #2891.",
        ),
    )
    op.add_column(
        "state_supervision_period_history",
        sa.Column(
            "supervision_type_raw_text",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="DEPRECATED - use supervision_period_supervision_type instead. See #2891.",
        ),
    )
    op.add_column(
        "state_supervision_period",
        sa.Column(
            "supervision_type",
            postgresql.ENUM(
                "CIVIL_COMMITMENT",
                "EXTERNAL_UNKNOWN",
                "INTERNAL_UNKNOWN",
                "HALFWAY_HOUSE",
                "PAROLE",
                "POST_CONFINEMENT",
                "PRE_CONFINEMENT",
                "PROBATION",
                name="state_supervision_type",
            ),
            autoincrement=False,
            nullable=True,
            comment="DEPRECATED - use supervision_period_supervision_type instead. See #2891.",
        ),
    )
    op.add_column(
        "state_supervision_period",
        sa.Column(
            "supervision_type_raw_text",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="DEPRECATED - use supervision_period_supervision_type instead. See #2891.",
        ),
    )
    # ### end Alembic commands ###
