# pylint: skip-file
"""add_state_charge_is_sex_offense

Revision ID: 8a50c937d9cb
Revises: ca75d6f5dfcb
Create Date: 2021-05-24 14:06:19.714541

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8a50c937d9cb"
down_revision = "ca75d6f5dfcb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "state_charge",
        sa.Column(
            "is_sex_offense",
            sa.Boolean(),
            nullable=True,
            comment="Whether or not the violation involved a sex offense.",
        ),
    )
    op.add_column(
        "state_charge_history",
        sa.Column(
            "is_sex_offense",
            sa.Boolean(),
            nullable=True,
            comment="Whether or not the violation involved a sex offense.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("state_charge_history", "is_sex_offense")
    op.drop_column("state_charge", "is_sex_offense")
    # ### end Alembic commands ###
