# pylint: skip-file
"""add context model

Revision ID: 335faf1d5933
Revises: a6dd983bb209
Create Date: 2022-04-26 10:26:23.560688

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "335faf1d5933"
down_revision = "a6dd983bb209"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "context",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("report_table_instance_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_table_instance_id"],
            ["report_table_instance.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_table_instance_id", "key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("context")
    # ### end Alembic commands ###
