# pylint: skip-file
"""add system to report table definition unique constraint

Revision ID: 54f8ecddcf7a
Revises: 5185e0815a48
Create Date: 2022-04-05 10:37:53.440958

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "54f8ecddcf7a"
down_revision = "5185e0815a48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "report_table_definition_columns_for_key",
        "report_table_definition",
        type_="unique",
    )
    op.create_unique_constraint(
        "report_table_definition_columns_for_key",
        "report_table_definition",
        [
            "system",
            "metric_type",
            "measurement_type",
            "filtered_dimensions",
            "filtered_dimension_values",
            "aggregated_dimensions",
            "label",
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "report_table_definition_columns_for_key",
        "report_table_definition",
        type_="unique",
    )
    op.create_unique_constraint(
        "report_table_definition_columns_for_key",
        "report_table_definition",
        [
            "metric_type",
            "measurement_type",
            "filtered_dimensions",
            "filtered_dimension_values",
            "aggregated_dimensions",
            "label",
        ],
    )
    # ### end Alembic commands ###
