# pylint: skip-file
"""fix metric keys

Revision ID: bb15006cf148
Revises: 9fdc6aab3552
Create Date: 2022-08-08 11:09:37.817602

"""
import sqlalchemy as sa
from alembic import op

from recidiviz.utils.string import StrictStringFormatter

# revision identifiers, used by Alembic.
revision = "bb15006cf148"
down_revision = "9fdc6aab3552"
branch_labels = None
depends_on = None


OLD_KEY_TO_NEW_KEY = {
    "LAW_ENFORCEMENT_BUDGET_metric/law_enforcement/budget/type": "LAW_ENFORCEMENT_BUDGET_",
    "LAW_ENFORCEMENT_TOTAL_STAFF_metric/law_enforcement/staff/type": "LAW_ENFORCEMENT_TOTAL_STAFF_",
    "JAILS_RELEASES_global/gender/restricted,global/race_and_ethnicity,metric/jails/release/type": "JAILS_RELEASES_metric/jails/release/type",
    "JAILS_POPULATION_metric/jails/population/type": "JAILS_POPULATION_global/gender/restricted,global/race_and_ethnicity,metric/jails/population/type",
}

NEW_KEY_TO_OLD_KEY = {v: k for k, v in OLD_KEY_TO_NEW_KEY.items()}

QUERY = """
UPDATE datapoint SET metric_definition_key = '{new_key}' WHERE metric_definition_key = '{old_key}';
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for old_key, new_key in OLD_KEY_TO_NEW_KEY.items():
        op.execute(
            StrictStringFormatter().format(
                QUERY,
                old_key=old_key,
                new_key=new_key,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for new_key, old_key in NEW_KEY_TO_OLD_KEY.items():
        StrictStringFormatter().format(
            QUERY,
            old_key=new_key,
            new_key=old_key,
        )
    # ### end Alembic commands ###
