# pylint: skip-file
"""add email and name to user account

Revision ID: 5185e0815a48
Revises: 17df78c45454
Create Date: 2022-04-04 10:48:15.381288

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5185e0815a48"
down_revision = "17df78c45454"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account", sa.Column("name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "user_account",
        sa.Column("email_address", sa.String(length=255), nullable=False),
    )
    op.alter_column(
        "user_account",
        "auth0_user_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.create_unique_constraint(
        "unique_email_address", "user_account", ["email_address"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_email_address", "user_account", type_="unique")
    op.alter_column(
        "user_account",
        "auth0_user_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("user_account", "email_address")
    op.drop_column("user_account", "name")
    # ### end Alembic commands ###
