# pylint: skip-file
"""add enabled to datapoint_history table.

Revision ID: c50f621bac41
Revises: e86e2b9d9ade
Create Date: 2023-12-18 14:35:25.175510

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c50f621bac41"
down_revision = "e86e2b9d9ade"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "datapoint_history", sa.Column("old_enabled", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "datapoint_history", sa.Column("new_enabled", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("datapoint_history", "new_enabled")
    op.drop_column("datapoint_history", "old_enabled")
    # ### end Alembic commands ###
