# pylint: skip-file
"""add column

Revision ID: cc2840969c2a
Revises: 886fb2f2a3ce
Create Date: 2023-02-13 15:04:00.820919

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cc2840969c2a"
down_revision = "886fb2f2a3ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account",
        sa.Column(
            "guidance_progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "guidance_progress")
    # ### end Alembic commands ###
