# pylint: skip-file
"""index-is-report-datapoint

Revision ID: d3ea3d85ccaf
Revises: c50f621bac41
Create Date: 2024-02-16 09:15:40.404320

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d3ea3d85ccaf"
down_revision = "c50f621bac41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_datapoint_is_report_datapoint"),
        "datapoint",
        ["is_report_datapoint"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_datapoint_is_report_datapoint"), table_name="datapoint")
    # ### end Alembic commands ###
