# pylint: skip-file
"""add_database_name

Revision ID: 1f6edf08e547
Revises: fc29e1c1b961
Create Date: 2021-03-16 14:49:02.413163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f6edf08e547"
down_revision = "fc29e1c1b961"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "direct_ingest_ingest_file_metadata",
        sa.Column("ingest_database_name", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("direct_ingest_ingest_file_metadata", "ingest_database_name")
    # ### end Alembic commands ###
