# pylint: skip-file
"""fix_sftp_timestamps

Revision ID: 9d8a8601ffcb
Revises: 495f39d5e421
Create Date: 2022-12-14 11:19:50.449950

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d8a8601ffcb"
down_revision = "495f39d5e421"
branch_labels = None
depends_on = None


UPGRADE_REMOTE_FILE_DISCOVERY_QUERY = """
UPDATE direct_ingest_sftp_remote_file_metadata SET file_discovery_time=discovery_time AT TIME ZONE 'UTC';
"""
UPGRADE_REMOTE_FILE_DOWNLOAD_QUERY = """
UPDATE direct_ingest_sftp_remote_file_metadata SET file_download_time=download_time AT TIME ZONE 'UTC';
"""
UPGRADE_INGEST_READY_DISCOVERY_QUERY = """
UPDATE direct_ingest_sftp_ingest_ready_file_metadata SET file_discovery_time=discovery_time AT TIME ZONE 'UTC';
"""
UPGRADE_INGEST_READY_UPLOAD_QUERY = """
UPDATE direct_ingest_sftp_ingest_ready_file_metadata SET file_upload_time=upload_time AT TIME ZONE 'UTC';
"""
DOWNGRADE_REMOTE_FILE_DISCOVERY_QUERY = """
UPDATE direct_ingest_sftp_remote_file_metadata SET discovery_time=file_discovery_time AT TIME ZONE 'UTC';
"""
DOWNGRADE_REMOTE_FILE_DOWNLOAD_QUERY = """
UPDATE direct_ingest_sftp_remote_file_metadata SET download_time=file_download_time AT TIME ZONE 'UTC';
"""
DOWNGRADE_INGEST_READY_DISCOVERY_QUERY = """
UPDATE direct_ingest_sftp_ingest_ready_file_metadata SET discovery_time=file_discovery_time AT TIME ZONE 'UTC';
"""
DOWNGRADE_INGEST_READY_UPLOAD_QUERY = """
UPDATE direct_ingest_sftp_ingest_ready_file_metadata SET upload_time=file_upload_time AT TIME ZONE 'UTC';
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "direct_ingest_sftp_ingest_ready_file_metadata",
        sa.Column(
            "file_discovery_time", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "direct_ingest_sftp_ingest_ready_file_metadata",
        sa.Column(
            "file_upload_time", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
    )
    with op.get_context().autocommit_block():
        op.execute(UPGRADE_INGEST_READY_DISCOVERY_QUERY)
        op.execute(UPGRADE_INGEST_READY_UPLOAD_QUERY)
    op.drop_column("direct_ingest_sftp_ingest_ready_file_metadata", "upload_time")
    op.drop_column("direct_ingest_sftp_ingest_ready_file_metadata", "discovery_time")
    op.add_column(
        "direct_ingest_sftp_remote_file_metadata",
        sa.Column(
            "file_discovery_time", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "direct_ingest_sftp_remote_file_metadata",
        sa.Column(
            "file_download_time", postgresql.TIMESTAMP(timezone=True), nullable=True
        ),
    )
    with op.get_context().autocommit_block():
        op.execute(UPGRADE_REMOTE_FILE_DISCOVERY_QUERY)
        op.execute(UPGRADE_REMOTE_FILE_DOWNLOAD_QUERY)
    op.drop_column("direct_ingest_sftp_remote_file_metadata", "download_time")
    op.drop_column("direct_ingest_sftp_remote_file_metadata", "discovery_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "direct_ingest_sftp_remote_file_metadata",
        sa.Column(
            "discovery_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "direct_ingest_sftp_remote_file_metadata",
        sa.Column(
            "download_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    with op.get_context().autocommit_block():
        op.execute(DOWNGRADE_REMOTE_FILE_DISCOVERY_QUERY)
        op.execute(DOWNGRADE_REMOTE_FILE_DOWNLOAD_QUERY)
    op.drop_column("direct_ingest_sftp_remote_file_metadata", "file_download_time")
    op.drop_column("direct_ingest_sftp_remote_file_metadata", "file_discovery_time")
    op.add_column(
        "direct_ingest_sftp_ingest_ready_file_metadata",
        sa.Column(
            "discovery_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "direct_ingest_sftp_ingest_ready_file_metadata",
        sa.Column(
            "upload_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    with op.get_context().autocommit_block():
        op.execute(DOWNGRADE_INGEST_READY_DISCOVERY_QUERY)
        op.execute(DOWNGRADE_INGEST_READY_UPLOAD_QUERY)
    op.drop_column("direct_ingest_sftp_ingest_ready_file_metadata", "file_upload_time")
    op.drop_column(
        "direct_ingest_sftp_ingest_ready_file_metadata", "file_discovery_time"
    )
    # ### end Alembic commands ###
