# pylint: skip-file
"""discovery_tz_migration

Revision ID: 2dbffd5fff56
Revises: 741b41909611
Create Date: 2022-12-29 14:12:42.022097

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2dbffd5fff56"
down_revision = "741b41909611"
branch_labels = None
depends_on = None

UPGRADE_QUERY = """
UPDATE direct_ingest_raw_file_metadata SET file_discovery_time=discovery_time AT TIME ZONE 'UTC';
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # In order to safely deploy this change, we need to stagger adding the new `file_discovery_time` colum and dropping
    # the old `discovery_time` column into different releases.
    # A future migration will safely drop the original column `discovery_time`.
    op.add_column(
        "direct_ingest_raw_file_metadata",
        sa.Column(
            "file_discovery_time",
            postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
    )
    with op.get_context().autocommit_block():
        op.execute(UPGRADE_QUERY)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("direct_ingest_raw_file_metadata", "file_discovery_time")
    pass
    # ### end Alembic commands ###
