# pylint: skip-file
"""raw_tz_migration

Revision ID: b058f8ad693a
Revises: 2dbffd5fff56
Create Date: 2022-12-29 14:34:58.688092

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b058f8ad693a"
down_revision = "2dbffd5fff56"
branch_labels = None
depends_on = None

PROCESSED_UPGRADE_QUERY = """
UPDATE direct_ingest_raw_file_metadata SET file_processed_time=processed_time AT TIME ZONE 'UTC';
"""

UPPER_BOUND_UPGRADE_QUERY = """
UPDATE direct_ingest_raw_file_metadata SET update_datetime=datetimes_contained_upper_bound_inclusive AT TIME ZONE 'UTC';
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "direct_ingest_raw_file_metadata",
        sa.Column("file_processed_time", sa.DateTime(timezone=True), nullable=True),
    )
    with op.get_context().autocommit_block():
        op.execute(PROCESSED_UPGRADE_QUERY)

    op.add_column(
        "direct_ingest_raw_file_metadata",
        sa.Column(
            "update_datetime",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    with op.get_context().autocommit_block():
        op.execute(UPPER_BOUND_UPGRADE_QUERY)

    op.alter_column(
        "direct_ingest_raw_file_metadata", "update_datetime", nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("direct_ingest_raw_file_metadata", "update_datetime")
    op.drop_column("direct_ingest_raw_file_metadata", "file_processed_time")
    # ### end Alembic commands ###
