# pylint: skip-file
"""add_llm_extraction_tables

Revision ID: 9ac715eedb6f
Revises: a91841509ed8
Create Date: 2026-06-16 15:48:37.111672

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9ac715eedb6f"
down_revision = "a91841509ed8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_extraction_eligible_document_metadata",
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("document_contents_id", sa.String(length=255), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column(
            "document_update_datetime", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "row_creation_datetime_utc", sa.DateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("state_code", "document_contents_id"),
    )
    op.create_index(
        op.f("ix_llm_extraction_eligible_document_metadata_state_code"),
        "llm_extraction_eligible_document_metadata",
        ["state_code"],
        unique=False,
    )
    op.create_table(
        "llm_extractor_collection",
        sa.Column("collection_name", sa.String(length=255), nullable=False),
        sa.Column("collection_version_id", sa.String(length=255), nullable=False),
        sa.Column("output_schema_version", sa.String(length=255), nullable=False),
        sa.Column("output_schema_json", sa.Text(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("minimum_confidence_level", sa.String(length=255), nullable=False),
        sa.Column(
            "row_creation_datetime_utc", sa.DateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("collection_name", "collection_version_id"),
    )
    op.create_table(
        "llm_extractor",
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("extractor_id", sa.String(length=255), nullable=False),
        sa.Column("extractor_collection_name", sa.String(length=255), nullable=False),
        sa.Column(
            "input_document_collection_name", sa.String(length=255), nullable=False
        ),
        sa.Column(
            "row_creation_datetime_utc", sa.DateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("state_code", "extractor_id"),
    )
    op.create_index(
        op.f("ix_llm_extractor_state_code"),
        "llm_extractor",
        ["state_code"],
        unique=False,
    )
    op.create_table(
        "llm_extractor_document_filter",
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("extractor_id", sa.String(length=255), nullable=False),
        sa.Column("document_filter_id", sa.String(length=255), nullable=False),
        sa.Column("document_metadata_filter_query_template", sa.Text(), nullable=False),
        sa.Column(
            "row_creation_datetime_utc", sa.DateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["state_code", "extractor_id"],
            ["llm_extractor.state_code", "llm_extractor.extractor_id"],
            name="llm_extractor_document_filter_extractor_fkey",
        ),
        sa.PrimaryKeyConstraint("state_code", "extractor_id", "document_filter_id"),
    )
    op.create_index(
        op.f("ix_llm_extractor_document_filter_state_code"),
        "llm_extractor_document_filter",
        ["state_code"],
        unique=False,
    )
    op.create_table(
        "llm_extractor_version",
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("extractor_version_id", sa.String(length=255), nullable=False),
        sa.Column("extractor_id", sa.String(length=255), nullable=False),
        sa.Column("extractor_collection_name", sa.String(length=255), nullable=False),
        sa.Column(
            "extractor_collection_version_id", sa.String(length=255), nullable=False
        ),
        sa.Column("instructions_prompt", sa.Text(), nullable=False),
        sa.Column("instructions_prompt_hash", sa.String(length=255), nullable=False),
        sa.Column("model_config_name", sa.String(length=255), nullable=False),
        sa.Column("model_config_version_id", sa.String(length=255), nullable=False),
        sa.Column(
            "invalidated_datetime_utc", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("invalidation_reason", sa.Text(), nullable=True),
        sa.Column(
            "row_creation_datetime_utc", sa.DateTime(timezone=True), nullable=False
        ),
        sa.CheckConstraint(
            "(invalidated_datetime_utc IS NULL) = (invalidation_reason IS NULL)",
            name="llm_extractor_version_invalidation_fields_consistent",
        ),
        sa.ForeignKeyConstraint(
            ["extractor_collection_name", "extractor_collection_version_id"],
            [
                "llm_extractor_collection.collection_name",
                "llm_extractor_collection.collection_version_id",
            ],
            name="llm_extractor_version_collection_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["state_code", "extractor_id"],
            ["llm_extractor.state_code", "llm_extractor.extractor_id"],
            name="llm_extractor_version_extractor_fkey",
        ),
        sa.PrimaryKeyConstraint("state_code", "extractor_version_id"),
    )
    op.create_index(
        op.f("ix_llm_extractor_version_state_code"),
        "llm_extractor_version",
        ["state_code"],
        unique=False,
    )
    op.create_table(
        "llm_extraction_cap_override",
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("extractor_version_id", sa.String(length=255), nullable=False),
        sa.Column("document_filter_id", sa.String(length=255), nullable=False),
        sa.Column("override_document_count_cap", sa.Integer(), nullable=False),
        sa.Column("expires_datetime_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "row_creation_datetime_utc", sa.DateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["state_code", "extractor_version_id"],
            [
                "llm_extractor_version.state_code",
                "llm_extractor_version.extractor_version_id",
            ],
            name="llm_extraction_cap_override_extractor_version_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "state_code", "extractor_version_id", "document_filter_id"
        ),
    )
    op.create_index(
        op.f("ix_llm_extraction_cap_override_state_code"),
        "llm_extraction_cap_override",
        ["state_code"],
        unique=False,
    )
    op.create_table(
        "llm_extraction_eligible_document",
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("extractor_version_id", sa.String(length=255), nullable=False),
        sa.Column("document_filter_id", sa.String(length=255), nullable=False),
        sa.Column("document_contents_id", sa.String(length=255), nullable=False),
        sa.Column(
            "row_creation_datetime_utc", sa.DateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["state_code", "document_contents_id"],
            [
                "llm_extraction_eligible_document_metadata.state_code",
                "llm_extraction_eligible_document_metadata.document_contents_id",
            ],
            name="llm_extraction_eligible_document_metadata_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["state_code", "extractor_version_id"],
            [
                "llm_extractor_version.state_code",
                "llm_extractor_version.extractor_version_id",
            ],
            name="llm_extraction_eligible_document_version_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "state_code",
            "extractor_version_id",
            "document_filter_id",
            "document_contents_id",
        ),
    )
    op.create_index(
        op.f("ix_llm_extraction_eligible_document_state_code"),
        "llm_extraction_eligible_document",
        ["state_code"],
        unique=False,
    )
    op.create_table(
        "llm_extraction_job",
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("extractor_version_id", sa.String(length=255), nullable=False),
        sa.Column("start_datetime_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completion_datetime_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result_type",
            sa.Enum(
                "SUCCESS",
                "PARTIAL_FAILURE",
                "FAILURE",
                name="llm_extraction_job_result_type",
            ),
            nullable=True,
        ),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.CheckConstraint(
            "error_message IS NULL OR result_type = 'FAILURE'",
            name="llm_extraction_job_error_message_only_for_failure",
        ),
        sa.CheckConstraint(
            "(completion_datetime_utc IS NULL) = (result_type IS NULL)",
            name="llm_extraction_job_completion_and_result_type_consistent",
        ),
        sa.CheckConstraint(
            "completion_datetime_utc IS NULL OR start_datetime_utc IS NULL OR completion_datetime_utc >= start_datetime_utc",
            name="llm_extraction_job_completion_after_start",
        ),
        sa.CheckConstraint(
            "start_datetime_utc IS NOT NULL OR completion_datetime_utc IS NULL",
            name="llm_extraction_job_completion_requires_start",
        ),
        sa.ForeignKeyConstraint(
            ["state_code", "extractor_version_id"],
            [
                "llm_extractor_version.state_code",
                "llm_extractor_version.extractor_version_id",
            ],
            name="llm_extraction_job_extractor_version_fkey",
        ),
        sa.PrimaryKeyConstraint("state_code", "job_id"),
    )
    op.create_index(
        op.f("ix_llm_extraction_job_state_code"),
        "llm_extraction_job",
        ["state_code"],
        unique=False,
    )
    op.create_index(
        "one_open_llm_extraction_job_per_extractor_version",
        "llm_extraction_job",
        ["state_code", "extractor_version_id"],
        unique=True,
        postgresql_where=sa.text("completion_datetime_utc IS NULL"),
    )
    op.create_table(
        "llm_extraction_batch_job_metadata",
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("batch_index", sa.Integer(), nullable=False),
        sa.Column("external_job_id", sa.String(length=255), nullable=False),
        sa.Column("external_job_provider", sa.String(length=255), nullable=False),
        sa.Column("gcs_input_uri", sa.String(), nullable=False),
        sa.Column("gcs_output_uri", sa.String(), nullable=True),
        sa.Column(
            "row_creation_datetime_utc", sa.DateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["state_code", "job_id"],
            ["llm_extraction_job.state_code", "llm_extraction_job.job_id"],
            name="llm_extraction_batch_job_metadata_job_fkey",
        ),
        sa.PrimaryKeyConstraint("state_code", "job_id", "batch_index"),
    )
    op.create_index(
        op.f("ix_llm_extraction_batch_job_metadata_state_code"),
        "llm_extraction_batch_job_metadata",
        ["state_code"],
        unique=False,
    )
    op.create_table(
        "llm_extraction_job_document",
        sa.Column("state_code", sa.String(length=255), nullable=False),
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("document_contents_id", sa.String(length=255), nullable=False),
        sa.Column("batch_index", sa.Integer(), nullable=True),
        sa.Column("job_index", sa.Integer(), nullable=False),
        sa.Column("result_datetime_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result_type",
            sa.Enum(
                "SUCCESS",
                "JOB_LEVEL_FAILURE",
                "DOCUMENT_LEVEL_FAILURE_TRANSIENT",
                "DOCUMENT_LEVEL_FAILURE_PERMANENT",
                "DOCUMENT_LEVEL_FAILURE_RETRIES_EXHAUSTED",
                name="llm_extraction_job_document_result_type",
            ),
            nullable=True,
        ),
        sa.Column("is_relevant", sa.Boolean(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("input_token_count", sa.Integer(), nullable=True),
        sa.Column("output_token_count", sa.Integer(), nullable=True),
        sa.Column("cached_input_token_count", sa.Integer(), nullable=True),
        sa.Column("thinking_token_count", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(is_relevant IS NOT NULL) = (result_type IS NOT DISTINCT FROM 'SUCCESS')",
            name="llm_extraction_job_document_is_relevant_iff_success",
        ),
        sa.CheckConstraint(
            "error_message IS NULL OR result_type IN ('JOB_LEVEL_FAILURE','DOCUMENT_LEVEL_FAILURE_TRANSIENT','DOCUMENT_LEVEL_FAILURE_PERMANENT','DOCUMENT_LEVEL_FAILURE_RETRIES_EXHAUSTED')",
            name="llm_extraction_job_document_error_message_only_for_failure",
        ),
        sa.CheckConstraint(
            "(result_datetime_utc IS NULL) = (input_token_count IS NULL) AND (result_datetime_utc IS NULL) = (output_token_count IS NULL) AND (result_datetime_utc IS NULL) = (cached_input_token_count IS NULL) AND (result_datetime_utc IS NULL) = (thinking_token_count IS NULL)",
            name="llm_extraction_job_document_token_counts_iff_result_datetime",
        ),
        sa.CheckConstraint(
            "(result_datetime_utc IS NULL) = (result_type IS NULL)",
            name="llm_extraction_job_document_result_datetime_and_type_consistent",
        ),
        sa.CheckConstraint(
            "job_index >= 0", name="llm_extraction_job_document_nonnegative_job_index"
        ),
        sa.ForeignKeyConstraint(
            ["state_code", "job_id", "batch_index"],
            [
                "llm_extraction_batch_job_metadata.state_code",
                "llm_extraction_batch_job_metadata.job_id",
                "llm_extraction_batch_job_metadata.batch_index",
            ],
            name="llm_extraction_job_document_batch_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["state_code", "job_id"],
            ["llm_extraction_job.state_code", "llm_extraction_job.job_id"],
            name="llm_extraction_job_document_job_fkey",
        ),
        sa.PrimaryKeyConstraint("state_code", "job_id", "document_contents_id"),
        sa.UniqueConstraint(
            "state_code",
            "job_id",
            "batch_index",
            "job_index",
            name="llm_extraction_job_document_job_index_unique",
        ),
    )
    op.create_index(
        op.f("ix_llm_extraction_job_document_state_code"),
        "llm_extraction_job_document",
        ["state_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_llm_extraction_job_document_state_code"),
        table_name="llm_extraction_job_document",
    )
    op.drop_table("llm_extraction_job_document")
    op.drop_index(
        op.f("ix_llm_extraction_batch_job_metadata_state_code"),
        table_name="llm_extraction_batch_job_metadata",
    )
    op.drop_table("llm_extraction_batch_job_metadata")
    op.drop_index(
        "one_open_llm_extraction_job_per_extractor_version",
        table_name="llm_extraction_job",
        postgresql_where=sa.text("completion_datetime_utc IS NULL"),
    )
    op.drop_index(
        op.f("ix_llm_extraction_job_state_code"), table_name="llm_extraction_job"
    )
    op.drop_table("llm_extraction_job")
    op.drop_index(
        op.f("ix_llm_extraction_eligible_document_state_code"),
        table_name="llm_extraction_eligible_document",
    )
    op.drop_table("llm_extraction_eligible_document")
    op.drop_index(
        op.f("ix_llm_extraction_cap_override_state_code"),
        table_name="llm_extraction_cap_override",
    )
    op.drop_table("llm_extraction_cap_override")
    op.drop_index(
        op.f("ix_llm_extractor_version_state_code"),
        table_name="llm_extractor_version",
    )
    op.drop_table("llm_extractor_version")
    op.drop_index(
        op.f("ix_llm_extractor_document_filter_state_code"),
        table_name="llm_extractor_document_filter",
    )
    op.drop_table("llm_extractor_document_filter")
    op.drop_index(op.f("ix_llm_extractor_state_code"), table_name="llm_extractor")
    op.drop_table("llm_extractor")
    op.drop_table("llm_extractor_collection")
    op.drop_index(
        op.f("ix_llm_extraction_eligible_document_metadata_state_code"),
        table_name="llm_extraction_eligible_document_metadata",
    )
    op.drop_table("llm_extraction_eligible_document_metadata")
    postgresql.ENUM(
        name="llm_extraction_job_document_result_type",
    ).drop(op.get_bind())
    postgresql.ENUM(
        name="llm_extraction_job_result_type",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
