# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2025 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================
"""Lists views that are currently exempted from checks related to gender columns.
"""
from functools import cache

from recidiviz.big_query.big_query_address import BigQueryAddress
from recidiviz.calculator.query.state.views.reference.state_resident_population import (
    STATE_RESIDENT_POPULATION_VIEW_BUILDER,
)
from recidiviz.calculator.query.state.views.reference.state_resident_population_combined_race_ethnicity import (
    STATE_RESIDENT_POPULATION_COMBINED_RACE_ETHNICITY_VIEW_BUILDER,
)
from recidiviz.utils import metadata
from recidiviz.validation.views.state.incarceration_population_by_demographic_internal_comparison import (
    INCARCERATION_POPULATION_BY_DEMOGRAPHIC_INTERNAL_COMPARISON_VIEW_BUILDER,
)

# Views that have a "gender" column but are NOT part of metric exports.
# These should eventually be refactored to use "sex" instead of "gender".
# TODO(#50972): These exemptions should eventually all be removed once views are
#  migrated to read from sex instead of gender.
_KNOWN_NON_EXPORT_VIEWS_WITH_GENDER_COLUMN: dict[BigQueryAddress, str] = {
    # reference_views views
    STATE_RESIDENT_POPULATION_VIEW_BUILDER.address: "TODO(#50972): Migrate to use sex instead of gender",
    STATE_RESIDENT_POPULATION_COMBINED_RACE_ETHNICITY_VIEW_BUILDER.address: "TODO(#50972): Migrate to use sex instead of gender",
    # validation_views views
    INCARCERATION_POPULATION_BY_DEMOGRAPHIC_INTERNAL_COMPARISON_VIEW_BUILDER.address: "TODO(#50972): Migrate to use sex instead of gender",
    # The _errors view is auto-generated by the validation framework
    BigQueryAddress(
        dataset_id="validation_views",
        table_id="incarceration_population_by_demographic_internal_comparison_errors",
    ): "TODO(#50972): This is auto-generated - will be fixed when the base view is migrated",
}


@cache
def get_known_non_export_views_with_gender_column(
    # We require project_id as an argument so that we don't return incorrect cached
    # results when metadata.project_id() changes (e.g. in tests).
    project_id: str,
) -> set[BigQueryAddress]:
    """Returns the addresses of every deployed BQ view that has a column named
    "gender" but is NOT part of a metric export. Generally, we want views to use
    "sex" instead of "gender", but there are some views where this migration is
    still in progress.
    """
    if project_id != metadata.project_id():
        raise ValueError(
            f"Expected project_id [{project_id}] to match metadata.project_id() "
            f"[{metadata.project_id()}]"
        )
    return set(_KNOWN_NON_EXPORT_VIEWS_WITH_GENDER_COLUMN)
