# Configuration for which validations to run for region US_NV.

region_code: US_NV
# TODO(OBT-47666): Enable validations for US_NV.
dev_mode: True
exclusions: []
max_allowed_error_overrides: []
num_allowed_rows_overrides: []
