# pylint: skip-file
"""initial migration

Revision ID: b6a54a77e8ac
Revises: 
Create Date: 2024-05-03 10:20:55.824561

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6a54a77e8ac"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configurations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("feature_variant", sa.String(), nullable=True),
        sa.Column("supervision_officer_label", sa.String(), nullable=False),
        sa.Column("supervision_district_label", sa.String(), nullable=False),
        sa.Column("supervision_unit_label", sa.String(), nullable=False),
        sa.Column("supervision_supervisor_label", sa.String(), nullable=False),
        sa.Column("supervision_district_manager_label", sa.String(), nullable=False),
        sa.Column("supervision_jii_label", sa.String(), nullable=False),
        sa.Column("learn_more_url", sa.String(), nullable=False),
        sa.Column("none_are_outliers_label", sa.String(), nullable=False),
        sa.Column("worse_than_rate_label", sa.String(), nullable=False),
        sa.Column("exclusion_reason_description", sa.String(), nullable=False),
        sa.Column("slightly_worse_than_rate_label", sa.String(), nullable=False),
        sa.Column("at_or_below_rate_label", sa.String(), nullable=False),
        sa.Column(
            "absconders_label", sa.String(), server_default="absconders", nullable=False
        ),
        sa.Column(
            "at_or_above_rate_label",
            sa.String(),
            server_default="At or above statewide rate",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_metadata",
        sa.Column("pseudonymized_id", sa.String(), nullable=False),
        sa.Column("has_seen_onboarding", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("pseudonymized_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_metadata")
    op.drop_table("configurations")
    # ### end Alembic commands ###
