# pylint: skip-file
"""add vitals_metrics and vitals_metrics_methodology

Revision ID: f860175e1be8
Revises: d52e0c731843
Create Date: 2025-01-06 17:38:33.825949

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f860175e1be8"
down_revision = "d52e0c731843"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configurations",
        sa.Column(
            "vitals_metrics_methodology_url",
            sa.String(),
            nullable=False,
            server_default="https://www.recidiviz.org/",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configurations", "vitals_metrics_methodology_url")
    # ### end Alembic commands ###
