# pylint: skip-file
"""remove_doc_label

Revision ID: 7b9df9f7a755
Revises: f860175e1be8
Create Date: 2025-08-07 12:01:24.785945

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b9df9f7a755"
down_revision = "f860175e1be8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configurations", "doc_label")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configurations",
        sa.Column(
            "doc_label",
            sa.VARCHAR(),
            server_default=sa.text("'DOC'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
