# Configuration for which validations to run for region US_XX.

region_code: US_XX
# TODO(#XXXX): Enable validations for US_XX.
dev_mode: True
exclusions: []
max_allowed_error_overrides: []
num_allowed_rows_overrides: []
