# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2020 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================

resource "google_project_service" "bigquery_connection_api" {
  service = "bigqueryconnection.googleapis.com"

  disable_dependent_services = true
  disable_on_destroy         = true
}

# Storing validation results
module "validation_results_dataset" {
  source      = "./modules/big_query_dataset"
  dataset_id  = "validation_results"
  description = "This dataset contains raw results from data validation runs as well as any views over them."
}

# TODO(OBT-44639): remove this block once both projects have applied it.
# The validation_results table is now managed by the source-table framework as a protected
# table (see source_tables/yaml_managed/validation_results/). Deregister the Terraform table
# resource without destroying it, so the framework adopts the existing table in place.
removed {
  from = google_bigquery_table.validation_results
  lifecycle {
    destroy = false
  }
}

module "supplemental_generated_dataset" {
  source      = "./modules/big_query_dataset"
  dataset_id  = "supplemental_data"
  description = "This dataset contains tables with generated data that does not go through the traditional ingest and calc pipelines."
}

module "export_archives_dataset" {
  source      = "./modules/big_query_dataset"
  dataset_id  = "export_archives"
  description = "This dataset contains tables that archive the contents of daily exports."
}

module "eomis_writeback_metadata_dataset" {
  source      = "./modules/big_query_dataset"
  dataset_id  = "eomis_writeback_metadata"
  description = "Stores the append-only audit ledger for eOMIS writeback runs: run lifecycle events and per-candidate write events. Rows contain offender IDs."
}

module "twilio_webhook_requests_dataset" {
  source      = "./modules/big_query_dataset"
  dataset_id  = "twilio_webhook_requests"
  description = "This dataset contains tables that archive requests made by Twilio to Recidiviz resources."
}

module "raw_data_comparison_output" {
  source                      = "./modules/big_query_dataset"
  dataset_id                  = "raw_data_comparison_output"
  description                 = "This dataset contains tables that store the output of raw data comparisons generated by compare_raw_data.py."
  default_table_expiration_ms = 1000 * 60 * 60 * 24 * 7 # 7 days
}

# TODO(OBT-44639): remove this block once both projects have applied it.
# The jii_texting_incoming_messages table is now managed by the source-table framework as a
# protected table (see source_tables/yaml_managed/twilio_webhook_requests/). Deregister the
# Terraform table resource without destroying it, so the framework adopts the existing table
# in place.
removed {
  from = google_bigquery_table.jii_texting_incoming_messages
  lifecycle {
    destroy = false
  }
}
