# Configuration for which validations to run for region US_ME.

region_code: US_MI
dev_mode: False
exclusions: []
max_allowed_error_overrides:
  - validation_name: incarceration_population_by_facility_external_comparison
    hard_max_allowed_error_override: 1.0
    override_reason: Needs further investigation.
      There are some facilities in the external data that don't appear in our data.
      In some cases (like "GUI"), it's not an actual facility in the external data but a category of facilities.
      In other cases (like "JLS", "ZPF", "ZPM"), they're facilities that we don't consider as part of incarceration
      but further investigation is required to confirm that they are being excluded in our incarceration periods view.
      Lastly, there are also some mismatches for facilities that no longer exist ("IRM").
      As a note, MI has cautioned that the counts they have in the external data are also not entirely consistent.
  - validation_name: incarceration_population_by_state_by_date_justice_counts_comparison #TODO(#13513)
    hard_max_allowed_error_override: .125
    override_reason: Needs investigation; fails for years 2010-2013. #TODO(#13514)
  - validation_name: incarceration_population_person_level_external_comparison
    hard_max_allowed_error_override: .035
    override_reason: Needs investigation.  Current failing level as of 9/26 is .0302 #TODO(#13880)
  - validation_name: supervision_population_by_type_external_comparison
    hard_max_allowed_error_override: .11
    override_reason:
      Some error is expected because MI has told us that their validation numbers for suprevision have some weirdness.
      Hopefully we'll be able to get more reliable validation data for supervision population when we receive OTIS data.
      Some investigation is required however for the case where validations are producing different results in
      staging vs production.  Current failing level as of 2/10 is 9.74% in staging and 10.11% in production #TODO(#18578), TODO(#16338)
num_allowed_rows_overrides:
  - validation_name: admission_pfi_pop_pfi_mismatch
    hard_num_allowed_rows_override: 1500
    override_reason: Needs investigation.  Current failing level as of 9/26 is 1418 rows #TODO(#13882)
  - validation_name: incarceration_admission_after_open_period
    hard_num_allowed_rows_override: 50
    override_reason: Mostly fixed but needs investigation for remaining cases.
  - validation_name: incarceration_commitments_subset_of_admissions
    hard_num_allowed_rows_override: 4
    override_reason: Needs investigation. Current failing level as of 9/26 is 4 rows #TODO(#15586)
  - validation_name: overlapping_incarceration_periods
    hard_num_allowed_rows_override: 1000
    override_reason:
      Needs further investigation; there's a known issue with incarceration periods (#13336) that might be related?
      Current failing level as of 9/26 is 145071 rows #TODO(#13518)
  - validation_name: overlapping_supervision_periods
    hard_num_allowed_rows_override: 2500
    override_reason: Addressed known issue with overlapping offender bookings so remaining errors needs further investigation. #TODO(#15587)
  - validation_name: sentence_end_dates_before_start_dates
    hard_num_allowed_rows_override: 100000
    override_reason: Needs investigation.  Current failing level as of 10/21 is 56,669 rows #TODO(#16186)
  - validation_name: session_new_admissions_with_no_sentence_date_imposed
    hard_num_allowed_rows_override: 350000
    override_reason: Needs investigation.  Current failing level as of 10/26 is 326,285 rows #TODO(#16227)
  - validation_name: session_liberty_releases_with_no_sentence_completion_date
    hard_num_allowed_rows_override: 100000
    override_reason: Needs investigation.  Current failing level as of 10/26 is 69,392 rows #TODO(#16237)
  - validation_name: supervision_termination_reason_no_date
    hard_num_allowed_rows_override: 10
    override_reason: Needs investigation.  Current failing level as of 10/28 is 3 rows #TODO(#16337)
  - validation_name: sentences_missing_date_imposed
    hard_num_allowed_rows_override: 20
    override_reason: Needs investigation.  Current failing level as of 11/2 is 9 rows
  - validation_name: normalized_state_charge_missing_descriptions
    hard_num_allowed_rows_override: 50
    override_reason: Current failing level as of 4/5/23 is 0 rows
  - validation_name: normalized_state_charge_missing_uniform_offense_labels
    hard_num_allowed_rows_override: 50
    override_reason: Current failing level as of 4/5/23 is 0 rows
  - validation_name: sessions_missing_closest_sentence_imposed_group
    hard_num_allowed_rows_override: 13000
    override_reason: Current failing level as of 4/20/23 is 11,081 rows (0.6%)
