# Configuration for which validations to run for region US_ME.

region_code: US_MI
# TODO(#11850): Enable validations for US_MI.
dev_mode: True
exclusions: []
max_allowed_error_overrides: []
num_allowed_rows_overrides: []
