# Minimum age of a package version according to the publish date on the npm registry in minutes to be considered for installation.
# If a package version is newer than the minimal age gate, it will not be considered for installation.
# This can be used to reduce the likelihood of installing compromised packages.
# 72 hours = 4320 minutes
npmMinimalAgeGate: 4320
