"""
Snapshots for recidiviz/tests/admin_panel/routes/outliers_test.py
Update snapshots automatically by running `pytest recidiviz/tests/admin_panel/routes/outliers_test.py --snapshot-update
Remember to include a docstring like this after updating the snapshots for Pylint purposes
"""

# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot

snapshots = Snapshot()

snapshots[
    "OutliersAdminPanelEndpointTests.OutliersAdminPanelEndpointTests test_add_configuration"
] = [
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because x",
        "featureVariant": None,
        "id": 1,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "agent",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-26T13:30:00",
        "updatedBy": "alexa@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because a",
        "featureVariant": "fv2",
        "id": 4,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:03",
        "updatedBy": "dana2@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because z",
        "featureVariant": "fv1",
        "id": 3,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:02",
        "updatedBy": "dana1@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because y",
        "featureVariant": None,
        "id": 2,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:01",
        "updatedBy": "fake@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because b",
        "featureVariant": "fv2",
        "id": 5,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer-fv2",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:00:03",
        "updatedBy": "dana2@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
]

snapshots[
    "OutliersAdminPanelEndpointTests.OutliersAdminPanelEndpointTests test_add_configuration_with_updated_by"
] = [
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because x",
        "featureVariant": None,
        "id": 1,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "agent",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-26T13:30:00",
        "updatedBy": "alexa@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because a",
        "featureVariant": "fv2",
        "id": 4,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:03",
        "updatedBy": "dana2@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because z",
        "featureVariant": "fv1",
        "id": 3,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:02",
        "updatedBy": "dana1@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because y",
        "featureVariant": None,
        "id": 2,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:01",
        "updatedBy": "fake@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because b",
        "featureVariant": "fv2",
        "id": 5,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer-fv2",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:00:03",
        "updatedBy": "dana2@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
]

snapshots[
    "OutliersAdminPanelEndpointTests.OutliersAdminPanelEndpointTests test_get_configurations"
] = [
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because x",
        "featureVariant": None,
        "id": 1,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "agent",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-26T13:30:00",
        "updatedBy": "alexa@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because a",
        "featureVariant": "fv2",
        "id": 4,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:03",
        "updatedBy": "dana2@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because z",
        "featureVariant": "fv1",
        "id": 3,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:02",
        "updatedBy": "dana1@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because y",
        "featureVariant": None,
        "id": 2,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:01",
        "updatedBy": "fake@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because b",
        "featureVariant": "fv2",
        "id": 5,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer-fv2",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:00:03",
        "updatedBy": "dana2@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
]

snapshots[
    "OutliersAdminPanelEndpointTests.OutliersAdminPanelEndpointTests test_promote_default_configuration_success"
] = [
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because z",
        "featureVariant": None,
        "id": 6,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-02-01T00:00:00",
        "updatedBy": "test-user@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because x",
        "featureVariant": None,
        "id": 1,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "agent",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-26T13:30:00",
        "updatedBy": "alexa@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because a",
        "featureVariant": "fv2",
        "id": 4,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:03",
        "updatedBy": "dana2@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because z",
        "featureVariant": "fv1",
        "id": 3,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:02",
        "updatedBy": "dana1@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because y",
        "featureVariant": None,
        "id": 2,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:01",
        "updatedBy": "fake@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because b",
        "featureVariant": "fv2",
        "id": 5,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer-fv2",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:00:03",
        "updatedBy": "dana2@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
]

snapshots[
    "OutliersAdminPanelEndpointTests.OutliersAdminPanelEndpointTests test_reactivate_configuration_success"
] = [
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because b",
        "featureVariant": "fv2",
        "id": 6,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer-fv2",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-02-01T00:00:00",
        "updatedBy": "test-user@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because x",
        "featureVariant": None,
        "id": 1,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "agent",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-26T13:30:00",
        "updatedBy": "alexa@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because a",
        "featureVariant": "fv2",
        "id": 4,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:03",
        "updatedBy": "dana2@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because z",
        "featureVariant": "fv1",
        "id": 3,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "ACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:02",
        "updatedBy": "dana1@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because y",
        "featureVariant": None,
        "id": 2,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:30:01",
        "updatedBy": "fake@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
    {
        "abscondersLabel": "absconders",
        "atOrAboveRateLabel": "At or above statewide rate",
        "atOrBelowRateLabel": "At or below statewide rate",
        "docLabel": "DOC",
        "exclusionReasonDescription": "excluded because b",
        "featureVariant": "fv2",
        "id": 5,
        "learnMoreUrl": "fake.com",
        "noneAreOutliersLabel": "are outliers",
        "outliersHover": "Has a rate on any metric significantly higher than peers - over 1 Interquartile Range above the statewide rate.",
        "slightlyWorseThanRateLabel": "slightly worse than statewide rate",
        "status": "INACTIVE",
        "supervisionDistrictLabel": "district",
        "supervisionDistrictManagerLabel": "district manager",
        "supervisionJiiLabel": "client",
        "supervisionOfficerLabel": "officer-fv2",
        "supervisionSupervisorLabel": "supervisor",
        "supervisionUnitLabel": "unit",
        "updatedAt": "2024-01-01T13:00:03",
        "updatedBy": "dana2@recidiviz.org",
        "worseThanRateLabel": "Far worse than statewide rate",
    },
]
