# Infrastructure configuration for components that will be deployed to the recidiviz-staging

import:
  - ../../catalogs/terraform-backend # Import Terraform backend configuration
  - ../../catalogs/organization-settings # Import billing_account and organization_id `settings.context`

# The variables set here are automatically provided to any components used in this stack.
settings:
  context:
    project_id: recidiviz-staging
    location: us-central1

components:
  terraform:
    apps/resource-search:
      vars:
        location: "{{ .settings.context.location }}"
        project_id: "{{ .settings.context.project_id }}"
        sql_instance_name: "resource-search-staging"
        is_backup_enabled: false
        big_query_instance_name: "resource_search_staging"
        big_query_instance_friendly_name: "Resource Search Data (Staging)"
        big_query_instance_description: "Staging dataset for Recidiviz Resource Search application data. Used for testing and development purposes. Do NOT use for production queries or applications."
