# Infrastructure configuration for components that will be deployed to the recidiviz-staging

import:
  - ../../catalogs/terraform-backend # Import Terraform backend configuration
  - ../../catalogs/organization-settings # Import billing_account and organization_id `settings.context`

settings:
  context:
    project_id: recidiviz-123
    location: us-central1

components:
  terraform:
    apps/resource-search:
      vars:
        location: "{{ .settings.context.location }}"
        project_id: "{{ .settings.context.project_id }}"
        sql_instance_name: "prod-resource-search-data"
        is_backup_enabled: true
        big_query_instance_name: "resource_search_production"
        big_query_instance_friendly_name: "Resource Search Data (Production)"
        big_query_instance_description: "Production dataset for Recidiviz Resource Search application data."
        service_account_id: "resource-search-prod"
        tables:
          - "resource"
          - "resource_score"
        postgresql:
          databases:
            - us_id
            - us_az
            - us_ut
