# pylint: skip-file
"""add_status_to_configurations

Revision ID: 0612f7babd60
Revises: a6f42c3dcefb
Create Date: 2024-01-26 15:41:00.401224

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0612f7babd60"
down_revision = "a6f42c3dcefb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("configurations", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configurations", "status")
    # ### end Alembic commands ###
