# pylint: skip-file
"""add_at_or_above_rate_label_with_default

Revision ID: f5050f03618f
Revises: bfa8c7659846
Create Date: 2024-04-05 11:39:34.016815

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5050f03618f"
down_revision = "bfa8c7659846"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "configurations",
        sa.Column(
            "at_or_above_rate_label",
            sa.String(),
            server_default="At or above statewide rate",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("configurations", "at_or_above_rate_label")
    # ### end Alembic commands ###
