# This file is used to manually trigger and submit a build from the run_sandbox_flex_calculation_pipeline script
# It builds a Docker image using the Dockerfile recidiviz/pipelines/Dockerfile.pipeline,
# and specifies it to be pushed to the provided _IMAGE_PATH.

steps:
  - name: "gcr.io/kaniko-project/executor:v1.8.1"
    args:
      - --destination=${_IMAGE_PATH}
      - --cache=true
      - --dockerfile=recidiviz/pipelines/Dockerfile.pipelines
      # For unknown reasons, Cloud Build does not respect these arguments in the format of `--build-arg=""`
      - --build-arg
      - GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}
      - --build-arg
      - RECIDIVIZ_ENV=${_RECIDIVIZ_ENV}
