# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2019 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================
"""A static reference cache for converting raw incoming codes into normalized
county codes."""
from typing import Dict

# TODO(2605): Do all county code mappings for MO
COUNTY_CODES: Dict[str, str] = {
    'ADAI': 'US_MO_*',
    'ANDR': 'US_MO_*',
    'ATCH': 'US_MO_*',
    'AUDR': 'US_MO_*',
    'BARR': 'US_MO_*',
    'BART': 'US_MO_*',
    'BATE': 'US_MO_*',
    'BENT': 'US_MO_*',
    'BOLL': 'US_MO_*',
    'BOON': 'US_MO_*',
    'BUCH': 'US_MO_*',
    'BUTL': 'US_MO_*',
    'CALD': 'US_MO_*',
    'CALL': 'US_MO_*',
    'CAMD': 'US_MO_*',
    'CAPE': 'US_MO_*',
    'CARR': 'US_MO_*',
    'CART': 'US_MO_*',
    'CASS': 'US_MO_*',
    'CEDA': 'US_MO_*',
    'CHAR': 'US_MO_*',
    'CHRI': 'US_MO_*',
    'CLAR': 'US_MO_*',
    'CLAY': 'US_MO_*',
    'CLIN': 'US_MO_*',
    'COLE': 'US_MO_COLE',
    'COOP': 'US_MO_*',
    'CRAW': 'US_MO_*',
    'DADE': 'US_MO_*',
    'DALL': 'US_MO_*',
    'DAVI': 'US_MO_*',
    'DEKA': 'US_MO_*',
    'DENT': 'US_MO_*',
    'DOUG': 'US_MO_*',
    'DUNK': 'US_MO_*',
    'FRAN': 'US_MO_*',
    'GASC': 'US_MO_*',
    'GENT': 'US_MO_*',
    'GREE': 'US_MO_*',
    'GRUN': 'US_MO_*',
    'HARR': 'US_MO_*',
    'HENR': 'US_MO_*',
    'HICK': 'US_MO_*',
    'HOLT': 'US_MO_*',
    'HOWA': 'US_MO_*',
    'HOWE': 'US_MO_*',
    'IRON': 'US_MO_*',
    'JACK': 'US_MO_JACKSON',
    'JASP': 'US_MO_*',
    'JEFF': 'US_MO_*',
    'JOHN': 'US_MO_*',
    'KNOX': 'US_MO_*',
    'LACL': 'US_MO_*',
    'LAFA': 'US_MO_*',
    'LAWR': 'US_MO_*',
    'LEWI': 'US_MO_*',
    'LINC': 'US_MO_*',
    'LINN': 'US_MO_*',
    'LIVI': 'US_MO_*',
    'MACO': 'US_MO_*',
    'MADI': 'US_MO_*',
    'MARE': 'US_MO_*',
    'MARI': 'US_MO_*',
    'MCDO': 'US_MO_*',
    'MERC': 'US_MO_*',
    'MILL': 'US_MO_*',
    'MISS': 'US_MO_*',
    'MONI': 'US_MO_*',
    'MONR': 'US_MO_*',
    'MONT': 'US_MO_*',
    'MORG': 'US_MO_*',
    'NEWM': 'US_MO_*',
    'NEWT': 'US_MO_*',
    'NODA': 'US_MO_*',
    'OREG': 'US_MO_*',
    'OSAG': 'US_MO_*',
    'OTST': 'US_MO_*',
    'OZAR': 'US_MO_*',
    'PEMI': 'US_MO_*',
    'PERR': 'US_MO_*',
    'PETT': 'US_MO_*',
    'PHEL': 'US_MO_*',
    'PIKE': 'US_MO_PIKE',
    'PLAT': 'US_MO_*',
    'POLK': 'US_MO_*',
    'PULA': 'US_MO_*',
    'PUTN': 'US_MO_*',
    'RALL': 'US_MO_*',
    'RAND': 'US_MO_*',
    'RAY':  'US_MO_*',
    'REYN': 'US_MO_*',
    'RIPL': 'US_MO_*',
    'SALI': 'US_MO_*',
    'SCHU': 'US_MO_*',
    'SCOL': 'US_MO_*',
    'SCOT': 'US_MO_*',
    'SHAN': 'US_MO_*',
    'SHEL': 'US_MO_*',
    'STCH': 'US_MO_*',
    'STCL': 'US_MO_*',
    'STEG': 'US_MO_*',
    'STFR': 'US_MO_*',
    'STLC': 'US_MO_ST_LOUIS_COUNTY',
    'STLO': 'US_MO_ST_LOUIS_CITY',  # TODO(2605): Do we need to flip STLC/STLO?
    'STOD': 'US_MO_*',
    'STON': 'US_MO_*',
    'SULL': 'US_MO_*',
    'TANE': 'US_MO_*',
    'TEXA': 'US_MO_*',
    'VERN': 'US_MO_*',
    'WARR': 'US_MO_*',
    'WASH': 'US_MO_*',
    'WAYN': 'US_MO_*',
    'WEBS': 'US_MO_*',
    'WORT': 'US_MO_*',
    'WRIG': 'US_MO_*',
}
