# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2019 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================

"""Constants that correspond to the largely opaque column names from the
MODOC data warehouse."""

# Table prefixes
TAK076_PREFIX = 'CZ'
TAK291_PREFIX = 'JS'

# Field names
DOC_ID = 'DOC'
CYCLE_ID = 'CYC'
SENTENCE_KEY_SEQ = 'SEO'
FIELD_KEY_SEQ = 'FSO'
VIOLATION_KEY_SEQ = 'VSN'
CITATION_KEY_SEQ = 'CSQ'

# Columns (Table prefixes + field names)
STATE_ID = 'EK$SID'
FBI_ID = 'EK$FBI'
LICENSE_ID = 'EK$OLN'

CHARGE_COUNTY_CODE = 'BS$CNT'

SENTENCE_COUNTY_CODE = 'BS$CNS'
SENTENCE_OFFENSE_DATE = 'BS$DO'
SENTENCE_COMPLETED_FLAG = 'BS$SCF'
SENTENCE_STATUS_CODE = 'BW$SCD'

INCARCERATION_SENTENCE_LENGTH_YEARS = 'BT$SLY'
INCARCERATION_SENTENCE_LENGTH_MONTHS = 'BT$SLM'
INCARCERATION_SENTENCE_LENGTH_DAYS = 'BT$SLD'
INCARCERATION_SENTENCE_MIN_RELEASE_TYPE = 'BT$CRR'
INCARCERATION_SENTENCE_PAROLE_INELIGIBLE_YEARS = 'BT$PIE'
INCARCERATION_SENTENCE_START_DATE = 'BT$EM'
INCARCERATION_SENTENCE_PROJECTED_MIN_DATE = 'BT$PC'
INCARCERATION_SENTENCE_PROJECTED_MAX_DATE = 'BS$PD'

SUPERVISION_SENTENCE_LENGTH_YEARS = 'BU$SBY'
SUPERVISION_SENTENCE_LENGTH_MONTHS = 'BU$SBM'
SUPERVISION_SENTENCE_LENGTH_DAYS = 'BU$SBD'
SUPERVISION_SENTENCE_START_DATE = 'BU$SF'
SUPERVISION_SENTENCE_PROJECTED_COMPLETION_DATE = 'BS$PD'

PERIOD_OPEN_CODE = 'START_STATUS_CODE'
PERIOD_OPEN_CODE_SUBTYPE = 'START_STATUS_SUBTYPE'
PERIOD_CLOSE_CODE = 'END_STATUS_CODE'
PERIOD_CLOSE_CODE_SUBTYPE = 'END_STATUS_SUBTYPE'
PERIOD_START_DATE = 'SUB_SUBCYCLE_START_DT'
PERIOD_RELEASE_DATE = 'SUB_SUBCYCLE_END_DT'
PERIOD_PURPOSE_FOR_INCARCERATION = 'F1$PFI'
PERIOD_START_STATUSES = 'START_SCD_CODES'

SUPERVISION_VIOLATION_VIOLATED_CONDITIONS = 'VIOLATED_CONDITIONS'
SUPERVISION_VIOLATION_TYPES = 'BY$VTY'
SUPERVISION_VIOLATION_RECOMMENDATIONS = 'BY$VOR'

ORAS_ASSESSMENTS_DOC_ID = 'E03'
ORAS_ASSESSMENT_ID = 'FOCLIST'

# Recidiviz internal constants
VIOLATION_REPORT_ID_PREFIX = 'R'
CITATION_ID_PREFIX = 'C'
