# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2023 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================
"""Endpoints for Outliers utils endpoints."""
from http import HTTPStatus
from typing import Tuple

from flask import Blueprint, request

from recidiviz.metrics.export.export_config import INSIGHTS_VIEWS_OUTPUT_DIRECTORY_URI
from recidiviz.tools.archive import archive_etl_file
from recidiviz.utils.pubsub_helper import OBJECT_ID, extract_pubsub_message_from_json


def get_outliers_utils_blueprint() -> Blueprint:
    """Creates a Flask Blueprint for Outliers Utils routes."""
    outliers_utils_blueprint = Blueprint("outliers-utils", __name__)

    # This endpoint is triggered by a pub/sub subscription on the insights-etl-data GCS bucket.
    # To trigger it manually, run (substituting PROJECT_ID and FILENAME):
    # `gcloud pubsub topics publish storage-notification-$PROJECT_ID-insights-etl-data --attribute=objectId=$FILENAME`
    @outliers_utils_blueprint.route("/archive-file", methods=["POST"])
    def _archive_file() -> Tuple[str, HTTPStatus]:
        try:
            message = extract_pubsub_message_from_json(request.get_json())
        except Exception as e:
            return str(e), HTTPStatus.BAD_REQUEST

        if not message.attributes:
            return "Invalid Pub/Sub message", HTTPStatus.BAD_REQUEST

        attributes = message.attributes

        filename = attributes[OBJECT_ID]
        if filename is None:
            return "Missing filename", HTTPStatus.BAD_REQUEST

        # ignore temp files generated by export
        if not filename.startswith("staging"):
            archive_etl_file(filename, INSIGHTS_VIEWS_OUTPUT_DIRECTORY_URI)

        return "", HTTPStatus.OK

    return outliers_utils_blueprint
