# List of products with their required exports and statuses

products:
  - name: Admin Panel
    description: The admin panel is a Recidiviz-internal surface from which we can observe things about the operation of our system and take diagnostic or corrective actions. The admin panel is not under the purview of any one team, so any and all should feel free to make contributions or fix issues as they arise!
    is_state_agnostic: True
    exports:
      - INGEST_METADATA
      - VALIDATION_METADATA
    environment: production
  - name: Justice Counts
    description: The Justice Counts Data Dashboards are designed to keep policymakers and other actors in the CJ arena informed of basic trends on the corrections systems in all fifty states.
    is_state_agnostic: True
    exports:
      - JUSTICE_COUNTS
    environment: production
  - name: Lantern Dashboard
    description: Lantern is a dashboard for leadership and supervisors to understand the patterns and behaviors associated with revocations. Users can see over-time revocation trends, the violation history leading up to revocation, demographic and geographic breakdowns of revocations, and individual lists of people who were revoked.
    exports:
      - LANTERN
    states:
      - state_code: US_MO
        environment: production
      - state_code: US_PA
        environment: production
  - name: Dashboard User Restrictions
    description: User restrictions for the UP dashboard, including Lantern and Case Triage.
    exports:
      - DASHBOARD_USER_RESTRICTIONS
    states:
      - state_code: US_CO
        environment: production
      - state_code: US_ID
        environment: production
      - state_code: US_ME
        environment: production
      - state_code: US_MI
        environment: production
      - state_code: US_MO
        environment: production
      - state_code: US_ND
        environment: production
      - state_code: US_TN
        environment: production
  - name: Overdue Discharge Alert
    description: Email reports sent to parole and probation officers to motivate progress toward discharging clients from supervision
    exports:
      - OVERDUE_DISCHARGE
    states:
      # TODO(#16465): Turn this back on in production
      - state_code: US_IX
        environment: staging
      - state_code: US_PA
        environment: production
  - name: PO Report
    description: Monthly Email Reports are sent regularly to parole and probation officers (line staff) to track and motivate progress towards improving client outcomes.
    exports:
      - PO_MONTHLY
    states:
      # TODO(#16465): Turn this back on in production
      - state_code: US_IX
        environment: staging
      - state_code: US_PA
        environment: staging
      - state_code: US_MO
        environment: staging
  - name: Product User Import
    description: Potential users of Polaris tools that we receive via ingest, to be imported into the Polaris Roster Postgres table
    exports:
      - PRODUCT_USER_IMPORT
    states:
      - state_code: US_MO
        environment: production
      - state_code: US_ND
        environment: production
  - name: Public Dashboard
    description: The Public Dashboard (Spotlight) is a public data portal designed to make criminal justice data more accessible to public stakeholders. It accomplishes this through a series of interactive data visualizations on key metrics (such as populations or admission reasons) and holistic, data-driven narratives on what's happening in the system as a whole.
    exports:
      - PUBLIC_DASHBOARD
    states:
      - state_code: US_IX
        environment: staging
      - state_code: US_ME
        environment: staging
      - state_code: US_ND
        environment: production
      - state_code: US_PA
        environment: production
      - state_code: US_TN
        environment: staging
  - name: Vitals
    description: Vitals provides a snapshot of agency performance on a set of key operational metrics, which can be drilled down by geographic region and officer. This helps community supervision leadership and supervisors proactively identify resource constraints as well as opportunities for improvement in both compliance and policy.
    exports:
      - VITALS
    states:
      - state_code: US_IX
        environment: production
      - state_code: US_ND
        environment: production
  - name: Pathways
    description: Prison and Supervision populations and transitions over time which can be drilled down by geographic region, demographic categories, time period, etc. Also see PATHWAYS_AND_PROJECTIONS and PATHWAYS_PRISON for variations on the Pathways exports..
    exports:
      - PATHWAYS
      - PATHWAYS_EVENT_LEVEL
    states:
      - state_code: US_ND
        environment: production
      - state_code: US_TN
        environment: production
      - state_code: US_ME
        environment: production
      - state_code: US_MO
        environment: production
      - state_code: US_IX
        environment: production
  - name: Pathways Prison Module
    description: Prison populations over time which can be drilled down by geographic region, demographic categories, time period, etc.
    exports:
      - PATHWAYS_PRISON
      - PATHWAYS_PRISON_EVENT_LEVEL
    states:
      - state_code: US_MI
        environment: production
      - state_code: US_CO
        environment: production
  # TODO(#16465): Turn this back on in production
  # TODO(#17733): Turn this back on (and remove US_IX from PATHWAYS) once projection has been run for US_IX
  # - name: Pathways With Population Projections
  #   description: Prison and Supervision populations and transitions over time including prison and supervsion population projections. Also see PATHWAYS for Pathways exports that do not include projections.
  #   exports:
  #     - PATHWAYS_AND_PROJECTIONS
  #     - PATHWAYS_AND_PROJECTIONS_EVENT_LEVEL
  #   states:
  #       - state_code: US_IX
  #         environment: staging
  - name: Workflows
    description: Workflows is a collection of data and tools that help POs and supervisors provide services to their clients and hold themselves accountable.
    exports:
      - WORKFLOWS_FIRESTORE
    states:
      - state_code: US_TN
        environment: production
      - state_code: US_ND
        environment: production
      - state_code: US_ME
        environment: production
      - state_code: US_IX
        environment: production
      - state_code: US_MO
        environment: production
      - state_code: US_MI
        environment: production
  - name: Outliers
    description: Outliers is a state-agnostic product offering for staff performance and accountability.
    exports:
      - OUTLIERS
    states:
      - state_code: US_PA
        environment: production
      - state_code: US_IX
        environment: production
  - name: IMPACT
    description: Impact is a tracking product web tool to share impact metrics with partners.
    exports:
      - IMPACT
    states:
      - state_code: US_TN
        environment: staging
