# This file is used to manually trigger and submit a build from the command line.
# It builds a docker image with tag "us-docker.pkg.dev/recidiviz-staging/pipelines/recidiviz-pipelines:latest" using the provided Dockerfile recidiviz/calculator/pipeline/Dockerfile.pipeline,
# and specifies it to be pushed to cloud build to us-docker.pkg.dev/recidiviz-staging/pipelines/recidiviz-pipelines:latest.
# This flow is only used while developing and is triggered manually (not through the regular deploy flow in terraform)
# Example usage:
# gcloud builds submit --project=recidiviz-staging --config recidiviz/calculator/pipeline/cloudbuild.pipelines.yaml
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-docker.pkg.dev/recidiviz-staging/pipelines/recidiviz-pipelines:latest",
        "-f",
        "recidiviz/calculator/pipeline/Dockerfile.pipelines",
        ".",
      ]
images:
  - "us-docker.pkg.dev/recidiviz-staging/pipelines/recidiviz-pipelines:latest"
