# Details of production-ready pipeline jobs to deploy to templates. These templates will be deployed both to staging and
# production buckets.
#
#  If you want to deploy a pipeline just to stage, add it to staging_only_calculation_pipeline_templates.yaml

# Number of pipelines to deploy
pipeline_count: 8

# List of pipelines with their necessary details
pipelines:
# Full US_ND calculations with no time limit
  - pipeline: supervision
    job_name: full-us-nd-supervision-calculations
    input: state
    reference_input: reference_tables
    output: dataflow_metrics
    state_code: US_ND
    calculation_month_limit: -1 # No limit
    # metric_types must be the last in this list
    metric_types: POPULATION REVOCATION SUCCESS ASSESSMENT_CHANGE
  - pipeline: recidivism
    job_name: full-us-nd-recidivism-calculations
    input: state
    reference_input: reference_tables
    output: dataflow_metrics
    state_code: US_ND
    calculation_month_limit: -1 # No limit
  - pipeline: incarceration
    job_name: full-us-nd-incarceration-calculations
    input: state
    reference_input: reference_tables
    output: dataflow_metrics
    state_code: US_ND
    calculation_month_limit: -1 # No limit
  - pipeline: program
    job_name: full-us-nd-program-calculations
    input: state
    reference_input: reference_tables
    output: dataflow_metrics
    state_code: US_ND
    calculation_month_limit: -1 # No limit
# Daily US_ND calculations for the 36-mo dashboard
  - pipeline: supervision
    job_name: us-nd-supervision-calculations-36
    input: state
    reference_input: reference_tables
    output: dataflow_metrics
    state_code: US_ND
    calculation_month_limit: 36
    # metric_types must be the last in this list
    metric_types: POPULATION REVOCATION SUCCESS ASSESSMENT_CHANGE
  - pipeline: incarceration
    job_name: us-nd-incarceration-calculations-36
    input: state
    reference_input: reference_tables
    output: dataflow_metrics
    state_code: US_ND
    calculation_month_limit: 36
  - pipeline: program
    job_name: us-nd-program-calculations-36
    input: state
    reference_input: reference_tables
    output: dataflow_metrics
    state_code: US_ND
    calculation_month_limit: 36
# Daily US_MO calculations for the dashboard
  - pipeline: supervision
    job_name: us-mo-supervision-calculations-36
    input: state
    reference_input: reference_tables
    output: dataflow_metrics
    state_code: US_MO
    calculation_month_limit: 36
    # metric_types must be the last in this list
    metric_types: POPULATION REVOCATION_ANALYSIS REVOCATION_VIOLATION_TYPE_ANALYSIS
