# Details of production-ready pipeline jobs to deploy to templates. These templates will be deployed both to staging and
# production buckets.
#
#  If you want to deploy a pipeline just to stage, add it to staging_only_calculation_pipeline_templates.yaml

# List of pipelines with their necessary details

daily_pipelines:
  # Full US_ND calculations with no time limit
  - pipeline: recidivism
    job_name: full-us-nd-recidivism-calculations
    state_code: US_ND
    metric_types: REINCARCERATION_COUNT REINCARCERATION_RATE
    region: us-west1

  # Daily US_ND calculations
  - pipeline: supervision
    job_name: us-nd-supervision-calculations-36
    state_code: US_ND
    calculation_month_count: 36
    metric_types: SUPERVISION_POPULATION SUPERVISION_SUCCESS SUPERVISION_TERMINATION SUPERVISION_COMPLIANCE
    region: us-east1
  - pipeline: incarceration
    job_name: us-nd-incarceration-calculations-36
    state_code: US_ND
    metric_types: INCARCERATION_ADMISSION INCARCERATION_COMMITMENT_FROM_SUPERVISION INCARCERATION_POPULATION INCARCERATION_RELEASE
    calculation_month_count: 36
    region: us-central1
  - pipeline: program
    job_name: us-nd-program-calculations-36
    state_code: US_ND
    calculation_month_count: 36
    metric_types: PROGRAM_PARTICIPATION PROGRAM_REFERRAL
    region: us-west1

  # Daily US_MO calculations
  - pipeline: supervision
    job_name: us-mo-supervision-calculations-36
    state_code: US_MO
    calculation_month_count: 36
    metric_types: SUPERVISION_POPULATION SUPERVISION_TERMINATION
    region: us-west3
  - pipeline: incarceration
    job_name: us-mo-incarceration-calculations-36
    state_code: US_MO
    calculation_month_count: 36
    metric_types: INCARCERATION_ADMISSION INCARCERATION_COMMITMENT_FROM_SUPERVISION INCARCERATION_POPULATION INCARCERATION_RELEASE
    region: us-east1
  - pipeline: violation
    job_name: us-mo-violation-calculations-36
    state_code: US_MO
    calculation_month_count: 36
    metric_types: VIOLATION
    region: us-central1

  # Daily US_ID calculations
  - pipeline: supervision
    job_name: us-id-supervision-calculations-36
    state_code: US_ID
    calculation_month_count: 36
    metric_types: SUPERVISION_POPULATION SUPERVISION_OUT_OF_STATE_POPULATION SUPERVISION_COMPLIANCE SUPERVISION_TERMINATION SUPERVISION_START SUPERVISION_DOWNGRADE
    region: us-central1
  - pipeline: incarceration
    job_name: us-id-incarceration-calculations-36
    state_code: US_ID
    calculation_month_count: 36
    metric_types: INCARCERATION_ADMISSION INCARCERATION_COMMITMENT_FROM_SUPERVISION INCARCERATION_POPULATION INCARCERATION_RELEASE
    region: us-west3
  - pipeline: violation
    job_name: us-id-violation-calculations-36
    state_code: US_ID
    calculation_month_count: 36
    metric_types: VIOLATION
    region: us-west3

  # Daily US_PA calculations
  - pipeline: supervision
    job_name: us-pa-supervision-calculations-36
    state_code: US_PA
    calculation_month_count: 36
    metric_types: SUPERVISION_POPULATION SUPERVISION_SUCCESS SUPERVISION_TERMINATION SUPERVISION_OUT_OF_STATE_POPULATION SUPERVISION_COMPLIANCE SUPERVISION_START SUPERVISION_DOWNGRADE
    region: us-west1
  - pipeline: incarceration
    job_name: us-pa-incarceration-calculations-36
    state_code: US_PA
    calculation_month_count: 36
    metric_types: INCARCERATION_COMMITMENT_FROM_SUPERVISION
    region: us-east1
  - pipeline: violation
    job_name: us-pa-violation-calculations-36
    state_code: US_PA
    calculation_month_count: 36
    metric_types: VIOLATION
    region: us-east1

historical_pipelines:
  - pipeline: incarceration
    job_name: us-id-historical-incarceration-calculations-240
    state_code: US_ID
    calculation_month_count: 240
    metric_types: INCARCERATION_ADMISSION INCARCERATION_COMMITMENT_FROM_SUPERVISION INCARCERATION_POPULATION INCARCERATION_RELEASE
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-west1
  - pipeline: supervision
    job_name: us-id-historical-supervision-calculations-240
    state_code: US_ID
    calculation_month_count: 240
    metric_types: SUPERVISION_POPULATION SUPERVISION_START SUPERVISION_TERMINATION SUPERVISION_OUT_OF_STATE_POPULATION
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-west1
  - pipeline: violation
    job_name: us-id-historical-violation-calculations-240
    state_code: US_ID
    calculation_month_count: 240
    metric_types: VIOLATION
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-west1
  - pipeline: incarceration
    job_name: us-mo-historical-incarceration-calculations-240
    state_code: US_MO
    calculation_month_count: 240
    metric_types: INCARCERATION_ADMISSION INCARCERATION_COMMITMENT_FROM_SUPERVISION INCARCERATION_POPULATION INCARCERATION_RELEASE
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-west3
  - pipeline: supervision
    job_name: us-mo-historical-supervision-calculations-240
    state_code: US_MO
    calculation_month_count: 240
    metric_types: SUPERVISION_POPULATION SUPERVISION_START SUPERVISION_TERMINATION SUPERVISION_OUT_OF_STATE_POPULATION
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-west3
  - pipeline: violation
    job_name: us-mo-historical-violation-calculations-240
    state_code: US_MO
    calculation_month_count: 240
    metric_types: VIOLATION
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-west3
  - pipeline: incarceration
    job_name: us-nd-historical-incarceration-calculations-240
    state_code: US_ND
    calculation_month_count: 240
    metric_types: INCARCERATION_ADMISSION INCARCERATION_COMMITMENT_FROM_SUPERVISION INCARCERATION_POPULATION INCARCERATION_RELEASE
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-east1
  - pipeline: supervision
    job_name: us-nd-historical-supervision-calculations-240
    state_code: US_ND
    calculation_month_count: 240
    metric_types: SUPERVISION_POPULATION SUPERVISION_START SUPERVISION_TERMINATION
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-east1
  - pipeline: incarceration
    job_name: us-pa-historical-incarceration-calculations-240
    state_code: US_PA
    calculation_month_count: 240
    metric_types: INCARCERATION_ADMISSION INCARCERATION_COMMITMENT_FROM_SUPERVISION INCARCERATION_POPULATION INCARCERATION_RELEASE
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-central1
  - pipeline: supervision
    job_name: us-pa-historical-supervision-calculations-240
    state_code: US_PA
    calculation_month_count: 240
    metric_types: SUPERVISION_POPULATION SUPERVISION_START SUPERVISION_TERMINATION SUPERVISION_OUT_OF_STATE_POPULATION
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-central1
  - pipeline: violation
    job_name: us-pa-historical-violation-calculations-240
    state_code: US_PA
    calculation_month_count: 240
    metric_types: VIOLATION
    # This region value must stay in-sync with the REGION arg in the
    # historical-pipelines.tf config for this pipeline
    region: us-central1
