# Details of production-ready pipeline jobs to deploy to templates. These templates will be deployed both to staging and
# production buckets.
#
#  If you want to deploy a pipeline just to stage, add it to staging_only_calculation_pipeline_templates.yaml

# Number of pipelines to deploy
pipeline_count: 7

# List of pipelines with their necessary details
pipelines:
  - pipeline: recidivism
    job_name: full-recidivism-calculations
    input: state
    # TODO(2821): Move to reference dataset
    reference_input: dashboard_views
    output: dataflow_metrics
  - pipeline: incarceration
    job_name: full-incarceration-calculations
    input: state
    reference_input: dashboard_views
    output: dataflow_metrics
  # TODO(2822): Once we have fixed memory issues so we can run the whole supervision pipeline at once, collapse all
  #   these supervision pipelines into one with no metric_type or state_code filters, and update the cloud functions
  #   to only trigger a single supervision pipeline.
  - pipeline: supervision
    job_name: supervision-assessment-change-us-nd-calculations
    input: state
    # TODO(2821): Move to reference dataset
    reference_input: dashboard_views
    output: dataflow_metrics
    metric_type: ASSESSMENT_CHANGE
    state_code: US_ND
  - pipeline: supervision
    job_name: supervision-population-us-nd-calculations
    input: state
    # TODO(2821): Move to reference dataset
    reference_input: dashboard_views
    output: dataflow_metrics
    metric_type: POPULATION
    state_code: US_ND
  - pipeline: supervision
    job_name: supervision-revocation-us-nd-calculations
    input: state
    # TODO(2821): Move to reference dataset
    reference_input: dashboard_views
    output: dataflow_metrics
    metric_type: REVOCATION
    state_code: US_ND
  - pipeline: supervision
    job_name: supervision-success-us-nd-calculations
    input: state
    # TODO(2821): Move to reference dataset
    reference_input: dashboard_views
    output: dataflow_metrics
    metric_type: SUCCESS
    state_code: US_ND
  - pipeline: program
    job_name: full-program-calculations
    input: state
    # TODO(2821): Move to reference dataset
    reference_input: dashboard_views
    output: dataflow_metrics
