# Details of production-ready pipeline jobs to deploy to templates. These templates will be deployed both to staging and
# production buckets.
#
#  If you want to deploy a pipeline just to stage, add it to staging_only_calculation_pipeline_templates.yaml

# List of pipelines with their necessary details

daily_pipelines:
  # Full US_ND calculations with no time limit
  - pipeline: recidivism
    job_name: full-us-nd-recidivism-calculations
    state_code: US_ND
    region: us-west1

  # Daily US_ND calculations for the dashboards
  - pipeline: supervision
    job_name: us-nd-supervision-calculations-36
    state_code: US_ND
    calculation_month_count: 36
    metric_types: SUPERVISION_POPULATION SUPERVISION_REVOCATION SUPERVISION_SUCCESS SUPERVISION_TERMINATION SUPERVISION_COMPLIANCE
    region: us-east1
  - pipeline: incarceration
    job_name: us-nd-incarceration-calculations-36
    state_code: US_ND
    calculation_month_count: 36
    region: us-central1
  - pipeline: program
    job_name: us-nd-program-calculations-36
    state_code: US_ND
    calculation_month_count: 36
    region: us-west3


  # Daily US_MO calculations for the dashboard
  - pipeline: supervision
    job_name: us-mo-supervision-calculations-36
    state_code: US_MO
    calculation_month_count: 36
    metric_types: SUPERVISION_POPULATION SUPERVISION_REVOCATION_ANALYSIS SUPERVISION_TERMINATION
    region: us-west1

  # Daily US_MO calculations for automated data validation not covered by daily calculation runs
  - pipeline: incarceration
    job_name: us-mo-incarceration-validation-calculations
    state_code: US_MO
    calculation_end_month: 2019-12
    calculation_month_count: 1
    metric_types: INCARCERATION_POPULATION
    region: us-east1

  # Daily US_ID supervision calculations for the COVID and PO reports
  - pipeline: supervision
    job_name: us-id-supervision-calculations-24
    state_code: US_ID
    calculation_month_count: 24
    metric_types: SUPERVISION_POPULATION SUPERVISION_OUT_OF_STATE_POPULATION SUPERVISION_REVOCATION SUPERVISION_REVOCATION_ANALYSIS SUPERVISION_COMPLIANCE SUPERVISION_TERMINATION SUPERVISION_START SUPERVISION_DOWNGRADE
    region: us-central1

  # Daily US_ID incarceration calculations for the COVID report
  - pipeline: incarceration
    job_name: us-id-incarceration-calculations-24
    state_code: US_ID
    calculation_month_count: 24
    region: us-west3

  # Daily US_PA calculations for the dashboard
  - pipeline: supervision
    job_name: us-pa-supervision-calculations-36
    state_code: US_PA
    calculation_month_count: 36
    metric_types: SUPERVISION_POPULATION SUPERVISION_REVOCATION_ANALYSIS SUPERVISION_TERMINATION
    region: us-west1

  # Daily US_PA calculations for automated data validation not covered by daily calculation runs
  - pipeline: incarceration
    job_name: us-pa-incarceration-validation-calculations
    state_code: US_PA
    calculation_end_month: 2020-05
    calculation_month_count: 6
    metric_types: INCARCERATION_POPULATION
    region: us-east1

# Historical US_ND population calculations for the dashboards
historical_pipelines:
  - pipeline: supervision
    job_name: us-nd-supervision-population-240
    state_code: US_ND
    calculation_month_count: 240
    metric_types: SUPERVISION_POPULATION
    region: us-central1
  - pipeline: incarceration
    job_name: us-nd-incarceration-population-240
    state_code: US_ND
    calculation_month_count: 240
    metric_types: INCARCERATION_POPULATION
    region: us-west3
