# Details of production-ready pipeline jobs to deploy to templates. These templates will be deployed both to staging and
# production buckets.
#
#  If you want to deploy a pipeline just to stage, add it to staging_only_calculation_pipeline_templates.yaml

# Number of pipelines to deploy
pipeline_count: 4

# List of pipelines with their necessary details
pipelines:
  - pipeline: recidivism
    job_name: full-recidivism-calculations
    input: state
    # TODO(2821): Move to reference dataset
    reference_input: dashboard_views
    output: dataflow_metrics
  - pipeline: incarceration
    job_name: full-incarceration-calculations
    input: state
    reference_input: dashboard_views
    output: dataflow_metrics
  - pipeline: supervision
    job_name: full-supervision-calculations
    input: state
    # TODO(2821): Move to reference dataset
    reference_input: dashboard_views
    output: dataflow_metrics
  - pipeline: program
    job_name: full-program-calculations
    input: state
    # TODO(2821): Move to reference dataset
    reference_input: dashboard_views
    output: dataflow_metrics
