# Details of pipeline jobs to deploy to templates that are only ready for stage deployment. These templates will not be
# deployed to prod.
#
#  If you want to deploy a pipeline just to production, add it to prod_calculation_pipeline_templates.yaml

# Number of pipelines to deploy
pipeline_count: 1

# List of pipelines with their necessary details
pipelines:
# Daily US_MO calculations for the dashboard
  - pipeline: supervision
    job_name: us-mo-supervision-calculations-1
    input: state
    # TODO(2821): Move to reference dataset
    reference_input: dashboard_views
    output: dataflow_metrics
    state_code: US_MO
    calculation_month_limit: 1
    # metric_types must be the last in this list
    metric_types: POPULATION REVOCATION_ANALYSIS REVOCATION_VIOLATION_TYPE_ANALYSIS
