# Configuration file for the Build-JC trigger in justice-counts-staging.
# Builds a Docker image containing both JC Publisher and Agency Dashboard.
steps:
  - name: "gcr.io/kaniko-project/executor:v1.8.1"
    args:
      - "--dockerfile=Dockerfile.recidiviz-base"
      - "--cache=true"
      - >-
        --destination=us-central1-docker.pkg.dev/justice-counts-staging/recidiviz-base-images/recidiviz-base:latest
    id: recidiviz-base
  - name: "gcr.io/kaniko-project/executor:v1.8.1"
    args:
      - "--dockerfile=Dockerfile.justice-counts"
      - >-
        --destination=us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/$_SUBDIRECTORY:$COMMIT_SHA
      - "--build-arg"
      - FRONTEND_URL=$_FRONTEND_URL
    waitFor:
      - recidiviz-base
timeout: 3600s
options:
  machineType: N1_HIGHCPU_32
