# Configuration file for the Continuous-Staging-Deploy trigger in justice-counts-staging.
# This trigger is responsible for deploying the justice-counts image to Cloud Run for
# publisher and agency-dashboard. This trigger is designed only to be called by the
# Github Action Continuous Deployment script.
steps:
  # Build the recidiviz-base image and push it to Artifact Registry.
  - name: "gcr.io/kaniko-project/executor:v1.8.1"
    args:
      - "--dockerfile=Dockerfile.recidiviz-base"
      - "--cache=true"
      - >-
        --destination=us-central1-docker.pkg.dev/justice-counts-staging/recidiviz-base-images/recidiviz-base:latest
    id: recidiviz-base
  # Build the justice-counts image and push it to Artifact Registry.
  - name: "gcr.io/kaniko-project/executor:v1.8.1"
    args:
      - "--dockerfile=Dockerfile.justice-counts"
      - >-
        --destination=us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/$_SUBDIRECTORY:$COMMIT_SHA
      - "--build-arg"
      - FRONTEND_URL=$_FRONTEND_URL
    id: build-justice-counts-image
    waitFor:
      - recidiviz-base
  # Tag the image as latest.
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud artifacts docker tags add "us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$COMMIT_SHA" "us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:latest"
    id: tag-as-latest
    waitFor:
      - build-justice-counts-image
  # Tag the Docker image with the git commit version tag. The $TAG_NAME environment
  # variable is auto-populated when the Continuous Deployment GitHub Action invokes the
  # Continuous-Staging-Deploy trigger based on the git tag.
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud artifacts docker tags add "us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$COMMIT_SHA" "us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$TAG_NAME"
    id: tag-with-version
    waitFor:
      - build-justice-counts-image
  # Deploy the image to Cloud Run for publisher.
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$_PUBLISHER_CLOUD_RUN_SERVICE"
      - "--image=us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$COMMIT_SHA"
      - "--platform=managed" # Specify Cloud Run (fully managed)
      - "--region=us-central1" # Specify the region where your Cloud Run service will be deployed
    id: run-deploy-publisher
  # Update the traffic to the latest revision for publisher.
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "services"
      - "update-traffic"
      - "$_PUBLISHER_CLOUD_RUN_SERVICE"
      - "--to-latest"
      - "--platform=managed"
      - "--region=us-central1"
    id: update-traffic-publisher
    waitFor:
      - run-deploy-publisher
  # Deploy the image to Cloud Run for agency-dashboard.
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "$_DASHBOARD_CLOUD_RUN_SERVICE"
      - "--image=us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$COMMIT_SHA"
      - "--platform=managed" # Specify Cloud Run (fully managed)
      - "--region=us-central1" # Specify the region where your Cloud Run service will be deployed
    id: run-deploy-agency-dashboard
  # Update the traffic to the latest revision for agency-dashboard.
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "services"
      - "update-traffic"
      - "$_DASHBOARD_CLOUD_RUN_SERVICE"
      - "--to-latest"
      - "--platform=managed"
      - "--region=us-central1"
    id: update-traffic-agency-dashboard
    waitFor:
      - run-deploy-agency-dashboard
  # Deploy revisions to the following cloud run services.
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "jobs"
      - "update"
      - "recurring-report-creation"
      - "--image"
      - "us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$COMMIT_SHA"
      - "--region"
      - "us-central1"
    waitFor:
      - build-justice-counts-image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "jobs"
      - "update"
      - "recurring-new-mexico-courts-dataxchange"
      - "--image"
      - "us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$COMMIT_SHA"
      - "--region"
      - "us-central1"
    waitFor:
      - build-justice-counts-image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "jobs"
      - "update"
      - "csg-data-pull"
      - "--image"
      - "us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$COMMIT_SHA"
      - "--region"
      - "us-central1"
    waitFor:
      - build-justice-counts-image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "jobs"
      - "update"
      - "user-permission-check"
      - "--image"
      - "us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$COMMIT_SHA"
      - "--region"
      - "us-central1"
    waitFor:
      - build-justice-counts-image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "jobs"
      - "update"
      - "upload-reminder-email-job"
      - "--image"
      - "us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$COMMIT_SHA"
      - "--region"
      - "us-central1"
    waitFor:
      - build-justice-counts-image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "jobs"
      - "update"
      - "copy-superagency-metric-settings-to-child-agencies"
      - "--image"
      - "us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/main:$COMMIT_SHA"
      - "--region"
      - "us-central1"
    waitFor:
      - tag-as-latest
timeout: 3600s
options:
  machineType: N1_HIGHCPU_32
  logging: CLOUD_LOGGING_ONLY
