# Configuration file for the Deploy-to-playtesting trigger in justice-counts-staging.
steps:
  # Build the Recidiviz Base docker image
  - name: "gcr.io/kaniko-project/executor:v1.8.1"
    args:
      - "--dockerfile=Dockerfile.recidiviz-base"
      - "--cache=true"
      - >-
        --destination=us-central1-docker.pkg.dev/justice-counts-staging/recidiviz-base-images/recidiviz-base:latest
    id: recidiviz-base
  # Build the Justice Counts docker image containing both Publisher and Agency dashboard
  - name: "gcr.io/kaniko-project/executor:v1.8.1"
    args:
      - "--dockerfile=Dockerfile.justice-counts"
      - >-
        --destination=us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/$_SUBDIRECTORY:$COMMIT_SHA
      - "--build-arg"
      - FRONTEND_URL=$_FRONTEND_URL
    id: justice-counts-image
    waitFor:
      - recidiviz-base
  # Deploy the docker image to playtesting.
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - "--image"
      - >-
        us-central1-docker.pkg.dev/justice-counts-staging/publisher-and-dashboard-images/$_SUBDIRECTORY:$COMMIT_SHA
      - "--project"
      - justice-counts-staging
      - "--region"
      - us-central1
      - "--tag"
      - $_URL_TAG
      - "--no-traffic"
    waitFor:
      - justice-counts-image
    entrypoint: gcloud
timeout: 3600s
options:
  machineType: N1_HIGHCPU_32
  logging: CLOUD_LOGGING_ONLY
