# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2025 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================
"""Aggregated metrics collection definition for our standard set of aggregated metrics.
"""

from recidiviz.aggregated_metrics.aggregated_metric_collection_config import (
    AggregatedMetricsCollection,
)
from recidiviz.aggregated_metrics.aggregated_metrics_view_collector import (
    collect_aggregated_metric_view_builders_for_collection,
)
from recidiviz.aggregated_metrics.dataset_config import AGGREGATED_METRICS_DATASET_ID
from recidiviz.aggregated_metrics.metric_time_period_config import (
    MetricTimePeriodConfig,
)
from recidiviz.aggregated_metrics.models.aggregated_metric import AggregatedMetric
from recidiviz.aggregated_metrics.models.aggregated_metric_configurations import (
    ABSCONSIONS_BENCH_WARRANTS,
    ABSCONSIONS_BENCH_WARRANTS_FROM_PAROLE,
    ABSCONSIONS_BENCH_WARRANTS_FROM_PROBATION,
    ANY_INCARCERATION_365,
    ASSIGNMENTS,
    AVG_ACTIVE_LENGTH_OF_STAY_HOUSING_UNIT_TYPE_METRICS,
    AVG_ACTIVE_LENGTH_OF_STAY_SOLITARY_CONFINEMENT,
    AVG_AGE,
    AVG_CRITICAL_CASELOAD_SIZE,
    AVG_DAILY_CASELOAD_OFFICER,
    AVG_DAILY_POPULATION,
    AVG_DAILY_POPULATION_COMMUNITY_CONFINEMENT,
    AVG_DAILY_POPULATION_DOMESTIC_VIOLENCE_CASE_TYPE,
    AVG_DAILY_POPULATION_DRUG_CASE_TYPE,
    AVG_DAILY_POPULATION_EMPLOYED,
    AVG_DAILY_POPULATION_FEMALE,
    AVG_DAILY_POPULATION_GENERAL_CASE_TYPE,
    AVG_DAILY_POPULATION_GENERAL_INCARCERATION,
    AVG_DAILY_POPULATION_HIGH_RISK_LEVEL,
    AVG_DAILY_POPULATION_HOUSING_TYPE_METRICS,
    AVG_DAILY_POPULATION_LIMITED_SUPERVISION_JUSTICE_IMPACT,
    AVG_DAILY_POPULATION_LOW_RISK_LEVEL,
    AVG_DAILY_POPULATION_MAXIMUM_CUSTODY,
    AVG_DAILY_POPULATION_MAXIMUM_CUSTODY_JUSTICE_IMPACT,
    AVG_DAILY_POPULATION_MEDIUM_CUSTODY,
    AVG_DAILY_POPULATION_MEDIUM_CUSTODY_JUSTICE_IMPACT,
    AVG_DAILY_POPULATION_MENTAL_HEALTH_CASE_TYPE,
    AVG_DAILY_POPULATION_MINIMUM_CUSTODY,
    AVG_DAILY_POPULATION_MINIMUM_CUSTODY_JUSTICE_IMPACT,
    AVG_DAILY_POPULATION_NONLIMITED_SUPERVISION,
    AVG_DAILY_POPULATION_NONLIMITED_SUPERVISION_JUSTICE_IMPACT,
    AVG_DAILY_POPULATION_NONWHITE,
    AVG_DAILY_POPULATION_OTHER_CASE_TYPE,
    AVG_DAILY_POPULATION_PAROLE,
    AVG_DAILY_POPULATION_PAROLE_BOARD_HOLD,
    AVG_DAILY_POPULATION_PAST_FULL_TERM_RELEASE_DATE,
    AVG_DAILY_POPULATION_PAST_PAROLE_ELIGIBILITY_DATE,
    AVG_DAILY_POPULATION_PROBATION,
    AVG_DAILY_POPULATION_SEX_OFFENSE_CASE_TYPE,
    AVG_DAILY_POPULATION_SHOCK_INCARCERATION,
    AVG_DAILY_POPULATION_SOLITARY_CONFINEMENT,
    AVG_DAILY_POPULATION_SOLITARY_CONFINEMENT_JUSTICE_IMPACT,
    AVG_DAILY_POPULATION_STATE_PRISON,
    AVG_DAILY_POPULATION_SUPERVISION_LEVEL_METRICS,
    AVG_DAILY_POPULATION_TASK_ELIGIBLE_METRICS_INCARCERATION,
    AVG_DAILY_POPULATION_TASK_ELIGIBLE_METRICS_SUPERVISION,
    AVG_DAILY_POPULATION_TREATMENT_IN_PRISON,
    AVG_DAILY_POPULATION_UNKNOWN_CASE_TYPE,
    AVG_LSIR_SCORE,
    AVG_NUM_SUPERVISION_OFFICERS_INSIGHTS_CASELOAD_CATEGORY_METRICS,
    COMMUNITY_CONFINEMENT_SUPERVISION_STARTS,
    CONTACTS_ATTEMPTED,
    CUSTODY_LEVEL_DOWNGRADES,
    CUSTODY_LEVEL_DOWNGRADES_TO_MINIMUM,
    CUSTODY_LEVEL_UPGRADES,
    DAYS_ABSCONDED_365,
    DAYS_AT_LIBERTY_365,
    DAYS_ELIGIBLE_AT_TASK_COMPLETION_METRICS_INCARCERATION,
    DAYS_ELIGIBLE_AT_TASK_COMPLETION_METRICS_SUPERVISION,
    DAYS_EMPLOYED_365,
    DAYS_IN_COMMUNITY_365,
    DAYS_INCARCERATED_365,
    DAYS_TO_FIRST_INCARCERATION_365,
    DAYS_TO_FIRST_LIBERTY_365,
    DRUG_SCREENS,
    DRUG_SCREENS_POSITIVE,
    EARLY_DISCHARGE_REQUESTS,
    EMPLOYED_STATUS_ENDS,
    EMPLOYED_STATUS_STARTS,
    EMPLOYER_CHANGES_365,
    HOUSING_UNIT_TYPE_ENDS,
    HOUSING_UNIT_TYPE_LENGTH_OF_STAY_BY_END,
    HOUSING_UNIT_TYPE_LENGTH_OF_STAY_BY_START,
    HOUSING_UNIT_TYPE_STARTS,
    INCARCERATION_INCIDENTS,
    INCARCERATION_STARTS,
    INCARCERATION_STARTS_AND_INFERRED,
    INCARCERATION_STARTS_AND_INFERRED_FROM_PAROLE,
    INCARCERATION_STARTS_AND_INFERRED_FROM_PROBATION,
    INCARCERATION_STARTS_AND_INFERRED_TECHNICAL_VIOLATION_NO_PRIOR_TREATMENT_REFERRAL,
    INCARCERATION_STARTS_AND_INFERRED_WITH_VIOLATION_TYPE_METRICS,
    INCARCERATION_STARTS_MOST_SEVERE_VIOLATION_TYPE_NOT_ABSCONSION,
    INCARCERATION_STARTS_TECHNICAL_VIOLATION_NO_PRIOR_TREATMENT_REFERRAL,
    INCARCERATION_STARTS_WITH_VIOLATION_TYPE_METRICS,
    INCARCERATIONS_INFERRED,
    INCARCERATIONS_INFERRED_WITH_VIOLATION_TYPE_METRICS,
    INCARCERATIONS_TEMPORARY,
    LATE_OPPORTUNITY_METRICS_INCARCERATION,
    LATE_OPPORTUNITY_METRICS_SUPERVISION,
    LIBERTY_STARTS,
    LSIR_ASSESSMENTS,
    MAX_DAYS_STABLE_EMPLOYMENT_365,
    NUMBER_MONTHS_BETWEEN_DOWNGRADE_AND_ASSESSMENT_DUE,
    NUMBER_MONTHS_BETWEEN_DOWNGRADE_TO_MINIMUM_AND_ASSESSMENT_DUE,
    PAROLE_BOARD_HEARINGS,
    PAROLE_BOARD_HEARINGS_APPROVED,
    PAROLE_BOARD_HEARINGS_AVG_DAYS_SINCE_INCARCERATION,
    PAROLE_BOARD_HEARINGS_CONTINUED,
    PAROLE_BOARD_HEARINGS_DENIED,
    PENDING_CUSTODY_STARTS,
    PERSON_DAYS_TASK_ELIGIBLE_METRICS_INCARCERATION,
    PERSON_DAYS_TASK_ELIGIBLE_METRICS_SUPERVISION,
    PERSON_DAYS_WEIGHTED_JUSTICE_IMPACT,
    PROP_PERIOD_WITH_CRITICAL_CASELOAD,
    SOLITARY_CONFINEMENT_ENDS,
    SOLITARY_CONFINEMENT_LENGTH_OF_STAY_BY_END,
    SOLITARY_CONFINEMENT_LENGTH_OF_STAY_BY_START,
    SOLITARY_CONFINEMENT_STARTS,
    SOLITARY_CONFINEMENT_STARTS_LAST_YEAR,
    SUPERVISION_LEVEL_DOWNGRADES,
    SUPERVISION_LEVEL_DOWNGRADES_TO_LIMITED,
    SUPERVISION_LEVEL_UPGRADES,
    SUPERVISION_STARTS,
    SUPERVISION_STARTS_FROM_INCARCERATION,
    TASK_COMPLETED_METRICS_INCARCERATION,
    TASK_COMPLETED_METRICS_SUPERVISION,
    TASK_COMPLETED_WHILE_ELIGIBLE_METRICS_INCARCERATION,
    TASK_COMPLETED_WHILE_ELIGIBLE_METRICS_SUPERVISION,
    TREATMENT_REFERRALS,
    TREATMENT_STARTS,
    VIOLATIONS,
    VIOLATIONS_BY_TYPE_METRICS,
)
from recidiviz.aggregated_metrics.models.metric_population_type import (
    MetricPopulationType,
)
from recidiviz.aggregated_metrics.models.metric_unit_of_analysis_type import (
    MetricUnitOfAnalysisType,
)
from recidiviz.utils.environment import GCP_PROJECT_STAGING
from recidiviz.utils.metadata import local_project_id_override

_UNIT_OF_ANALYSIS_TYPES_BY_POPULATION_TYPE: dict[
    MetricPopulationType, list[MetricUnitOfAnalysisType]
] = {
    MetricPopulationType.INCARCERATION: [
        MetricUnitOfAnalysisType.FACILITY,
        MetricUnitOfAnalysisType.FACILITY_COUNSELOR,
        MetricUnitOfAnalysisType.STATE_CODE,
    ],
    MetricPopulationType.SUPERVISION: [
        MetricUnitOfAnalysisType.SUPERVISION_OFFICER,
        MetricUnitOfAnalysisType.SUPERVISION_OFFICER_OR_PREVIOUS_IF_TRANSITIONAL,
        MetricUnitOfAnalysisType.SUPERVISION_UNIT,
        MetricUnitOfAnalysisType.SUPERVISION_OFFICE,
        MetricUnitOfAnalysisType.SUPERVISION_DISTRICT,
        MetricUnitOfAnalysisType.STATE_CODE,
    ],
    MetricPopulationType.JUSTICE_INVOLVED: [
        MetricUnitOfAnalysisType.STATE_CODE,
        MetricUnitOfAnalysisType.FACILITY,
        MetricUnitOfAnalysisType.SUPERVISION_DISTRICT,
    ],
}

# TODO(#29291): Filter this metrics list down to only metrics we use downstream in
#  products / Looker, then make it easier for DAs, etc to query configured metrics
#  in an ad-hoc way from notebooks, etc.
# Defines a map of metrics that are part of our standard aggregated metrics collection,
# grouped by the population they should be calculated for.
# Metrics should be added only if necessary for products or analyses, since additions
# will have a meaningful impact on view update performance.
METRICS_BY_POPULATION_TYPE: dict[MetricPopulationType, list[AggregatedMetric]] = {
    MetricPopulationType.INCARCERATION: [
        # Average daily population
        AVG_DAILY_POPULATION,
        # Average daily population, person demographics
        AVG_AGE,
        AVG_DAILY_POPULATION_FEMALE,
        AVG_DAILY_POPULATION_NONWHITE,
        # Average daily population, compartment level 2
        AVG_DAILY_POPULATION_COMMUNITY_CONFINEMENT,
        AVG_DAILY_POPULATION_GENERAL_INCARCERATION,
        AVG_DAILY_POPULATION_PAROLE_BOARD_HOLD,
        AVG_DAILY_POPULATION_SHOCK_INCARCERATION,
        AVG_DAILY_POPULATION_TREATMENT_IN_PRISON,
        # Average daily population, solitary confinement
        AVG_DAILY_POPULATION_SOLITARY_CONFINEMENT,
        # Average daily population, state prison
        AVG_DAILY_POPULATION_STATE_PRISON,
        # Average daily population, solitary confinement housing type
        *AVG_DAILY_POPULATION_HOUSING_TYPE_METRICS,
        # Average daily population, facility custody level
        AVG_DAILY_POPULATION_MAXIMUM_CUSTODY,
        AVG_DAILY_POPULATION_MEDIUM_CUSTODY,
        AVG_DAILY_POPULATION_MINIMUM_CUSTODY,
        # Average daily population, sentence info
        AVG_DAILY_POPULATION_PAST_FULL_TERM_RELEASE_DATE,
        AVG_DAILY_POPULATION_PAST_PAROLE_ELIGIBILITY_DATE,
        # Risk score
        AVG_DAILY_POPULATION_HIGH_RISK_LEVEL,
        AVG_DAILY_POPULATION_LOW_RISK_LEVEL,
        AVG_LSIR_SCORE,
        # Events
        COMMUNITY_CONFINEMENT_SUPERVISION_STARTS,
        *HOUSING_UNIT_TYPE_ENDS,
        *HOUSING_UNIT_TYPE_LENGTH_OF_STAY_BY_START,
        *HOUSING_UNIT_TYPE_LENGTH_OF_STAY_BY_END,
        *HOUSING_UNIT_TYPE_STARTS,
        LIBERTY_STARTS,
        SOLITARY_CONFINEMENT_ENDS,
        SOLITARY_CONFINEMENT_STARTS,
        SOLITARY_CONFINEMENT_STARTS_LAST_YEAR,
        SUPERVISION_STARTS,
        SUPERVISION_STARTS_FROM_INCARCERATION,
        INCARCERATION_INCIDENTS,
        # Solitary confinement length of stay
        *AVG_ACTIVE_LENGTH_OF_STAY_HOUSING_UNIT_TYPE_METRICS,
        AVG_ACTIVE_LENGTH_OF_STAY_SOLITARY_CONFINEMENT,
        SOLITARY_CONFINEMENT_LENGTH_OF_STAY_BY_END,
        SOLITARY_CONFINEMENT_LENGTH_OF_STAY_BY_START,
        # Assignment window metrics
        ASSIGNMENTS,
        DAYS_AT_LIBERTY_365,
        DAYS_IN_COMMUNITY_365,
        DAYS_INCARCERATED_365,
        ## Workflows
        # TODO(#21261): Automatically pull in all incarceration related TES metrics when we have a param in TES to distinguish
        *AVG_DAILY_POPULATION_TASK_ELIGIBLE_METRICS_INCARCERATION,
        *LATE_OPPORTUNITY_METRICS_INCARCERATION,
        *PERSON_DAYS_TASK_ELIGIBLE_METRICS_INCARCERATION,
        *TASK_COMPLETED_METRICS_INCARCERATION,
        *TASK_COMPLETED_WHILE_ELIGIBLE_METRICS_INCARCERATION,
        *DAYS_ELIGIBLE_AT_TASK_COMPLETION_METRICS_INCARCERATION,
        ## Custody level changes,
        CUSTODY_LEVEL_UPGRADES,
        CUSTODY_LEVEL_DOWNGRADES,
        CUSTODY_LEVEL_DOWNGRADES_TO_MINIMUM,
        NUMBER_MONTHS_BETWEEN_DOWNGRADE_AND_ASSESSMENT_DUE,
        NUMBER_MONTHS_BETWEEN_DOWNGRADE_TO_MINIMUM_AND_ASSESSMENT_DUE,
        # Parole bord hearings
        PAROLE_BOARD_HEARINGS,
        PAROLE_BOARD_HEARINGS_APPROVED,
        PAROLE_BOARD_HEARINGS_AVG_DAYS_SINCE_INCARCERATION,
        PAROLE_BOARD_HEARINGS_CONTINUED,
        PAROLE_BOARD_HEARINGS_DENIED,
    ],
    MetricPopulationType.SUPERVISION: [
        # Population/caseload information
        AVG_DAILY_POPULATION,
        AVG_CRITICAL_CASELOAD_SIZE,
        AVG_DAILY_CASELOAD_OFFICER,
        PROP_PERIOD_WITH_CRITICAL_CASELOAD,
        # Average daily population, person demographics
        AVG_AGE,
        AVG_DAILY_POPULATION_FEMALE,
        AVG_DAILY_POPULATION_NONWHITE,
        # Average daily population, compartment level 2
        AVG_DAILY_POPULATION_COMMUNITY_CONFINEMENT,
        AVG_DAILY_POPULATION_PAROLE,
        AVG_DAILY_POPULATION_PROBATION,
        # Average daily population, case type
        AVG_DAILY_POPULATION_DOMESTIC_VIOLENCE_CASE_TYPE,
        AVG_DAILY_POPULATION_DRUG_CASE_TYPE,
        AVG_DAILY_POPULATION_GENERAL_CASE_TYPE,
        AVG_DAILY_POPULATION_MENTAL_HEALTH_CASE_TYPE,
        AVG_DAILY_POPULATION_OTHER_CASE_TYPE,
        AVG_DAILY_POPULATION_SEX_OFFENSE_CASE_TYPE,
        AVG_DAILY_POPULATION_UNKNOWN_CASE_TYPE,
        # Average daily population, supervision level
        *AVG_DAILY_POPULATION_SUPERVISION_LEVEL_METRICS,
        AVG_DAILY_POPULATION_NONLIMITED_SUPERVISION,
        ## Average daily population, sentence info
        AVG_DAILY_POPULATION_PAST_FULL_TERM_RELEASE_DATE,
        # Average daily population, other attributes
        AVG_DAILY_POPULATION_EMPLOYED,
        # Risk score
        AVG_DAILY_POPULATION_HIGH_RISK_LEVEL,
        AVG_DAILY_POPULATION_LOW_RISK_LEVEL,
        AVG_LSIR_SCORE,
        # Average daily population, caseload category and type
        *AVG_NUM_SUPERVISION_OFFICERS_INSIGHTS_CASELOAD_CATEGORY_METRICS,
        # Events
        ## Session transitions
        ABSCONSIONS_BENCH_WARRANTS,
        ABSCONSIONS_BENCH_WARRANTS_FROM_PAROLE,
        ABSCONSIONS_BENCH_WARRANTS_FROM_PROBATION,
        EARLY_DISCHARGE_REQUESTS,
        INCARCERATIONS_INFERRED,
        *INCARCERATIONS_INFERRED_WITH_VIOLATION_TYPE_METRICS,
        INCARCERATION_STARTS,
        INCARCERATION_STARTS_MOST_SEVERE_VIOLATION_TYPE_NOT_ABSCONSION,
        *INCARCERATION_STARTS_WITH_VIOLATION_TYPE_METRICS,
        INCARCERATION_STARTS_TECHNICAL_VIOLATION_NO_PRIOR_TREATMENT_REFERRAL,
        INCARCERATION_STARTS_AND_INFERRED,
        *INCARCERATION_STARTS_AND_INFERRED_WITH_VIOLATION_TYPE_METRICS,
        INCARCERATION_STARTS_AND_INFERRED_TECHNICAL_VIOLATION_NO_PRIOR_TREATMENT_REFERRAL,
        INCARCERATION_STARTS_AND_INFERRED_FROM_PAROLE,
        INCARCERATION_STARTS_AND_INFERRED_FROM_PROBATION,
        INCARCERATIONS_TEMPORARY,
        LIBERTY_STARTS,
        PENDING_CUSTODY_STARTS,
        SUPERVISION_STARTS,
        SUPERVISION_STARTS_FROM_INCARCERATION,
        VIOLATIONS,
        *VIOLATIONS_BY_TYPE_METRICS,
        ## Supervision level changes
        SUPERVISION_LEVEL_DOWNGRADES,
        SUPERVISION_LEVEL_UPGRADES,
        SUPERVISION_LEVEL_DOWNGRADES_TO_LIMITED,
        ## Drug Screens
        DRUG_SCREENS,
        DRUG_SCREENS_POSITIVE,
        ## LSI-R Assessments
        LSIR_ASSESSMENTS,
        ## Contacts
        CONTACTS_ATTEMPTED,
        ## Employment Changes
        EMPLOYED_STATUS_ENDS,
        EMPLOYED_STATUS_STARTS,
        EMPLOYER_CHANGES_365,
        MAX_DAYS_STABLE_EMPLOYMENT_365,
        ## Program Referrals
        TREATMENT_REFERRALS,
        ## Program Starts
        TREATMENT_STARTS,
        # TODO(#18344): Use task population_types to only calculate relevant workflows metrics for a single population
        ## Workflows - eligibility metrics
        *AVG_DAILY_POPULATION_TASK_ELIGIBLE_METRICS_SUPERVISION,
        *LATE_OPPORTUNITY_METRICS_SUPERVISION,
        *PERSON_DAYS_TASK_ELIGIBLE_METRICS_SUPERVISION,
        *TASK_COMPLETED_METRICS_SUPERVISION,
        *TASK_COMPLETED_WHILE_ELIGIBLE_METRICS_SUPERVISION,
        *DAYS_ELIGIBLE_AT_TASK_COMPLETION_METRICS_SUPERVISION,
        # Assignment window metrics
        ASSIGNMENTS,
        ANY_INCARCERATION_365,
        DAYS_ABSCONDED_365,
        DAYS_AT_LIBERTY_365,
        DAYS_IN_COMMUNITY_365,
        DAYS_INCARCERATED_365,
        DAYS_EMPLOYED_365,
        DAYS_TO_FIRST_INCARCERATION_365,
        DAYS_TO_FIRST_LIBERTY_365,
    ],
    MetricPopulationType.JUSTICE_INVOLVED: [
        # Population metrics
        AVG_DAILY_POPULATION,
        AVG_DAILY_POPULATION_LIMITED_SUPERVISION_JUSTICE_IMPACT,
        AVG_DAILY_POPULATION_MAXIMUM_CUSTODY_JUSTICE_IMPACT,
        AVG_DAILY_POPULATION_MEDIUM_CUSTODY_JUSTICE_IMPACT,
        AVG_DAILY_POPULATION_MINIMUM_CUSTODY_JUSTICE_IMPACT,
        AVG_DAILY_POPULATION_NONLIMITED_SUPERVISION_JUSTICE_IMPACT,
        AVG_DAILY_POPULATION_SOLITARY_CONFINEMENT_JUSTICE_IMPACT,
        # Weighted population metrics
        PERSON_DAYS_WEIGHTED_JUSTICE_IMPACT,
        # Metrics required for sentence metrics
        LIBERTY_STARTS,
    ],
}

_STANDARD_METRICS_YEARS_TRACKED = 7

STANDARD_AGGREGATED_METRICS_COLLECTION_CONFIG = AggregatedMetricsCollection.build(
    output_dataset_id=AGGREGATED_METRICS_DATASET_ID,
    time_periods=[
        MetricTimePeriodConfig.year_periods_rolling_monthly(
            lookback_months=_STANDARD_METRICS_YEARS_TRACKED * 12
        ),
        MetricTimePeriodConfig.quarter_periods_rolling_monthly(
            lookback_months=_STANDARD_METRICS_YEARS_TRACKED * 12
        ),
        MetricTimePeriodConfig.month_periods(
            lookback_months=_STANDARD_METRICS_YEARS_TRACKED * 12
        ),
    ],
    unit_of_analysis_types_by_population_type=_UNIT_OF_ANALYSIS_TYPES_BY_POPULATION_TYPE,
    metrics_by_population_type=METRICS_BY_POPULATION_TYPE,
    disaggregate_by_observation_attributes=None,
)


if __name__ == "__main__":
    with local_project_id_override(GCP_PROJECT_STAGING):
        for vb in collect_aggregated_metric_view_builders_for_collection(
            STANDARD_AGGREGATED_METRICS_COLLECTION_CONFIG
        ):
            vb.build_and_print()
