# Configuration for which validations to run for region US_CO.

region_code: US_CO
dev_mode: False
exclusions:
  - validation_name: case_insights_rates_missing_charges
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: Sentencing assistant case insights are not configured/launched for this state
  - validation_name: case_insights_record_sentencing_charge_record_offense_mismatch
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: Sentencing assistant case insights are not configured/launched for this state
max_allowed_error_overrides: []
num_allowed_rows_overrides: []
