name: Docker CI
on:
  schedule:
    - cron: "15 2 * * *"
  # everyday at 2:15
jobs:
  build:
    if: github.repository == 'Recidiviz/pulse-data'
    name: docker-image-scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Build an image from Dockerfile
        run: |
          docker build . -t us.gcr.io/recidiviz-staging/appengine/default:latest
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@841fb371db7b5cd339e5b2d55c92f5dbd730ac9f # master
        with:
          image-ref: "us.gcr.io/recidiviz-staging/appengine/default:latest"
          format: "sarif"
          ignore-unfixed: true
          output: "trivy-results.sarif"
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@1ea673e9815322ac82c7c2a4d66658080e88158c # v2
        with:
          sarif_file: "trivy-results.sarif"
      - name: Run Dockle
        uses: erzz/dockle-action@69369bc745ee29813f730231a821bcd4f71cd290 # v1
        with:
          image: "us.gcr.io/recidiviz-staging/appengine/default:latest"
          report-format: json
          report-name: dockle-report
      - name: Upload Report
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        if: always()
        with:
          name: Dockle Report
          path: dockle-report.json
