# Recidiviz - a data platform for criminal justice reform
# Copyright (C) 2023 Recidiviz, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# =============================================================================
"""Defines PersonEventType enum."""
from enum import Enum


class PersonEventType(Enum):
    """Category of event-shaped data"""

    ABSCONSION_BENCH_WARRANT = "ABSCONSION_BENCH_WARRANT"
    COMPARTMENT_LEVEL_2_START = "COMPARTMENT_LEVEL_2_START"
    CUSTODY_LEVEL_CHANGE = "CUSTODY_LEVEL_CHANGE"
    DRUG_SCREEN = "DRUG_SCREEN"
    EARLY_DISCHARGE_REQUEST = "EARLY_DISCHARGE_REQUEST"
    EARLY_DISCHARGE_REQUEST_DECISION = "EARLY_DISCHARGE_REQUEST_DECISION"
    EMPLOYMENT_PERIOD_START = "EMPLOYMENT_PERIOD_START"
    EMPLOYMENT_STATUS_CHANGE = "EMPLOYMENT_STATUS_CHANGE"
    INCARCERATION_INCIDENT = "INCARCERATION_INCIDENT"
    INCARCERATION_START_TEMPORARY = "INCARCERATION_START_TEMPORARY"
    INCARCERATION_START = "INCARCERATION_START"
    LIBERTY_START = "LIBERTY_START"
    PAROLE_HEARING = "PAROLE_HEARING"
    PENDING_CUSTODY_START = "PENDING_CUSTODY_START"
    RISK_SCORE_ASSESSMENT = "RISK_SCORE_ASSESSMENT"
    SUPERVISING_OFFICER_CHANGE = "SUPERVISING_OFFICER_CHANGE"
    SUPERVISING_OFFICER_NEW_ASSIGNMENT = "SUPERVISING_OFFICER_NEW_ASSIGNMENT"
    SUPERVISION_CONTACT = "SUPERVISION_CONTACT"
    SUPERVISION_LEVEL_CHANGE = "SUPERVISION_LEVEL_CHANGE"
    SUPERVISION_START = "SUPERVISION_START"
    SUPERVISION_TERMINATION_WITH_INCARCERATION_REASON = (
        "SUPERVISION_TERMINATION_WITH_INCARCERATION_REASON"
    )
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_ELIGIBILITY_START = "TASK_ELIGIBILITY_START"
    TASK_ELIGIBLE_30_DAYS = "TASK_ELIGIBLE_30_DAYS"
    TASK_ELIGIBLE_7_DAYS = "TASK_ELIGIBLE_7_DAYS"
    TREATMENT_REFERRAL = "TREATMENT_REFERRAL"
    VARIANT_ASSIGNMENT = "VARIANT_ASSIGNMENT"
    VIOLATION = "VIOLATION"
    VIOLATION_RESPONSE = "VIOLATION_RESPONSE"
